### ISSUE TITLE
Laravel 5.1 Middleware's using Sentinel 2.0

### ISSUE THREAD

**Issue by kevinreynolds** [cartalyst/sentinel#100]
I am creating an app using Laravel 5.1 and Sentinel. I have created custom Http Middleware to check whether the user is guest or authenticated. The problem that I am facing is Sentinel::check() and Sentinel::getUser() always returns FALSE in the Middleware's even when the user is logged in.

I have gone through the code and can't understand what causing the issue. I am running the application on a virtual homestead development server.

Can anyone provide some insight into why this may be happening?

**Comment by brunogaspar** [comment]
Since you haven't provided any code, is quite difficult to know what's going on with your middleware.

**Comment by kevinreynolds** [comment]
Sorry about that. This my middleware to restrict the request only to the guests

<?php 

namespace App\Http\Middleware;

use Closure;
use Cartalyst\Sentinel\Native\Facades\Sentinel;
use Kamaln7\Toastr\Facades\Toastr;

class SentinelGuest
{
    public function handle($request, Closure $next)
    {
        if(Sentinel::check())
        {
            Toastr::info('This page is only accessible to guests', 'Guest Access Only');
            return redirect()->route('home');
        }

        return $next($request);
    }
}

**Comment by brunogaspar** [comment]
You're using the wrong facade.

If you're on Laravel you need to use the Laravel facade, not the native one.

**Comment by kevinreynolds** [comment]
Thanks for that, I have changed that line to 
use Cartalyst\Sentinel\Laravel\Facades\Sentinel;

But still Sentinel::check() returns FALSE

**Comment by brunogaspar** [comment]
Are you sure you're logged in? I can't reproduce this.

**Comment by kevinreynolds** [comment]
Yes I am sure. 
Would you like me to share any other file?

**Comment by brunogaspar** [comment]
Paste your `app/Http/Kernel.php` file contents and if possible a route or controller that's using the middleware.

**Comment by kevinreynolds** [comment]
This is my Kernel file:

<?php

namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \App\Http\Middleware\EncryptCookies::class,
        \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
        \App\Http\Middleware\VerifyCsrfToken::class,
    ];

    /**
     * The application's route middleware.
     *
     * @var array
     */
    protected $routeMiddleware = [
        'sentinel.auth' => \App\Http\Middleware\SentinelAuth::class,
        'sentinel.guest' => \App\Http\Middleware\SentinelGuest::class,
        'sentinel.admin' => \App\Http\Middleware\SentinelAdminAccess::class,
    ];
}

**Comment by kevinreynolds** [comment]
I was using the wrong Sentinel Facade on my SessionsController
- use Cartalyst\Sentinel\Native\Facades\Sentinel;

Changed to the correct Facade
- use Cartalyst\Sentinel\Laravel\Facades\Sentinel;

and it WORKED.

**Comment by brunogaspar** [comment]
:+1:

**Comment by kevinreynolds** [comment]
Thanks Bruno for walking me through.

**Comment by brunogaspar** [comment]
No problem.

**Comment by dev-mamun** [comment]
Hi i face the same problem Sentinel::check() return false after user login. but this problem happened when i try to access form my mobile app. when access from web its working fine. could any one explain me in details what happen. what i do wrong?

**Comment by praditha** [comment]
Hi, I get the same issue with dev-mamun, any body can help..?
@dev-mamun have you found the solutions..?

**Comment by dev-mamun** [comment]
@praditha i use jwt as alternative
