### ISSUE TITLE
ErrorExceptions in PermissionsTrait.php line 148

### ISSUE THREAD

**Issue by kevinreynolds** [cartalyst/sentinel#101]
I am getting the error 'ErrorExceptions in PermissionsTrait.php' when I try to check permission of a user

$user = Sentinel::getUser();
$user->hasAccess('admin.*');

The above code throws up the following error:

Argument 2 passed to Cartalyst\Sentinel\Permissions\StandardPermissions::preparePermissions() must be of the type array, null given.

The way I stored permissions on the database table field are as below:

{"admin.users": true, "admin.organisations": true, "admin.chemicals": false}

I tried updating the package and still no luck for me.  Also saw a similar closed issue at https://github.com/cartalyst/sentinel/issues/9 but wasn't helpful either.

Any suggestions on this matter?

**Comment by brunogaspar** [comment]
I'm not being able to reproduce any issue with the permissions you've provided.

Tried to have these on a role and on a user directly, both working fine. Tests are passing as well for the permissions, so it's most likely an issue on your end.

@suwardany Any idea?

**Comment by suwardany** [comment]
This happens when you've invalid permissions on any attached roles, make sure permissions are properly set on the roles.

**Comment by kevinreynolds** [comment]
Is this the right way to set the permission on roles?
{"admin.users": true, "admin.organisations": true, "admin.chemicals": false}

**Comment by kevinreynolds** [comment]
Thank you @suwardany, there was a invalid permission attached to my role. Its all working now :+1:
