### ISSUE TITLE
Trouble accessing methods

### ISSUE THREAD

**Issue by iboinas** [cartalyst/sentinel#102]
Hello,

I'm trying to implement cartalyst/sentinel 2.0.x on Laravel 5.1
(right now getting v2.0.6)

on config.app, i add the 
```
//providers
Cartalyst\Sentinel\Laravel\SentinelServiceProvider::class

//alias
'Activation' => Cartalyst\Sentinel\Laravel\Facades\Activation::class,
'Reminder'   => Cartalyst\Sentinel\Laravel\Facades\Reminder::class,
'Sentinel'   => Cartalyst\Sentinel\Laravel\Facades\Sentinel::class,
```

and I can't seem to get to use "hasAnyAccess" or "hasAccess"

I can, for example, use:

Sentinel::registerAndActivate([
        'email'    => 'test@test.com',
        'password' => 'sentinel',
    ]);

to create a user and 

$credentials = [
        'email'    => 'test@test.com',
        'password' => 'sentinel',
    ];

    Sentinel::authenticate($credentials);

autheticate it with sucess!

Just i can't seem to user the permissions methods..

Wonder what am i doing wrong?

**Comment by brunogaspar** [comment]
You failed to explain what's happening when you call either the `hasAnyAccess` or the `hasAccess` methods.

**Comment by iboinas** [comment]
Sorry for late answer!

LEt's take an example
``` php
 <div class="col-lg-12">

                    {{ Sentinel::check() }}

                    @if( Sentinel::hasAnyAccess(['admin.copy']) )

                        tem acesso a admin.copy

                    @endif


                </div>
```

Check() returns the logged user, ok.
hasAnyAccess returns nothing, blank

I have other project where has AnyAccess is working, but can't find the difference.

(also, on barryvdh/laravel-ide-helper not all the methods appear...)

**Comment by iboinas** [comment]
``` php
                    {!! Sentinel::hasAnyAccess(['superuser'])  !!}
```

Let me add: if the user really has that access, it echoes 1

Else echoes nothing.

I can see it works, but the echoing got me wrong way, was that it?

Also, how can one make the facade be recognizable by the ide-helper?

Thanks in advance Bruno!!!

**Comment by iboinas** [comment]
Shame on me, i didn't read all the docs, "superuser" is no longer granting all permissions.

All is working, just don't know why the result is not "true" or "false"...

And what can be done so that all the methods goes into ide-helper?

**Comment by brunogaspar** [comment]
> All is working, just don't know why the result is not "true" or "false"...

It returns `true` `false` on my end and it's passing the tests, so i assume it's something on your end.

> And what can be done so that all the methods goes into ide-helper?

No idea.

**Comment by iboinas** [comment]
Bruno, everythign was ok, I did the stupidity of writing Acess with only one 'c'.
I'm very used to the IDE fullfilling the methods etc..

Do you mind I explore that idea with BarryV, https://github.com/barryvdh/laravel-ide-helper
and then add to Sentinel?

**Comment by drsii** [comment]
Feel free to explore and PR. We would be happy to take a look but we may or may not accept it, or we would postpone it until next major version which is the more likely scenario and when Laravel has it's own Sentinel Laravel bridge package.

**Comment by brunogaspar** [comment]
Not a fan of that kind of docblocks in packages.

**Comment by iboinas** [comment]
there would be no docblocks on sentinel package.
instead, a _ide_helper.php file is generated on the project root, that allows IDE to auto-complete when you are coding....

**Comment by brunogaspar** [comment]
So, you mean having a similar package just for Sentinel? If that's the case, you can basically create it if you want.

I don't believe this is something we'll be doing as we don't have time to invest on it.

**Comment by iboinas** [comment]
The issue was that some methods are called on __call, so the _ide_helper.php file generated would not consider this.

Solution is to add to ide-helper/config, on the extra key, the ones related to Sentinel...

``` php
/*
    |--------------------------------------------------------------------------
    | Extra classes
    |--------------------------------------------------------------------------
    |
    | These implementations are not really extended, but called with magic functions
    |
    */

    'extra' => array(
        'Eloquent' => array('Illuminate\Database\Eloquent\Builder', 'Illuminate\Database\Query\Builder'),
        'Session' => array('Illuminate\Session\Store'),

        'Sentinel' => array(
            'Cartalyst\Sentinel\Users\UserRepositoryInterface',
            'Cartalyst\Sentinel\Roles\RoleRepositoryInterface',
            'Cartalyst\Sentinel\Permissions\PermissionsInterface',
            'Cartalyst\Sentinel\Roles\RoleableInterface',
            'Cartalyst\Sentinel\Users\UserInterface')
    ),
```

Now we have autocompletion
![image](https://cloud.githubusercontent.com/assets/6516477/9193558/37cebe58-400c-11e5-8fe4-b96146110a2e.png)

Thank you for your time and patiente!! :)

**Comment by chrispage1** [comment]
@iboinas I've added this to my extra but I can't get the hinting to work.

E.g..

```
if(!Sentinel::getUser()->inRole()) {
    // do this. inRole() is showing as undefined.
}
```

Has something changed since last update?
