### ISSUE TITLE
Retrieving user roles

### ISSUE THREAD

**Issue by iboinas** [cartalyst/sentinel#103]
![image](https://cloud.githubusercontent.com/assets/6516477/9169931/62ef9e06-3f56-11e5-9d3e-03e7b97fa055.png)

![image](https://cloud.githubusercontent.com/assets/6516477/9169945/77f677d4-3f56-11e5-830f-d53f63514059.png)

![image](https://cloud.githubusercontent.com/assets/6516477/9169950/81455a30-3f56-11e5-954a-62a63cc72019.png)

![image](https://cloud.githubusercontent.com/assets/6516477/9169956/94a0df00-3f56-11e5-8913-e0b157a3dec0.png)

It doesnt find any roles, and it should, the one from id=21, right?

**Comment by brunogaspar** [comment]
You're doing it wrong.

Either do `Sentinel::findById(1)->roles;` or finish the query by doing `Sentinel::findById(1)->roles()->get();`.

**Comment by hbsoftco** [comment]
@brunogaspar 
How do I show it in user blade file?

**Comment by brunogaspar** [comment]
@hbsoftco Save the roles in a variable, pass that variable to a Blade view and then loop through the roles.

Something along these lines:

```php
$userId = 1;

$roles = Sentinel::findById($userId)->roles;

return view('user.roles', compact('roles'));
```

```php
<ul>
    @foreach ($roles as $role)
        <li>{{ $role->name }}</li>
    @endforeach
</ul>
```

Hope it helps!

**Comment by hbsoftco** [comment]
@brunogaspar thanks
