### ISSUE TITLE
Displaying all users in a role along with their role details

### ISSUE THREAD

**Issue by kevinreynolds** [cartalyst/sentinel#105]
How do I display all users assigned to a particular role in Sentinel? along with their role details.

Sentry has a function called findAllUsersInGroup(), does Sentinel have one?

**Comment by brunogaspar** [comment]
Pretty simple

```php
$role = Sentinel::findRoleById(1);

$users = $role->users()->with('roles')->get();
```

It's Eloquent, you can do whatever you need :)

**Comment by kevinreynolds** [comment]
Thanks

**Comment by UmerAbbas8** [comment]
can you please tell me how can i paginate the result that i get from 

$role = Sentinel::findRoleById(1);

$users = $role->users()->with('roles')->get();

please help me, 
thanks

**Comment by pankitgami** [comment]
You can use `paginate` method instead of `get`.

``` $role = Sentinel::findRoleById(1);

$users = $role->users()->with('roles')->get();

```

**Comment by UmerAbbas8** [comment]
it works, i wasn't aware that paginate can be used in place of get()

Thank you so much,
