### ISSUE TITLE
How do you disable and re-enable the user?

### ISSUE THREAD

**Issue by kevinreynolds** [cartalyst/sentinel#106]
How do you disable and re-enable the user using Sentinel?

**Comment by suwardany** [comment]
Hello @kevinreynolds 

You can't disable/enable users out of the box.

You could add such functionality using a new Checkpoint, check out the `ThrottleCheckpoint` as an example.

**Comment by jcorry** [comment]
I use the `Activation` feature to do this. `Activation::remove($user)` will remove the user's activation record. If the activation checkpoint is enabled in the config, this will prevent the user from authentication (while leaving all other user records intact).

**Comment by padmanabanparthi** [comment]
###
