### ISSUE TITLE
How to check allowed permissions, by user?

### ISSUE THREAD

**Issue by iboinas** [cartalyst/sentinel#107]
Hello,

Wondering, is there a quick way to display all the permissions that a certain user has?

Like, looping through every group permissions where the user is, combined with individual permissions, and checking with hasAnyAccess??

**Comment by brunogaspar** [comment]
Can you elaborate on what you want to achieve here?

**Comment by iboinas** [comment]
On a admin backoffice section, i would like to select a user, and display its current permissions.

Exactly the permissions that this user would be granted on hasAcess(permission), being this permission from a group where he is, or from individual permission...

lets say:
user->groups->permissions
+
user->permissions

for every single permission, if hasAcess, output permission...

All summed up, means i can look at a user, and realise what he has permission to do...

I guess it would be quicker to implement than to bother you, but i guess this is nice feature, and if sentinel still doesn't have it, i want to leave that suggestion...

**Comment by brunogaspar** [comment]
We can probably add this as a feature for the next release.

**Comment by iboinas** [comment]
:+1:

**Comment by brunogaspar** [comment]
This has been added in the new version.

**Comment by rahulbussa** [comment]
Can any tell us solution.I don't find the solution even in #128 .
Please reopen it
