### ISSUE TITLE
Possible to authenticate without password?

### ISSUE THREAD

**Issue by iboinas** [cartalyst/sentinel#108]
Another question :)

Is it possible to authenticate with a user only by its id, for example?

Useful for debugging and/or live testing, as if we were someone else..

Hope I got the message through :)

**Comment by brunogaspar** [comment]
You can use the [findById()](https://cartalyst.com/manual/sentinel/2.0#sentinel-findbyid) to retrieve the user by it's id then use the [login()](https://cartalyst.com/manual/sentinel/2.0#sentinel-login) to authenticate that user.

Pretty much

```php
$user = Sentinel::findById(1);

Sentinel::login($user);
```
