### ISSUE TITLE
not able to login/persist

### ISSUE THREAD

**Issue by lorvent** [cartalyst/sentinel#110]
When i enter correct login details...its not getting logged in

actually its logging in properly but data is not stored into `persistences` table,
i can see cookie in system but no rows in `persistences` table

when i debug, i can see success message saying 'you are successfully loggedin' and below that error message saying 'you must be logged in' means.... its logging user properly but not storing persistences in table.

same code works properly in localhost and another installation works properly in server too...

any help would be appreciated.

thanks

**Comment by brunogaspar** [comment]
Without seeing how you're logging your users, we can't really help.

**Comment by lorvent** [comment]
````php
 public function postLogin()
    {
        // Declare the rules for the form validation
        $rules = array(
            'email'    => 'required|email',
            'password' => 'required|between:3,32',
        );

        // Create a new validator instance from our validation rules
        $validator = Validator::make(Input::all(), $rules);

        // If validation fails, we'll exit the operation now.
        if ($validator->fails()) {
            // Ooops.. something went wrong
            return Redirect::back()->withInput()->withErrors($validator);
        }

        try {
            // Try to log the user in
            Sentinel::authenticate(Input::only('email', 'password'), Input::get('remember-me', 0));

            // Get the page we were before
            $redirect = Session::get('loginRedirect', 'account');

            // Unset the page we were before from the session
            Session::forget('loginRedirect');

            // Redirect to the users page
            //return Redirect::to($redirect)->with('success', Lang::get('auth/message.login.success'));
            return Redirect::route("dashboard")->with('success', Lang::get('auth/message.login.success'));
        } catch (UserNotFoundException $e) {
            $this->messageBag->add('email', Lang::get('auth/message.account_not_found'));
        } catch (UserNotActivatedException $e) {
            $this->messageBag->add('email', Lang::get('auth/message.account_not_activated'));
        } catch (UserSuspendedException $e) {
            $this->messageBag->add('email', Lang::get('auth/message.account_suspended'));
        } catch (UserBannedException $e) {
            $this->messageBag->add('email', Lang::get('auth/message.account_banned'));
        }

        // Ooops.. something went wrong
        return Redirect::back()->withInput()->withErrors($this->messageBag);
    }
````

**Comment by brunogaspar** [comment]
I don't see anything wrong with your code nor i can really reproduce on my end.

> same code works properly in localhost and another installation works properly in server too...

I would try to debug your application then, something must be wrong there, doesn't seem to be a problem with the package.

Try to do a `dd(Sentinel::getUser());` right after the `Sentinel::authenticate()` to start, double check the database, etc..

**Comment by lorvent** [comment]
its returning `null`

If you are interested, i can give you access to ftp or git repo

thanks.

**Comment by brunogaspar** [comment]
> its returning `null`

Since it's returning `null` it means the user never logged in.

I don't know what might be causing it, but a common issue is the storage/* folders permissions not being set properly as mentioned on the [Laravel documentation](http://laravel.com/docs/5.1#configuration) therefore when Laravel tries to write a session, it can't. This mainly applies for the `file` session driver though.

You can also apply an if statement on the `Sentinel::authenticate()` that way you know for sure if the user logged in or not.

---

Also, not related to this issue, but the second argument on both the `authenticate()` and `login()` methods should be a `boolean` and not an `integer`

Something like:

```php
Sentinel::authenticate(Input::only('email', 'password'), (bool) Input::get('remember-me', 0));
```

**Comment by lorvent** [comment]
i tried what you suggested like

````php
try {
            // Try to log the user in
            if($user = Sentinel::authenticate(Input::only('email', 'password'), (bool)Input::get('remember-me', 0)))
            {
                return $user;
            }
            else  return 'error logging in';

            
            // Redirect to the users page
            return Redirect::route("dashboard")->with('success', Lang::get('auth/message.login.success'));
        } catch (UserNotFoundException $e) {
            $this->messageBag->add('email', Lang::get('auth/message.account_not_found'));
        } catch (UserNotActivatedException $e) {
            $this->messageBag->add('email', Lang::get('auth/message.account_not_activated'));
        }
````

its going to else block only

**Comment by brunogaspar** [comment]
I don't have any more ideas, sorry.

Just for the sake of testing, i did a fresh clone of Laravel 5.1, installed Sentinel then created a few users and tried to login, it's working as expected here.

**Comment by lorvent** [comment]
Ok.... i think i may found reason

when i use it in virtual host (custom domain) this problem is coming up...
when i access it with full domain URL.... its working properly

i.e.

i have server at digitalocean, and droplet name is dev.domain.com

when i access with dev.domain.com/laravel ... login working properly

i have custom domain xyz.com

now when i access xyz.com login not working properly

i have setup xyz.com to access dev.domain.com/laravel

so it must be something related to virtualhost

yesterday a friend of mine experienced same in localhost but i thought he has some mis-configuration but it seems the problem lies in virtualhost or virtualhost+sentinel not playing well together.
