### ISSUE TITLE
hasAnyAccess on logged in user only?

### ISSUE THREAD

**Issue by iboinas** [cartalyst/sentinel#112]
Hello again,

I've been implementing Sentinel 2.0, and i've user a lot of times the Sentinel::hasAnyAccess method, via alias/facade..
Thing is, when a user is not logged in, this method throws a BadMethodCallException, instead of sending false.

Means, we have to first check the logged in user, so only after this call the hasAnyAccess, and it seems  to me that this method could return false also for not logged in users, means also would not have access.

Does it make sense?

**Comment by brunogaspar** [comment]
Just check if the user is logged in before calling that method.

Returning false is the incorrect behaviour.
