### ISSUE TITLE
Is it possible to make it work with CI3 ?

### ISSUE THREAD

**Issue by XEngine** [cartalyst/sentinel#120]
I already make it working with Codeigniter 3. Simply composer update was enough but Activation and Reminders not working, since there is no facade of them in Native folder. How can I achive this?

**Comment by brunogaspar** [comment]
You don't need facades, just retrieve the appropriate repository and use it.

Sentinel::getActivationRepositiry()
Sentinel::getReminderRepository()

and so on.
