### ISSUE TITLE
Inherit Sentry to User model class

### ISSUE THREAD

**Issue by khanshakeeb** [cartalyst/sentinel#121]
I have a scenario where I need to make user profile. So I want to create a model class and wanted to make relation with Sentry User class. How I will do that?

**Comment by brunogaspar** [comment]
Sentry? This is not Sentry.

**Comment by brunogaspar** [comment]
But if you want to extend the default User model you can do the following https://github.com/cartalyst/sentinel/wiki/Extending-Sentinel

**Comment by khanshakeeb** [comment]
sorry it was my mistake yes I am taking about sentinel

**Comment by brunogaspar** [comment]
No worries.

Does that link help or you need more information?

**Comment by khanshakeeb** [comment]
For now I don't need any information I will post it if any

Thanks a lot for quick revert

Thanks

Sent from my Windows Phone
________________________________
