### ISSUE TITLE
Sentinel::logout() problem?

### ISSUE THREAD

**Issue by gsmeira** [cartalyst/sentinel#122]
Hello,

I've been exploring the features of Sentinel and I have a problem with **Sentinel::logout()**

In order to create my code, I used the following link documentation:

https://github.com/cartalyst/sentinel/blob/docs/2.0/usage/login.md

When I perform a "simple" logout, everything works correctly:

```php
Sentinel::logout()
```
or
```php
Sentinel::logout(null, true)
```

Both codes work correctly for the logged in user. But when I try to pass a user in the first argument, I have two problems:

* I always lose my session.
* If i don't pass the second argument as `true`, the given user doesn't lose his session

### Examples:

Let's pretend I'm logged in as **userA** and want to destroy the **userB** session.

When I run the code:

```php
$userB = Sentinel::findUserById($id);

Sentinel::logout($userB)
```
I lose my session as **userA** and **userB** doesn't lose its session. I tested for the user having one or more open sessions. **UserB** hasn't lost its session in either case.

But when I run the code
```php
$userB = Sentinel::findUserById($id);

Sentinel::logout($userB, true)
```
I still lose my session as **userA**, but in these conditions all **userB** sessions are destroyed too.

**Comment by suwardany** [comment]
Thanks for reporting @gsmeira .. this should be fixed now, it'll flush all persistences of the passed user if it's not the current.
