### ISSUE TITLE
Sentinel::authenticate() issue

### ISSUE THREAD

**Issue by paolooo** [cartalyst/sentinel#123]
Just got an issue on `Sentinel::authenticate()`. Somehow it returns the user even though $credentials[] `username` is invalid, as long as the password is valid.

users table

ID | email | password | ...
----|---------|--------------|----
1  | admin@localhost.com | 123 | ...

To reproduce this issue. Try the below code. Use `username` instead of `email`. If `email` key is used instead of `username`, then, authentication works properly, but if we'll going to use `username` or any key it will validate the user as long as the password is valid.

```
$auth = Sentinel::authenticate([
    'username' => 'xxxxxx',
    'password' => 123,
]);

dd($auth);  // <-- this will return User 1 ( admin@localhost.com )...
```

This is because `$query->first()` will always return the first user when `email` field is not supplied. Check the code here: https://github.com/cartalyst/sentinel/blob/2.0/src/Users/IlluminateUserRepository.php#L107

This is dangerous especially when using `$request->all()` or `Input:all()`. Check the following code:

```
if ($auth = Sentinel::authenticate($request->all())) {
   // valid user
} else {
  // invalid user
}
```

**Comment by shehi** [comment]
@paolooo : why not create a PR into this official repo?

**Comment by paolooo** [comment]
Thanks @shehi I just create one but it's on 1.0 branch as per requested by the owner. Here #126
