### ISSUE TITLE
[Question][3.0] How big the change will be in architecture?

### ISSUE THREAD

**Issue by shehi** [cartalyst/sentinel#125]
Hi there,

I've read you are working on Sentinel 3. My question is: I want to incorporate it into my open-source solution, the version 2 that is. How big will the changes in version 3 be? I ask this because I don't want to end-up with unupgradable mess down the path.

And, is there any ETA for version 3? Is there any place where I could read about the progress on version 3? Thanks.

**Comment by brunogaspar** [comment]
Most of it is covered here https://github.com/cartalyst/sentinel/issues/82

> And, is there any ETA for version 3? Is there any place where I could read about the progress on version 3? 

We don't give ETAs.
