### ISSUE TITLE
 Is it possible somehow to see all permissions of set of roles?

### ISSUE THREAD

**Issue by berpcor** [cartalyst/sentinel#128]
Hello.
For example, I have $roles = ['role1', 'role2', 'role3']; I need to see all permissions of all roles for admin zone purposes with interference of opposite permissions. How to do that?

**Comment by brunogaspar** [comment]
Don't believe such thing exists on Sentinel.

But you can easily fetch and loop through the roles you want, then call `$role->permissions` and do what you need i guess.

Something like this:

```php
$rolesSlugs = [ 'role1', 'role2', 'role3', 'admin' ];

$roles = Sentinel::getRoleRepository()->createModel()->whereIn('slug', $rolesSlugs)->get();

$permissions = [];

foreach ($roles as $role) {
    $permissions = array_merge($role->permissions, $permissions);
}

var_dump($permissions);
```

This is one way, there are other ways, but it depends on your use case i'll leave it up to you to figure out.

If that's not it, please try to explain better.

**Comment by berpcor** [comment]
In admin zone I have page with all users. I choose one of them and want to see the resulting set of all permissions for this user. Individual permissions of user and all permissions of his roles.
Roles are:
```
{
    "name" : "Moderator",
    "permissions" : {
        "user.create" : false,
        "user.delete" : false,
        "user.view"   : true,
        "user.update" : true
    }
},

{
    "name" : "Administrator",
    "permissions" : {
        "user.create" : true,
        "user.delete" : true,
        "user.view"   : true,
        "user.update" : true
    }
}
```
User has both of them. Also he has his user level permissions.

```
{
    "id" : 2,
    "first_name" : "Jane",
    "last_name" : "Smith",
    "roles" : ["moderator", "administrator"],
    "permissions" : {
        "user.create" : false,
        "user.delete" : true
    }
}
```

I need to get all permissions for user. Something like that:
$user = Sentinel::FindById(1);
$permissions = getResultingPermissionsFor($user);
$permissions = [
    "user.create" : false, 
    "user.delete" : true, 
    "user.view"   : true, 
    "user.update" : true
];

**Comment by brunogaspar** [comment]
That's not currently possible, you'll need to merge the permissions of both users and roles together if you want that kind of workflow.

Check this https://github.com/cartalyst/sentinel/issues/107

**Comment by Oni-zerone** [comment]
Please someone can tell me if something like that could works? 
`{
    "id" : 2,
    "first_name" : "Jane",
    "last_name" : "Smith",
    "roles" : ["moderator", "administrator"],
    "permissions" : {
        "user.view" : false,
        "user.create" : false,
        "user.delete" : false,
        "user.18.view" : true,
    }
}`

where 18 is the id of a single user?

**Comment by rolandalla** [comment]
I managed it with creating a function to my User Model 
```
public function getAllPermissions(){
        $roles = $this->roles;
        $permissions = [];
        foreach ($roles as $role) {
            $permissions = array_merge($role->permissions, $permissions); //Merge all  roles permissions
        }
        $permissions = array_merge($this->permissions, $permissions); //Merge  specific user  permissions

        return $permissions; //Return All permissions
    }
```

After that you can call it example for the  auth user:
`Sentinel::getUser()->getAllPermissions()`

Return:

```
{
  "home.dashboard": true,
  "users.show": true,
  "*": true
}

```
