### ISSUE TITLE
using $user->save() instead of Sentinel::update with password hashing

### ISSUE THREAD

**Issue by lorvent** [cartalyst/sentinel#129]
Hello,
I setup code in a way i find user by id and save user object into $user

then update all values like 
````
$user->email = Input::get('email')
$user->password = Input::get('password')
````
 then finally ````$user->save()```` works just fine.

it used to save hashed passwords with sentry but with sentinel its storing plain passwords :(

**Comment by brunogaspar** [comment]
That's not the proper way to update an user if you want to change their password.

You need to use the [update](https://cartalyst.com/manual/sentinel/2.0#sentinel-update) method instead.
