### ISSUE TITLE
$activation->create( $userArray ) Undefined index: code

### ISSUE THREAD

**Issue by qutwala** [cartalyst/sentinel#130]
Hello,

I'm trying to setup user creation with not completed activation.
There's following code to achieve this:

`$credentials = array(
			'email'    => 'john.doe@example.com',
			'password' => 'password',
		);`
`$user= $sentinel->register($credentials);`
`$activation = $activation->create( $user->getAttributes() );`

Seems that activation is not working properly in this way because it inserts not complete data to DB and later produces this error when trying to access created activation and it's code.
DB entry looks like this:

> {
>     "_id" : ObjectId("55e31f59b0e6df55708b4568"),
>     "updated_at" : ISODate("2015-08-30T15:20:57.537Z"),
>     "created_at" : ISODate("2015-08-30T15:20:57.537Z")
> }

`$activation->getCode()`

> ErrorException in EloquentActivation.php line 70:
> Undefined index: code

However, using `$sentinel->registerAndActivate($credentials)` it works fine:

> {
>     "_id" : ObjectId("55e31dc9b0e6df19708b4569"),
>     "code" : "JjGzz6DirydjfLT4hWLrcWJW8DX9qr0Y",
>     "user_id" : "55e31dc9b0e6df19708b4568",
>     "completed" : true,
>     "updated_at" : ISODate("2015-08-30T15:14:17.594Z"),
>     "created_at" : ISODate("2015-08-30T15:14:17.575Z"),
>     "completed_at" : {
>         "date" : "2015-08-30 15:14:17.000000",
>         "timezone_type" : NumberLong(3),
>         "timezone" : "UTC"
>     }
}

**Comment by brunogaspar** [comment]
What is `$activation` here `$activation = $activation->create( $user->getAttributes() );`

I kinda find it impossible for you to create an activation record by just passing an array instead of a user object as it requires a user object here https://github.com/cartalyst/sentinel/blob/2.0/src/Activations/IlluminateActivationRepository.php#L66

**Comment by qutwala** [comment]
My mistake, sorry, there's more code for clarifying things:

`use Cartalyst\Sentinel\Activations\EloquentActivation AS Activation ;`
`...`
`public function test(Activation $activation) {`
`$activation = $activation->create( $user->getAttributes() );`
`$activation->getCode()`
`}`

Maybe i'm using wrong branch or something. I have installed Sentinel using composer:

> "cartalyst/sentinel": "2.0.*"

And using sentinel in Laravel 5.

**Comment by brunogaspar** [comment]
You're doing it wrong then.

You shouldn't use the model directly, if you use the model directly, you're responsible by generating the activation code yourself.
