### ISSUE TITLE
disable throttling

### ISSUE THREAD

**Issue by lorvent** [cartalyst/sentinel#134]
Hello,
Our testers are testing a sentinel based product,
since many people from same ip trying to access it.... we are reaching throttling exception often.

is there any way we can disable throttling for a while?

thanks.

**Comment by suwardany** [comment]
Just disable the checkpoint here https://github.com/cartalyst/sentinel/blob/2.0/src/config/config.php#L136

**Comment by victorolowe** [comment]
Disabling throttling doesn't work. It's still throwing exceptions...Any help please
I'm using Laravel 5.4

**Comment by halabe15** [comment]
Make sure each time you call your function postLogin delete the table of throttle

**Comment by victorolowe** [comment]
Alright. Thanks. Will try this out

**Comment by hashik** [comment]
you can call a Sentinel default function in llaravel "web.php"
example
`Sentinel::disableCheckpoints();`

**Comment by ssi-anik** [comment]
> you can call a Sentinel default function in llaravel "web.php"
> example
> `Sentinel::disableCheckpoints();`
> 
> or comment the checkpoints in **config->cartalyst.sentinel.php**
> 
> ` 'checkpoints' => [ // 'throttle', // 'activation', ],`

I tried `config()->set('cartalyst.sentinel.checkpoints', ['activation']);` cause I don't want to bypass activation checkpoint.
Still cheerio to @hashik
