### ISSUE TITLE
Laravel 5 crypted email

### ISSUE THREAD

**Issue by LLIu33** [cartalyst/sentinel#135]
When I try authenticate Sentinel always return false.
In user model I use Crypt for column of email. (cipher => 'AES-256-CBC')
```
    public function getEmailAttribute($value)
    { 
        return is_null($value) ? $value : Crypt::decrypt($value);
    }
    public function setEmailAttribute($value)
    {
        try {
           $this->attributes['email'] = Crypt::encrypt($value);
        } catch (DecryptException $e)
        {
           //Add logic
        }
    }
```
`Sentinel::authenticate` use `IlluminateUserRepository::findByCredentials` for find user. 
The implementation of this method is not suitable for the search by encrypted field.
Is there a solution for this situation?

**Comment by brunogaspar** [comment]
You need to create your own user repository perhaps, not sure what your end goal is with this, but either way it's not really supported.
