### ISSUE TITLE
[Feature Request] Integrate into Laravel's Auth system to allow ACL features

### ISSUE THREAD

**Issue by james-daddies** [cartalyst/sentinel#136]
With the addition of Laravel's Authorization features, it would be nice to leverage Policies to have finer control of permissions.

The only way I have been able to get Policies and Sentinel to work together is by manually authenticating with Laravel's Auth along side Sentinel. Policies want to resolve the authenticated user via Auth before it continues to check the policy. That is where an integration point would be beneficial; having the authenticated user be resolved via Sentinel rather than Auth.

**Comment by fgreinus** [comment]
:+1:

**Comment by brunogaspar** [comment]
Sorry, but that's not going to happen.

**Comment by james-daddies** [comment]
Worth a shot. 

I managed to get the Gate class to resolve the user via Sentinel by extending `AuthServiceProvider`. 

Thanks for taking a look.

**Comment by brunogaspar** [comment]
The reason for this is that this sort of thing gets very opinionated, while you might require this, some might not.

Since it's more easier to add features than to remove them it's always recommended to create your own solution to fit your needs and another thing is that Sentinel 3 is even more decoupled from Laravel and we do our best to not change Laravel default behavior, the only thing we're doing on Sentinel 3 is to swap the resolved user on the request class and that's pretty much it.

Since you managed to make it work, just bundle it on a package if you want to share your solution with others.

**Comment by james-daddies** [comment]
That was going to be my suggestion. I do realize that this feature request
won't get a lot of votes, thought maybe shipping with a couple of service
providers the user could choose to include or not.

I have read the requirements for Sentinel 3 and noticed some nice
additions. Looking forward to the release.

**Comment by rigobcastro** [comment]
I always use Policies with Sentinel w/o much work:

``` php
// Config
...

'users' => [
    'model' => 'App\User',
 ],

...
```

``` php
// Model
class User extends EloquentUser ...
```

``` php
// Controller
$user = Sentinel::getUser();
$user->can('update');

// or ...

Gate::forUser($user)->denies('update', $post);
```

I love Sentinel flexibility.

**Comment by bajramemini** [comment]
> I managed to get the Gate class to resolve the user via Sentinel by extending AuthServiceProvider.

@james-daddies  how did you extend it? I am facing the same problem right now, but haven't been able to come up with a solution yet.

Regards

**Comment by james-daddies** [comment]
Here is what I ended up using

```php
class AuthServiceProvider extends AuthProvider
{
    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        $this->registerAuthenticator();

        $this->registerUserResolver();

        $this->registerAccessGate();

        $this->registerRequestRebindHandler();
    }

    /**
     * Register the access gate service with Sentinel resolving the user.
     *
     * @return void
     */
    protected function registerAccessGate()
    {
        $this->app->singleton(GateContract::class, function ($app) {
            return new Gate($app, function () use ($app) { return $this->app['sentinel']->getUser(); });
        });
    }
}
```

**Comment by bajramemini** [comment]
@james-daddies Thank you very much! Going to try that.

**Comment by marsd** [comment]
Hi @james-daddies Where is your AuthServiceProvider located? It seems to be very different from the one that comes with Laravel: https://github.com/laravel/laravel/blob/master/app/Providers/AuthServiceProvider.php

**Comment by james-daddies** [comment]
That is where mine is.


--
James Wagoner
Developer
Daddies Board Shop

**Comment by igorrynkovoy** [comment]
@james-daddies Thanks for your idea. 
@marsd You should extend **\Illuminate\Auth\AuthServiceProvider** Here is how I implemented:

`
<?php

namespace App\Auth;

use Illuminate\Auth\Access\Gate;
use Illuminate\Contracts\Auth\Access\Gate as GateContract;

class AuthServiceProvider extends \Illuminate\Auth\AuthServiceProvider {
    protected function registerAccessGate()
    {
        $this->app->singleton(GateContract::class, function ($app) {
            return new Gate($app, function () use ($app) {
                return $this->app['sentinel']->getUser();
            });
        });
    }
}
`

In **config/app.php** change service provider **Illuminate\Auth\AuthServiceProvider::class** to **App\Auth\AuthServiceProvider::class**

**Comment by benkelukas** [comment]
I had the same problem, after some fiddling, I came with this:

**app\Providers\AuthServiceProvider**

```php
namespace App\Providers;

use Illuminate\Auth\Access\Gate;
use Illuminate\Contracts\Auth\Access\Gate as GateContract;

class AuthServiceProvider extends Illuminate\Foundation\Support\Providers\AuthServiceProvider
{
    /**
     * The policy mappings for the application.
     *
     * @var array
     */
    protected $policies = [
    ];

    /**
     * Register any application authentication / authorization services.
     *
     * @param  \Illuminate\Contracts\Auth\Access\Gate  $gate
     * @return void
     */
    public function boot(GateContract $gate)
    {
        $this->registerPolicies($gate);

        //
    }

    /**
     * overriden register method, called the singleton rebinding in registerAccessGate     
     */
    public function register() {
        $this->registerAccessGate();
    }

    protected function registerAccessGate()
    {
        $this->app->singleton(GateContract::class, function ($app) {
            return new Gate($app, function () use ($app) {
                return $this->app['sentinel']->getUser();
            });
        });
    }
}
```

And it works, thanks @igorrynkovoy and @james-daddies  for pointing me into the right direction

**Comment by unstoppablecarl** [comment]
I propose adding this snipped to the readme.

**Comment by ivansammartino** [comment]
I'm also trying to "merge" native Laravel Auth and Sentinel: but I'm using Laravel 5.5 and something is changed in the AuthServiceProvider since the @benkelukas snippet...
Please, how can I do this?
Thanks

**Comment by vladimir-pitchkurov** [comment]
> I had the same problem, after some fiddling, I came with this:

**Comment by rambo666** [comment]
Using Laravel 5.6, 
My authenticated user is sentinel user. I have not authenticated using Auth facade. 
However, to use policy for sentinel authenticated user you just need to question mark the User model on your Policy Definition. 


    AgencyPolicy.php
    public function update(?User $user, Agencyuser $agencyUser)
    {
        return $user->id === $agencyUser->user_id;
    }

Notice the use of ?User on user model. This will allow any user model that are authenticated into the system whether laravel Auth user or Sentinel User.

**Comment by moiz-conceptlz** [comment]
> ```
> GateContract
> ```

So this method does not work with Laravel 6 - tried is and getting the following error 
```
Symfony\Component\Debug\Exception\FatalThrowableError
Call to undefined method Illuminate\Support\Facades\Gate::after()
```

**Comment by M0einRahmani** [comment]
@moiz-conceptlz 

This code works in Laravel 10

`<?php

namespace App\Providers;

use App\Permission;
use Illuminate\Auth\Access\Gate as AccessGate;
use Illuminate\Contracts\Auth\Access\Gate as GateContract;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Gate;
use Sentinel;

class AuthServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $this->registerPolicies();
    }

    public function register()
    {
        $this->registerAccessGate();
    }

    protected function registerAccessGate()
    {
        $this->app->singleton(GateContract::class, function ($app) {
            return new AccessGate($app, function () {
                return $this->app['sentinel']->getUser();
            });
        });
    }

    public function registerPolicies()
    {
        foreach (Permission::where('active', '1')->get() as $permission) {
            Gate::define($permission->slug, function ($user) use ($permission) {
                if (Sentinel::inRole('SUPER_ADMIN')) {
                    return true;
                }
                if ($user->hasAccess([$permission->slug])) {
                    return true;
                }

                return false;
            });
        }
    }
}
`

**Comment by M0einRahmani** [comment]
@moiz-conceptlz

This code works in Laravel 10

`<?php

namespace App\Providers;

use App\Permission;
use Illuminate\Auth\Access\Gate as AccessGate;
use Illuminate\Contracts\Auth\Access\Gate as GateContract;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Gate;
use Sentinel;

class AuthServiceProvider extends ServiceProvider
{
public function boot()
{
$this->registerPolicies();
}

public function register()
{
    $this->registerAccessGate();
}

protected function registerAccessGate()
{
    $this->app->singleton(GateContract::class, function ($app) {
        return new AccessGate($app, function () {
            return $this->app['sentinel']->getUser();
        });
    });
}

public function registerPolicies()
{
    foreach (Permission::where('active', '1')->get() as $permission) {
        Gate::define($permission->slug, function ($user) use ($permission) {
            if (Sentinel::inRole('SUPER_ADMIN')) {
                return true;
            }
            if ($user->hasAccess([$permission->slug])) {
                return true;
            }

            return false;
        });
    }
}
}`

**Comment by M0einRahmani** [comment]
@moiz-conceptlz

This code works in Laravel 10

`
<?php

namespace App\Providers;

use App\Permission;
use Illuminate\Auth\Access\Gate as AccessGate;
use Illuminate\Contracts\Auth\Access\Gate as GateContract;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Gate;
use Sentinel;

class AuthServiceProvider extends ServiceProvider
{
public function boot()
{
$this->registerPolicies();
}

public function register()
{
$this->registerAccessGate();
}

protected function registerAccessGate()
{
$this->app->singleton(GateContract::class, function ($app) {
return new AccessGate($app, function () {
return $this->app['sentinel']->getUser();
});
});
}

public function registerPolicies()
{
foreach (Permission::where('active', '1')->get() as $permission) {
Gate::define($permission->slug, function ($user) use ($permission) {
if (Sentinel::inRole('SUPER_ADMIN')) {
return true;
}
if ($user->hasAccess([$permission->slug])) {
return true;
}

        return false;
    });
}
}
}

`

**Comment by M0einRahmani** [comment]
@moiz-conceptlz

This code works in Laravel 10

`
namespace App\Providers;

use App\Permission;
use Illuminate\Auth\Access\Gate as AccessGate;
use Illuminate\Contracts\Auth\Access\Gate as GateContract;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Gate;
use Sentinel;

class AuthServiceProvider extends ServiceProvider
{
public function boot()
{
$this->registerPolicies();
}

public function register()
{
$this->registerAccessGate();
}

protected function registerAccessGate()
{
$this->app->singleton(GateContract::class, function ($app) {
return new AccessGate($app, function () {
return $this->app['sentinel']->getUser();
});
});
}

public function registerPolicies()
{
foreach (Permission::where('active', '1')->get() as $permission) {
Gate::define($permission->slug, function ($user) use ($permission) {
if (Sentinel::inRole('SUPER_ADMIN')) {
return true;
}
if ($user->hasAccess([$permission->slug])) {
return true;
}

        return false;
    });
}
}
}`

**Comment by M0einRahmani** [comment]
@moiz-conceptlz

This code works in Laravel 10

```
<?php

namespace App\Providers;

use App\Permission;
use Illuminate\Auth\Access\Gate as AccessGate;
use Illuminate\Contracts\Auth\Access\Gate as GateContract;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Gate;
use Sentinel;

class AuthServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $this->registerPolicies();
    }

    public function register()
    {
        $this->registerAccessGate();
    }

    protected function registerAccessGate()
    {
        $this->app->singleton(GateContract::class, function ($app) {
            return new AccessGate($app, function () {
                return $this->app['sentinel']->getUser();
            });
        });
    }

    public function registerPolicies()
    {
     
    }
}
```

**Comment by M0einRahmani** [comment]
@moiz-conceptlz

This code works in Laravel 10

``` php
<?php

namespace App\Providers;

use App\Permission;
use Illuminate\Auth\Access\Gate as AccessGate;
use Illuminate\Contracts\Auth\Access\Gate as GateContract;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Gate;
use Sentinel;

class AuthServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $this->registerPolicies();
    }

    public function register()
    {
        $this->registerAccessGate();
    }

    protected function registerAccessGate()
    {
        $this->app->singleton(GateContract::class, function ($app) {
            return new AccessGate($app, function () {
                return $this->app['sentinel']->getUser();
            });
        });
    }

    public function registerPolicies()
    {
        // Define gate
    }
}
```
