### ISSUE TITLE
Hidden fields visible.

### ISSUE THREAD

**Issue by hikernl** [cartalyst/sentinel#137]
In the EloquentUser model i have: protected $hidden = ['password']; 

When i do {{ Sentinel::getUser() }} in my view the password field is indeed hidden.
But when i do {{ Sentinel::getUser()->password }} it shows the password !!

Is this expected behavior ?

**Comment by brunogaspar** [comment]
From Laravel documentation

```
Sometimes you may wish to limit the attributes that are included in your model's array or JSON form, such as passwords. To do so, add a hidden property definition to your model
```

So yes, it's the expected behavior, otherwise it would be a bit impossible to verify if the given password is valid when a user is authenticating.

**Comment by hikernl** [comment]
Ok, i found my mistake.

I was sending  
```
$user = Sentinel::getUser(); 
````
to the view, which also send the password (and other) hidden fields to the view.

I had to cast it to an array (or Json) first like:

```
$user = Sentinel::getUser()->toArray();
or
$user = Sentinel::getUser()->toJson();
```
Now it is not sending the hidden fields to the view.

**Comment by brunogaspar** [comment]
Right, it makes sense then, glad you figured it out :)
