### ISSUE TITLE
Laravel 5: Session expires immediately

### ISSUE THREAD

**Issue by kumarbalap** [cartalyst/sentinel#138]
Hi,
I'm using Sentinel with Laravel5. I'm trying to login with "login" function.
```
Sentinel::loginAndRemember($user);
```
I'm able to get the logged in user by 
```
Sentinel::check()
Sentinel::getUser()
```
 immediately after the above login function call, but if I comment the login and check for the existence, its returning null.

Am I missing anything, can somebody please help me on this.

Thanks,
Bala

**Comment by brunogaspar** [comment]
Either your sessions folder doesn't have enough permissions or something else is logging the user out. I can't reproduce it.

I would try with a fresh Laravel installation and see if it works there.

**Comment by kumarbalap** [comment]
Session files and persistences tables are active, no idea what is missing.

Any way thanks for the reply.

**Comment by brunogaspar** [comment]
Have you tried on a fresh Laravel installation?

**Comment by kumarbalap** [comment]
Thanks Bruno, working fine with fresh installation.

**Comment by brunogaspar** [comment]
Glad to hear that, so something on your app is causing the logout.
