### ISSUE TITLE
User with multiple roles and same permission (other values)

### ISSUE THREAD

**Issue by RKAN** [cartalyst/sentinel#140]
Hello,

i have User with 2 Roles (Admin, OtherRole)

Admin has the permission ***can.view.admin:true***
OtherRole has the permission ***can.view.admin:false***

If i do a check with "Sentinel::hasAccess('can.view.admin')" i get false back.
But i want here a true because one of the permissions allow it. How i can accomplish that?

If the User has just the "Admin-Role" i get true back.

Thanks!

**Comment by brunogaspar** [comment]
You'll need to create your own permission logic by creating a class similar to [this](https://github.com/cartalyst/sentinel/blob/2.0/src/Permissions/StandardPermissions.php) and then modify it on the config file https://github.com/cartalyst/sentinel/blob/2.0/src/config/config.php#L98

**Comment by RKAN** [comment]
Thanks! I created a new Permission Handler.

**Comment by brunogaspar** [comment]
:+1:
