### ISSUE TITLE
DB normalization

### ISSUE THREAD

**Issue by vedmant** [cartalyst/sentinel#142]
Hi, I think it may be good idea to merge tables activations, persistences, reminders into one table like user_tokens with type field. Also, personally I need one more feature - change email confirmation, with current structure it will need another table, with user_tokens table it will be just additional type.

**Comment by brunogaspar** [comment]
Hello @vedmant, thanks for the proposal, but we prefer to keep everything separated and considering that Sentinel 3 (not released yet) is way more decoupled now, it would become a bit difficult to use and maintain.

If you really want this, you can pretty much extend all the models and create your own single table.
