### ISSUE TITLE
Question about persistances

### ISSUE THREAD

**Issue by glzwp** [cartalyst/sentinel#143]
In the config.php, it has the following:
'persistences' => [
        'model' => 'Cartalyst\Sentinel\Persistences\EloquentPersistence',
        'single' => false,
    ],

what is the meaning of 'single'=>false? if we set 'single'=>true, what will happen?

**Comment by brunogaspar** [comment]
Single means you will only be able to have a single person logged in at a time per user account.

If you log in then someone else logs in after you, you get logged out.

**Comment by glzwp** [comment]
Ok got it. Thank you.

**Comment by brunogaspar** [comment]
:+1:
