### ISSUE TITLE
Select all users and the roles realted to them

### ISSUE THREAD

**Issue by llioor** [cartalyst/sentinel#144]
There is a good way to select all the users in the system (admin panel users list view) plus to receive the roles for each user.

I tried to do this but it didn't work:
App\User::with(‘roles’)->get();

The only way right now is to loop over all users in the system (1000s) and to select for each of them the roles permissions related to him with: 
$user = Sentinel::findById(<id>);

Thank you very much

**Comment by brunogaspar** [comment]
> I tried to do this but it didn't work:
App\User::with(‘roles’)->get();

Didn't work is very vague.
Is that model you're using `App\User` extending the default Sentinel User model? If not, you'll need to extend it or you'll need to use the Sentinel User model to make that code to work.

Something like `Cartalyst\Sentinel\Laravel\Users\User::with('roles')->get();`

**Comment by llioor** [comment]
use Cartalyst\Sentinel\Users\EloquentUser;

class User extends EloquentUser

**Comment by brunogaspar** [comment]
So it's working now?

**Comment by llioor** [comment]
No my friend, because of it I came to here, for sure I'm missing something.

**Comment by brunogaspar** [comment]
Then you need to let me know what's not working, as i previously said `Didn't work is very vague.`, therefore, is impossible for me to guess what's not working on your end.

On my end it returns all the users and it brings the roles with them:

```json
[
    {
        "id": 1,
        "email": "brunofgaspar1@gmail.com",
        "permissions": [],
        "last_login": "2015-10-06 08:02:52",
        "created_at": "2015-09-23 23:40:44",
        "updated_at": "2015-10-06 08:02:52",
        "roles": [
            {
                "id": 1,
                "slug": "admin",
                "name": "Admin",
                "permissions": {
                    "admin": true
                },
                "created_at": "2015-09-24 00:41:10",
                "updated_at": "2015-09-24 00:41:10",
                "pivot": {
                    "user_id": 1,
                    "role_id": 1,
                    "created_at": "2015-09-24 00:41:16",
                    "updated_at": "2015-09-24 00:41:16"
                }
            }
        ]
    },
    {
        "id": 2,
        "email": "john@doe.com",
        "permissions": [],
        "last_login": null,
        "created_at": "2015-10-06 00:06:31",
        "updated_at": "2015-10-06 00:06:31",
        "roles": []
    }
]
```

**Comment by llioor** [comment]
You write! it is working!
Thanks

**Comment by dgildelaig** [comment]
Is it normal that it also returns the hashed password of each user? Looks very insecure to me

**Comment by brunogaspar** [comment]
We have a PR in place to hide the password, but you can do it that way as well.

**Comment by dgildelaig** [comment]
Sorry, I do not follow. What does the PR stand for?

**Comment by llioor** [comment]
You can do this: 
class User extends Model
{
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = ['password'];
}

**Comment by dgildelaig** [comment]
Thanks, I'll add this line to my model.

**Comment by brunogaspar** [comment]
@dgildelaig PR means Pull Request.

I've merged that PR and will create a tag shortly.

**Comment by awardx** [comment]
> On my end it returns all the users and it brings the roles with them:

> [
>     {
>         "id": 1,
>         "email": "brunofgaspar1@gmail.com",
>         "permissions": [],
>         "last_login": "2015-10-06 08:02:52",
>         "created_at": "2015-09-23 23:40:44",
>         "updated_at": "2015-10-06 08:02:52",
>         "roles": [
>             {
>                 "id": 1,
>                 "slug": "admin",
>                 "name": "Admin",
>                 "permissions": {
>                     "admin": true
>                 },
>                 "created_at": "2015-09-24 00:41:10",
>                 "updated_at": "2015-09-24 00:41:10",
>                 "pivot": {
>                     "user_id": 1,
>                     "role_id": 1,
>                     "created_at": "2015-09-24 00:41:16",
>                     "updated_at": "2015-09-24 00:41:16"
>                 }
>             }
>         ]
>     },
>     {
>         "id": 2,
>         "email": "john@doe.com",
>         "permissions": [],
>         "last_login": null,
>         "created_at": "2015-10-06 00:06:31",
>         "updated_at": "2015-10-06 00:06:31",
>         "roles": []
>     }
> ]
> 

Why it doesn't work for me? I use the same line of code - User::with(‘roles’)->get(); and it returns an array with all the users, but their roles come in different bucket - relations.
