### ISSUE TITLE
Sentinel::authenticate doesn't work.

### ISSUE THREAD

**Issue by berpcor** [cartalyst/sentinel#146]
Everything worked fine. But... One day I started my Vagrant and couldn't login. DB is OK. Data there - too. User exists. My code which was working:

```php
$credentials = $request->only('login', 'password');

        $validator = Validator::make($credentials, [
         ...
        ]
        );

        if($validator->fails())
        {
            return redirect()->route('admin-login-page')
                             ->withErrors($validator)
                             ->withInput();
        }
        if($auth = Sentinel::authenticate($credentials, $request->has('login-remember-me')))
        {
            return redirect()->intended('/admin');
        } else
        {
            dd($credentials); // I get array of credentials, although password and login are correct.
        }

        return redirect()->route('admin-login-page')
                         ->withInput($request->only('name', 'login-remember-me'))
                         ->withErrors([
                             'Auth error',
                         ]);
```

P.S. I executed command `composer update`.

**Comment by brunogaspar** [comment]
If it was working and now it's not, it's most likely something on your end.

Everything is working on our end.

I would check your application sessions folder permission or something.

**Comment by berpcor** [comment]
Do you have any ideas about my problem? I did nothing. Just regular computer restart. Hasher maby?..

**Comment by berpcor** [comment]
Yes, composer update was the reason. As you see in my code, I use 'login' field to authenticate. Default value is 'email' field. I've changed EloquenUser. After update it was set to default state.

**Comment by brunogaspar** [comment]
If a `composer update` resetted your changes, you probably changed the files in the `vendor` directory, which is discouraged and should be made on your own model and the published configuration file.

We have a guide that shows how you can extend the User model [here](https://github.com/cartalyst/sentinel/wiki/Extending-Sentinel).
