### ISSUE TITLE
Adding foreign keys with the migrations?

### ISSUE THREAD

**Issue by eschmid72** [cartalyst/sentinel#149]
You migration file does not set any foreign keys to the tables.

Some benefits of foreign keys are:

- preventing invalid data by the database: e.g. assigning a role to a user that doesn't exist yet
- cascading changing ID's: If you change the ID (primary key) of a dataset, all related foreign keys will be updated
- cascading deleting datasets: if you delete a dataset, all related data will be deleted, too, or their foreign key will be set to null.
- database visualisation tools can show the relationships

If the reason for "not adding foreign keys" is: "Not every database does support foreign keys" - I'm sure it's possible to detect if the database does support them or not.

**Comment by brunogaspar** [comment]
https://github.com/cartalyst/sentinel/issues/40
