### ISSUE TITLE
Cache logged user data

### ISSUE THREAD

**Issue by shadoWalker89** [cartalyst/sentinel#150]
Hi,
On each request, several db sql queries are executed to collect data about user, roles, permissions ...
Why there is no feature for collecting all of that data once (depending on the connected user), store it in php sessions and then pull the needed data from the php session instead of querying the db on each request.

**Comment by brunogaspar** [comment]
@shadoWalker89 Thanks for the suggestion, but we've do decline, it's not in the scope of the project nor it makes much sense to include this type of layer in it.

**Comment by k1ng440** [comment]
+1

```
