### ISSUE TITLE
Hard-coded Model definitions vs Model definitions in configuration file

### ISSUE THREAD

**Issue by shehi** [cartalyst/sentinel#153]
Hi all.

I noticed some weirdness in the package: 

As you all know, in ```cartalyst.sentinel.php``` configuration file, we can easily set models to our custom ones. Custom ones, which of course have to extend the official classes. That's all good.

However, in some areas of the code, I noticed that methods such as ```getUsersModel()```, ```setUsersModel()``` etc, just return hard-coded properties, such as ```static::$usersModel```. E.g.: https://github.com/cartalyst/sentinel/blob/2.0/src/Roles/EloquentRole.php#L121

So question arises: aren't we using models set in configuration file?! What's the point here? Why aren't we fetching the actual used model from config and then return it instead?! Or am I missing something here?

**Comment by brunogaspar** [comment]
Those are set at runtime through the service provider if you are on Laravel.
