### ISSUE TITLE
Extending EloquentUser

### ISSUE THREAD

**Issue by facupedrazzini** [cartalyst/sentinel#156]
Hi I'm trying to extending the EloquentUser following this steps:

https://github.com/cartalyst/sentinel/wiki/Extending-Sentinel

This is my User class

```
<?php

namespace App\Model;

class User extends \Cartalyst\Sentinel\Users\EloquentUser {
    protected $hidden = ['password'];
}
```

but I'm getting this error 
`FatalErrorException in RepositoryTrait.php line 35:
Class '\App\Model\User' not found` when I add the class to the config file.

**Comment by brunogaspar** [comment]
Try to run `composer dump-autoload`, it's an autoloading issue, nothing related to Sentinel.
