### ISSUE TITLE
Two tables for different groups of users.

### ISSUE THREAD

**Issue by berpcor** [cartalyst/sentinel#158]
Hello. How can I use sentinel for two groups of users: administrative users and clients?

**Comment by brunogaspar** [comment]
Sentinel doesn't have groups, it has roles, they might feel the same, but they are different.

Now to your question, you'll need to give more information than that or perhaps use the Laravel forums.

**Comment by berpcor** [comment]
How can I deal with two tables?

**Comment by brunogaspar** [comment]
Not possible by default, nor we really provide support for such setups.

**Comment by rauanmaemirov** [comment]
@berpcor You'll have to extend sentinel models and add custom instance of sentinel for one of your client areas.
So if Sentinel creates a single instance under $app['sentinel'] you can check what SentinelServiceProvider does and add your own instance in let's say $app['admin_sentinel'].

But you'll also have to duplicate all the tables under different names. It's tedious, but doable.
