### ISSUE TITLE
Not all dependencies are installed

### ISSUE THREAD

**Issue by NinoSkopac** [cartalyst/sentinel#160]
Native, 5.6.14, Jessie 8.1

```php
<?php
namespace Fitness;
require_once ($_SERVER['DOCUMENT_ROOT'] . '/bootstrap.php');

// Import the necessary classes
use Cartalyst\Sentinel\Native\Facades\Sentinel;
use Illuminate\Database\Capsule\Manager as Capsule;

// Include the composer autoload file
require $_SERVER['DOCUMENT_ROOT'] . '/assets/sentinel/vendor/autoload.php';

// Setup a new Eloquent Capsule instance
$capsule = new Capsule;

$capsule->addConnection([
    'driver'    => 'mysql',
    'host'      => 'X',
    'database'  => 'X',
    'username'  => 'X',
    'password'  => 'X',
    'charset'   => 'utf8',
    'collation' => 'utf8_unicode_ci',
]);

$capsule->bootEloquent();

// Register a new user
Sentinel::register([
    'email'    => 'test@example.com',
    'password' => 'foobar',
]);
```

Results in:
Fatal error: Class 'Illuminate\Events\Dispatcher' not found in /var/www/fitness/assets/sentinel/src/Native/SentinelBootstrapper.php on line 309

Installation was done by downloading master package from this repo, and running `composer install`. The problem is that you list some requirements(for instance the one in the error message) as "suggested", but that doesn't work in native, non Laravel environment. Moving those dependencies from "suggested" to "required" didn't work cause they're not meeting composer stability criteria or something.

I guess for now all I can do is install those dependencies manually.

EDIT: There was just too much dependencies to manually install, so I decided to jump the ship.

**Comment by brunogaspar** [comment]
That's why they are suggested. They are not required by default, you need to manually require them.

**Comment by NinoSkopac** [comment]
That's not very elegant, to just "suggest" them. It makes it virtually unusable by people who don't use Laravel (I mean, who would actually take the time and go actually all the required dependencies manually). How about including them in the package itself? What's the down side to this, instead of those 3rd party libraries becoming outdated over time (although you can always update them and commit your package).

**Comment by GrahamCampbell** [comment]
The best way would be to use virtual packages and require "an implementation". Laravel doesn't support that though, so this really is the best way.

**Comment by NinoSkopac** [comment]
thug life, then

**Comment by alexweissman** [comment]
I have encountered this same problem for both `illuminate/events` and `symfony/http-foundation`.  I think it should at least be mentioned in the documentation: https://cartalyst.com/manual/sentinel/2.0#native

**Comment by brunogaspar** [comment]
@alexweissman Feel free to add that to the documentation :)

**Comment by Arifi** [comment]
Hi.. me too just can't use it, no idea what should i compose :/
Fatal error: Uncaught Error: Class 'Symfony\Component\HttpFoundation\Request' not found in ....\sentinel\src\Native\SentinelBootstrapper.php:223 Stack trace: #0

**Comment by camtarn** [comment]
If you're not using Laraval, and just want to use Sentinel on its own, you need to:

`composer require symfony/http-foundation illuminate/database illuminate/events`

I'd add this to the documentation but I'm afraid I have no idea how. Hopefully enough people will land on this issue and see this.

**Comment by NinoSkopac** [comment]
@camtarn I've done it for you: https://github.com/cartalyst/sentinel/pull/407

nice to see we're coming full circle more than 2 years after I opened the issue

**Comment by OthmanAlseagh** [comment]
hello when i run composer require symfony/http-foundation illuminate/database illuminate/events

error:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires illuminate/database ^8.52, found illuminate/database[v8.52.0, 8.x-dev] but it conflicts with another require.
  Problem 2
    - Root composer.json requires illuminate/events ^8.52, found illuminate/events[v8.52.0, 8.x-dev] but it conflicts with another require.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
@brunogaspar
