### ISSUE TITLE
how to ban user login?

### ISSUE THREAD

**Issue by LiXunGuan** [cartalyst/sentinel#161]
sentry package has ban method,in sentinel how to ban user login

**Comment by brunogaspar** [comment]
You need to create your own banning checkpoint.

**Comment by LiXunGuan** [comment]
@brunogaspar how to custome checkpoints and use.

**Comment by brunogaspar** [comment]
Create the checkpoint by looking into the existing ones Sentinel already ships with https://github.com/cartalyst/sentinel/tree/2.0/src/Checkpoints (nothing is better than real code)

You have now 2 options to register the checkpoint:

- Either by register through a binding in a service provider or similar like this https://github.com/cartalyst/sentinel/blob/2.0/src/Laravel/SentinelServiceProvider.php#L241-L248 and then add it to the config file https://github.com/cartalyst/sentinel/blob/2.0/src/config/config.php#L134
- Or just call the Sentinel::addCheckpoint which is documented here https://cartalyst.com/manual/sentinel/2.0#functions

You're call.

**Comment by LiXunGuan** [comment]
@brunogaspar thank you very much!

**Comment by shahidbasheer** [comment]
@brunogaspar Thanks it really helped i created a checkpoint to check banned user very easily by using Sentinel::addCheckpoint.

**Comment by lorvent** [comment]
@shahidbasheer can you share your new checkpoints?

thanks

**Comment by juanfelipepipen** [comment]
vcv
