### ISSUE TITLE
Problem with tag 2.0.8?

### ISSUE THREAD

**Issue by juniorb2ss** [cartalyst/sentinel#163]
After composer update for package with tag 2.0.8 `$request->user()` not return user logged informations. Tag 2.0.7 not ocurred this problem.

**Comment by brunogaspar** [comment]
Can't reproduce your issue.

Laravel 5.1.26
Sentinel 2.0.8

Code i used to test:

```php
use Illuminate\Http\Request;

Route::get('testing', function (Request $request) {
    var_dump(app('sentinel')->getUser()->email);
    var_dump($request->user()->email);
});
```

Outputs my email as expected and errors out when not logged, still expected.
