### ISSUE TITLE
Prefixing DB tables

### ISSUE THREAD

**Issue by renarsvilnis** [cartalyst/sentinel#168]
Is it possible to prefix all sentinel tables? Something like a config entry or something.

`cartalyst.sentinel.php`

```php
return [
  /**
   * Will prefix the following sentinel tables:
   *
   * activations => auth_activations
   * persistences => auth_persistences
   * reminders => auth_reminders
   * roles => auth_roles
   * role_users => auth_role_users
   * throttle => auth_throttle
   * users => auth_users
   */
  'prefix': 'auth_',
  ...
]
```

**Comment by brunogaspar** [comment]
This is not configurable nor it will ever be.

You'll need to update the migrations and the models yourself by doing something like [this](https://github.com/cartalyst/sentinel/wiki/Extending-Sentinel) then just change the `$table` property.

**Comment by renarsvilnis** [comment]
Ok, thanks!

**Comment by brunogaspar** [comment]
No problem!
