### ISSUE TITLE
findAllUsersWithAccess

### ISSUE THREAD

**Issue by chriskonnertz** [cartalyst/sentinel#169]
Hello,

what is the Sentinel equivalent to `Sentry::findAllUsersWithAccess(...)` ?

Regards

**Comment by brunogaspar** [comment]
You need to fetch the users you want and filter them.

Since i don't know what kind of environment you have, here's with Eloquent:

```php
$permissions = [ /* add permissions to check here */ ];

$users = app('sentinel')->getUserRepository()->get()->filter(function ($user) use ($permissions) {
    return $user->hasAccess($permissions);
});
```

**Comment by chriskonnertz** [comment]
Thanks! Yep, my environment is Laravel.
