### ISSUE TITLE
Sentinel + Lumen + Event Binding.

### ISSUE THREAD

**Issue by atapatel** [cartalyst/sentinel#172]
Hi there,

Can anyone please help me how can i bind my listners for sentinel events like 'sentinel.registerd' ?

**Comment by deividaspetraitis** [comment]
Why this issue is not closed already?

For event binding responsible is Lumen and you should read Lumen's documentation.
In Laravel it can be achieved by registering EventServiceProvider and in that class describing event name and handler class. See more: https://lumen.laravel.com/docs/5.2/events

**Comment by brunogaspar** [comment]
Ya, I believe this is covered on the Lumen documentation, but I'll keep this open for now, until we have time to fiddle with Lumen.

**Comment by deividaspetraitis** [comment]
If helps please see Laravel implementation.

Service provider: https://gist.github.com/deividaspetraitis/e35167b494c4c9763abf
Listener: https://gist.github.com/deividaspetraitis/f8a109fec99881aed141
