### ISSUE TITLE
check() in RouteServiceProvider

### ISSUE THREAD

**Issue by llioor** [cartalyst/sentinel#173]
I want to check if the user is login and to get the user in the RouteServiceProvider after parent::boot() because I want to set the app locale by the user preference, I will explain.

I'm using this package to manage locales in my app: https://github.com/ARCANEDEV/Localization
This package has the option to setSupportedLocales()
I need to set the locale before route so I need to so it in my RouteServiceProvider:

```
use Sentinel;
...
class RouteServiceProvider extends ServiceProvider {

 public function boot(Router $router) {
	parent::boot($router);
	dd(Sentinel::check());
    }
}
```
The problem is that check returns false every time I called it.
I want to do something like this:

```
class RouteServiceProvider extends ServiceProvider {

 public function boot(Router $router) {
	parent::boot($router);
	$user = Sentinel::getUser();
        Localization::setSupportedLocales($user->locales);
    }
}
```
 Please advice:
1. Why I receive false when the user is logged in?
2. When Sentinel initialize the user first time? I don't see any provider under my app/Providers folder.

Thanks!

**Comment by brunogaspar** [comment]
Doing that kind of stuff in a service provider is not going to work as you're to early in the stack to have total access to that data.

Use a middleware instead.

**Comment by llioor** [comment]
Yes I understand that it is too early.
1. Where is the first time that Sentinel initialize the logged user?
2. If I will make a middleware how do I will know that I this middleware runs after sentinel initialized the logged user?

Thanks!

**Comment by brunogaspar** [comment]
> 1. Where is the first time that Sentinel initialize the logged user?

I think once the session starts?

> 2. If I will make a middleware how do I will know that I this middleware runs after sentinel initialized the logged user?

The middleware will run on the request, so at that time, Sentinel is already booted and you have access to the user object. That's why we use middlewares to check if the user is logged in or not.

**Comment by llioor** [comment]
@brunogaspar sorry I didn't answer u immediately. Thank you!
