### ISSUE TITLE
Remember me doesn't seem to be working?

### ISSUE THREAD

**Issue by clin407** [cartalyst/sentinel#174]
I've been trying to get the remember me state working under Laravel 5.1.26 LTS and it doesn't seem to remember. I use to use the built in authentication system laravel comes with and I assume it works similarly.When I run the code below, I can login successfully and go about my app but 2 hours later (the session length), I get kicked out. 

            $user = Sentinel::authenticate($credentials, $remember); // $remember = 1 when user ticks "remember me checkbox"

Is there a way to verify that the remember me feature is working? The persistence table does insert a new row when I log in which is what I assume it uses to verify my credentials on next visit. Sessions are stored in files, the cartalyst config file is pretty much left default

**Comment by suwardany** [comment]
@clin407 you must pass a bool to the method, make sure you cast it before passing it to the method.

**Comment by suwardany** [comment]
@clin407 you can verify it works by ensuring a cookie with the key `cartalyst_sentinel` has been set.

**Comment by clin407** [comment]
Thanks, that'll teach me to read properly. I see it working now (or verified the cookie exists since it didn't place one before)

**Comment by rxng** [comment]
I have the same problem and cannot seem to persist a login using remember me, but not sure how to ensure the cookie with the key has been set @suwardany ?

In the config file, there is this
'cookie' => 'cartalyst_sentinel'

Anyone able to provide wisdom on this matter? Many thanks
