### ISSUE TITLE
Convert Eloquent Models into Traits

### ISSUE THREAD

**Issue by hackel** [cartalyst/sentinel#175]
Is there any reason to implement the Eloquent model functionality needed as a class instead of a trait?  Hard-coding the dependence to Illuminate\Database\Eloquent\Model is limiting.  In my particular case, it is because I am using MongoDB and need to extend my models from Jenssegers\Mongodb\Model instead of Eloquent.  (I've made the same suggestion about switching to traits to him.)  I also have a BaseModel class that all my models extend, and a Sentinel-based User model wouldn't receive this added functionality.

The same is true of the repositories.  I have my own BaseRepository class I use where I've added quite a bit of functionality.  (Yes, I could also turn mine into a trait, but that wouldn't fit as well semantically.)

If you pulled the code from Cartalyst\Sentinel\Users\EloquentUser into a trait, then you could still include an empty EloquentUser class that uses that trait, so that it remains fully backward-compatible.  One small issue is that a class can't override properties set on a trait, so developers using the trait would have to set those themselves in their own classes.

If I am missing any other downside here, please let me know!

**Comment by brunogaspar** [comment]
Thanks for the suggestion but we have to decline it as we don't feel that traits would do any good here.

You're more than welcome to apply on your projects if you see fit.
