### ISSUE TITLE
[L5] Sentinel::authenticate(...)

### ISSUE THREAD

**Issue by AnonymChaos** [cartalyst/sentinel#176]
Call to undefined method Cartalyst\Sentinel\Checkpoints\ThrottleCheckpoint::auth()

Error log in attach. I dont know what i did wrong, or if it is an issue.

[error.zip](https://github.com/cartalyst/sentinel/files/73112/error.zip)

**Comment by brunogaspar** [comment]
Without seeing any code is quite difficult to help.

> Error log in attach. I dont know what i did wrong, or if it is an issue.

Sorry but if you want to show an error log, either paste it here using markdown or use pastebin or even an alternative to that. Downloading files from unknown sources are no to me.

**Comment by AnonymChaos** [comment]
http://pastebin.com/HZKegSJQ

If this doesnt hell i will post my code

**Comment by brunogaspar** [comment]
It's better to paste the code so we can see if it's a user error or a package error.

**Comment by AnonymChaos** [comment]
```php
public function postLogin()
    {
        try {
            $input = Input::all();

            $validator = Validator::make($input, config('config.auth.login.rules'));
            $validator->setAttributeNames(config('config.auth.login.names'));

            if ($validator->fails()) {
                return Redirect::back()
                    ->withInput()
                    ->withErrors($validator);
            }

            $remember = (bool)Input::get('remember', false);

            if (Sentinel::authenticate(Input::all(), $remember)) {
                return Redirect::intended('/');
            }

            $errors = 'Überprüfe Email und/oder Passwort.';
        } catch (NotActivatedException $e) {
            $errors = 'Ihr Benutzer wurde deaktiviert!';

        } catch (ThrottlingException $e) {
            $delay = $e->getDelay();

            $errors = "Ihr Benutzer ist für {$delay} Sekunde(n) gesperrt.";
        }

        return Redirect::back()
            ->withInput()
            ->withErrors($errors);
    }
```

**Comment by brunogaspar** [comment]
I don't see anything wrong with your code at first glance nor it's something i can reproduce on my end.

What's the version of Laravel and Sentinel you're using?

Have you done any change on the Sentinel class? As it seems you had by looking into the stack trace you provided.

[Line 303](https://github.com/cartalyst/sentinel/blob/2.0/src/Sentinel.php#L303) we use `login` but on your end you have `auth`.

**Comment by AnonymChaos** [comment]
I changed nothing in vendor. 

I post my composer file.

http://pastebin.com/5hRv2BSe

**Comment by AnonymChaos** [comment]
I know my mistake. My ide renamed this var while i was renaming an folder called login to auth.
