### ISSUE TITLE
how to use $guarded

### ISSUE THREAD

**Issue by lorvent** [cartalyst/sentinel#180]
Hello,

When i am trying to save custom data with Sentinel::register(), its not accepting as EloquentUser.php has
````
protected $fillable = [
        'email',
        'password',
        'last_name',
        'first_name',
        'permissions',
    ];
````

but i have form with 100+ fields ( :cry: ) and fields may be added anytime so i want to use $guarded in my User model instead of $fillable.

is there any worked around?

Thanks.

**Comment by brunogaspar** [comment]
You need to extend the user model.

https://github.com/cartalyst/sentinel/wiki/Extending-Sentinel

**Comment by lorvent** [comment]
Thanks for the quick response.

I already did that.

my user model looks like this

````php
class User extends EloquentUser
{
    protected $guarded = ['id'];
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';
    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = array('password', 'remember_token');
    protected $dates = ['deleted_at'];

    /**
     * To allow soft deletes
     */
    use SoftDeletes;



}
````

yet its not saving custom.

using laravel 5.1 and sentinel 2.0.*

**Comment by brunogaspar** [comment]
And are you certain that Sentinel is using your model?
Do a `dd(app('sentinel')->getUserRepository()->getModel());` and see what it returns, if it's not returning your user model, then you're not setting the model correctly for Sentinel to use.

**Comment by lorvent** [comment]
Hi,
Thanks for the response.

````"App\User"```` this is what i got, so apparently its using my User model only.

**Comment by brunogaspar** [comment]
I believe you need to set the `$fillable = [];` on your custom model otherwise it will use what's defined on the default user model.

If that's still doesn't fix your issue, i would try the Laravel forums.

**Comment by lorvent** [comment]
lol, that fixed the issue.

they always tell us to use either $fillable or $guarded but looks like using both working in this case.

I am having this trouble for 3+ months on numerous projects and your tip helps me all the time now.

Thank you so much :100:

**Comment by brunogaspar** [comment]
No problem.

I personally recommend `$fillable` over `$guarded` as with the `$fillable` you are 100% certain that only the fields you have there will be the ones to be passed to your query, but that's just me.
