### ISSUE TITLE
MigrationCartalystSentinel not found when rollback

### ISSUE THREAD

**Issue by wazirsoft** [cartalyst/sentinel#183]
I am having the same issue even with the latest repository 

when I try to rollback the Sentinel migration I get this error

```{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'MigrationCartalystSentinel' not found","file":"\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Migrations\/Migrator.php","line":301}}%   ```

**Comment by brunogaspar** [comment]
Try to run `composer dump-autoload` and it should work.

**Comment by wazirsoft** [comment]
I am using it with laravel 4.2 - did ```composer dump-autoload``` and again tried to rollback the migration but same problem

I removed the database and ran
```php artisan migrate --package=cartalyst/sentinel```
After that
```composer dump-autoload```
then 
```php artisan migrate:rollback```


but getting the same problem
```
PHP Fatal error:  Class 'MigrationCartalystSentinel' not found in /vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php on line 301
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'MigrationCartalystSentinel' not found","file":"\/Applications\/MAMP\/htdocs\/instasite\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Migrations\/Migrator.php","line":301}}%
```

**Comment by brunogaspar** [comment]
I can't reproduce.

http://d.pr/i/1j1Wu
