### ISSUE TITLE
Soft delete user delete records from role_users table.

### ISSUE THREAD

**Issue by stojankukrika** [cartalyst/sentinel#186]
Hi there :)
Soft delete user, delete records from role_users table also. Is that any way to we do not loose that data from role_users table? I ask it because if some user delete some customer or user it's can't be restore data because we didn't restore that info when we loose it.

**Comment by brunogaspar** [comment]
We don't have soft deletes by default but you can add these if you want.

Just [extend the models](https://github.com/cartalyst/sentinel/wiki/Extending-Sentinel) and it should work fine.

**Comment by stojankukrika** [comment]
I have user model, what else I need to do to that work?

<?php

namespace App\Models;

use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Cartalyst\Sentinel\Users\EloquentUser;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends EloquentUser implements AuthenticatableContract,
    AuthorizableContract,
    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;

    use SoftDeletes;

    protected $dates = ['deleted_at'];
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';


    protected $guarded = array('id');

    protected $hidden = ['password'];

**Comment by brunogaspar** [comment]
I guess that a small change on the main `EloquentUser` needs to happen in order to detect if the model is being soft deleted or not.

Without testing (not sure if the following really works) replacing [the following](https://github.com/cartalyst/sentinel/blob/2.0/src/Users/EloquentUser.php#L400-L411) with:

```php
public function delete()
{
   if ($this->exists && ! method_exists($this, 'getDeletedAtColumn')) {
       $this->activations()->delete();
       $this->persistences()->delete();
       $this->reminders()->delete();
       $this->roles()->detach();
       $this->throttle()->delete();
   }

   parent::delete();
}
```

**Comment by brunogaspar** [comment]
Going to reopen so i don't forget to push the changes and tag.
