### ISSUE TITLE
Boilerplate for Auth methods on Laravel

### ISSUE THREAD

**Issue by anarcist69** [cartalyst/sentinel#187]
Would be nice to have some boilerplate that be published by using the `vendor:publish` option of artisan in Laravel, just to make deploying of a new application a little faster.

Examples:

+ Middleware
+ Auth Controller w/ methods for registration and authentication
+ Possibly some views

**Comment by brunogaspar** [comment]
We have a kickstart app (available to Cartalyst subscribers) that serves that purpose, no need to polute a framework agnostic package with Laravel stuff.
