### ISSUE TITLE
Sentinel not detecting the user as logged in

### ISSUE THREAD

**Issue by zakiaziz** [cartalyst/sentinel#189]
Hi, I have a stackoverflow thread here: http://stackoverflow.com/questions/35026744/laravel-cartalyst-sentinel-authentication-not-detecting-the-user-as-logged-in and someone there suggested I open up an issue here. I'll copy the content of the stackoverflow thread here:

-----------
I'm on Laravel 5.1 using [Cartalyst's Sentinel][1] as my authentication system. I'm using angular on my front-end.

I have a form at `domain.com/login` that sends a POST request to `api.domain.com/login`. If the user has entered correct credentials `api.domain.com/login` returns `{'success': true}` which my front-end looks at and eventually forwards to `domain.com/dashboard`

This is where the problem arises. The relevant portion of my dashboard controller:
```
    if( Sentinel::check() ) {
        return view('dashboard');            
	} else {
        return redirect()->route('login');
    }
```
is not detecting the user as logged in. And keeps sending me back to `domain.com/login`

I suspect this is happening because the logging in part is happening at `api.domain.com` and we're checking to see if the user is logged in at `domain.com` and the browser isn't sending the relevant sentinel cookies. The [Sentinel docs][1] doesn't mention anything about this.

If my suspicions are correct how can I allow Sentinel authenticate a user for both `api.domain.com` and `domain.com`? If my suspicions aren't correct, what is happening here?

-----------
After a suggestion in the comment I've tried this: in `config/session.php` I've changed `'domain' => null` to `'domain' => '.domain.com'` but still no luck

  [1]: https://cartalyst.com/manual/sentinel/2.0

**Comment by suwardany** [comment]
Hello @zakiaziz 

You would have to update your session's domain config value to `.{yourdomain}.{tld}` .. ie `.example.com` in order to work for subdomains.

**Comment by zakiaziz** [comment]
@suwardany : I've made a ninja edit edit in my OP. I have tried that and I still get the same issue

**Comment by suwardany** [comment]
What code are you using to authenticate the user?

**Comment by zakiaziz** [comment]
Here is the relevant controller code:
```
    public function processLogin(AuthRequest $request) 
    {   
        //validation
        $input = $request->all();
        $rules = [
            'email'            => 'required|email',
            'password'         => 'required|min:6',
        ];
        $validator = Validator::make($input, $rules);
        
        if ($validator->fails())
        {   
            $response   = ['error' => $validator->errors()];
            $httpStatus = 400;

            return response()->json($response, $httpStatus);
        }

        //cannot find user
        if(!$user = Sentinel::findByCredentials($input) ) {
            $response   = ['error' => 'User not found.'];
            $httpStatus = 424;

            return response()->json($response, $httpStatus);
        }


        //process login
        if ($sentinel = Sentinel::login($user, true))
        {
            $response   = [ 'user' => ['id' => $user->id, 'email' => $user->email] ];
            $httpStatus = 200;
        }
        else
        {
            $response   = ['error' => $user];
            $httpStatus = 401;
        }

        return response()->json($response, $httpStatus);
    }
```

**Comment by zakiaziz** [comment]
@suwardany POST-ing to `domain.com/login` (instead of `api.domain.com/login`) allows Sentinel to detect the user as logged in and allows the user to access `domain.com/dashboard` so I'm inclined to believe there isn't anything wrong with the controller code.
