### ISSUE TITLE
Stateless support for Lumen 5.2

### ISSUE THREAD

**Issue by edgji** [cartalyst/sentinel#192]
This may be out of scope for the sentinel project but I had a question regarding building in support for Lumen 5.2+. Support for cookies and sessions has been dropped in the latest version of Lumen which seems to be an integral part in the sentinel persistence mechanism required by the Sentinel class.

The way I am currently integrating Sentinel is through a custom "stateless" persistence repository that implements the PersistenceRepositoryInterface and using a custom service provider to resolve `sentinel.persistence`. See gist [here](https://gist.github.com/edgji/ce43d0552705ec1401b5)

Would allowing a null $persistences parameter in the Sentinel class be feasible? Along with a setStateless() method to control a stateless bool property that can be checked before any persistences method is called, this could help make Sentinel easier to use with Lumen.

**Comment by brunogaspar** [comment]
I think it will be a better idea to have these changes as a separate package like how it was talked here https://github.com/cartalyst/sentinel/issues/70, this way will be inline with what we want to do for Sentinel 3 already.

Will keep this open but if you feel comfortable with PR's i can create the repository with the necessary files and you should be able to then submit the PR with the service provider and such for it work with Lumen.

/cc @suwardany

**Comment by edgji** [comment]
I can do the PR if you set up the repository/package for Lumen support.

**Comment by brunogaspar** [comment]
@edgji I've created the repo with some basic files, if you have time, you can submit a PR :)

**Comment by deividaspetraitis** [comment]
Hey. Any updates according this, for support with Lumen?

**Comment by brunogaspar** [comment]
Going to close this.

If there's still some interest in having this to work on Lumen, please do so [here](https://github.com/cartalyst/sentinel-lumen).
