### ISSUE TITLE
Trying example in document and result error

### ISSUE THREAD

**Issue by zhiephie** [cartalyst/sentinel#198]
I'm try result error
```
$user = Sentinel::findById(1);
$activation = Activation::create($user); //must be of the type array, object given
```
not error this code
```
using credentials, but in table activations new row with user_id 0
$activation = Activation::create($credentials);
```

**Comment by suwardany** [comment]
Make sure you're using the `Activation` facade not model.

**Comment by zhiephie** [comment]
This what you mean?

use Cartalyst\Sentinel\Activations\EloquentActivation as Activation;

**Comment by suwardany** [comment]
`use Cartalyst\Sentinel\Laravel\Facades\Activation;`

**Comment by zhiephie** [comment]
he sorry @suwardany without in laravel, i'm try facede and result A facade root has not been set.

**Comment by zhiephie** [comment]
oh oke Thanks @suwardany Facade native :D
