### ISSUE TITLE
Argument 1 passed

### ISSUE THREAD

**Issue by zhiephie** [cartalyst/sentinel#199]
I'm using slim 3

`` Argument 1 passed to Cartalyst\Sentinel\Reminders\IlluminateReminderRepository::__construct() must be an instance of Cartalyst\Sentinel\Users\UserRepositoryInterface, none given``

this DI 
```
// Generate Reminder Code
$container['reminder'] = function ($c) {
	return new \Cartalyst\Sentinel\Reminders\IlluminateReminderRepository;
};
```

**Comment by brunogaspar** [comment]
The error is expected, you are not passing the user repository as we do [here](https://github.com/cartalyst/sentinel/blob/2.0/src/Laravel/SentinelServiceProvider.php#L324).
