### ISSUE TITLE
Suggest a way to extend Sentinel user model 

### ISSUE THREAD

**Issue by khoatran** [cartalyst/sentinel#200]
Hi Sentinel team,

I am trying to find the way to make Sentinel work with MongoDB using my own User model. I found your article: https://github.com/cartalyst/sentinel/wiki/Extending-Sentinel
However, when checking through the Sentinel code - I see that EloquentUser is inherited from Illuminate\Database\Eloquent\Model. I think it's not a good idea as it's binding the the implementation of the User model to specific implementation of MySQL.  

I tried with 2 implementation wrappers of:  https://github.com/jenssegers/laravel-mongodb and https://github.com/leroy-merlin-br/mongolid-laravel - but failed. Let me explain the main reason below:

Both of them do the extending of Illuminate\Database\Eloquent\Model with their own implementation.  Let's call their own implementation of the extended Model is: CustomModel. However, we have the problem of the inheritance tree with your implementation. I cannot create a new CustomUserModel which extends both from your EloquentUser model and the CustomModel.

What I would like to suggest is: please make your EloquentUser to be an interface. Then, do a specific implementation based on Illuminate\Database\Eloquent\Model as the default. With this way, I can easily make a new User model class which implementing your EloquentUser interface, but still can be extended from other Model class (which do the real implementation for the real storage).

Best regards,

**Comment by suwardany** [comment]
Hello @khoatran 

The model does indeed implement the [`UserInterface`](https://github.com/cartalyst/sentinel/blob/2.0/src/Users/UserInterface.php), just implement that interface  on your class and you should be good to go.

**Comment by khoatran** [comment]
Thanks Suwardany. I have just read through the current implementation of Sentinel again. I see that your implementation is exactly as what I mentioned. Just read too fast before :). Let me try by implementing the UserInterface and replace the model to see whether it works. Will keep you posted. Will contribute/share my MongoDB implementation when I finished.

I love this library. You've done great job. Thanks again.
