### ISSUE TITLE
Call to undefined function Illuminate\Support\random_bytes() 

### ISSUE THREAD

**Issue by rahulshawsrm** [cartalyst/sentinel#201]
<br />
<b>Fatal error</b>:  Call to undefined function Illuminate\Support\random_bytes() in 
<b>G:\xampp\htdocs\makemytripbackend\api\vendor\illuminate\support\Str.php</b> on line 
<b>233</b>
<br />

**Comment by brunogaspar** [comment]
You probably need to enable Open SSL on your end, but in all case, it's something you need to bring on Laravel side.
