### ISSUE TITLE
Cannot override Throttle model because of the method secondsToFree

### ISSUE THREAD

**Issue by khoatran** [cartalyst/sentinel#202]
Hi Sentinel team,

I am developing an application which using your library, but extend the model to use MongoDB. I have followed all of the guidelines. Basically, I have override successfully all models related to User, Role, Activation, Persistence. However, I am having the problem with Throttle model. 

After overriding the Throttle model by setting in: config/catalyst.sentinel.php for below lines:

```php
'throttling' => [
    'model' => 'LaunchCMS\Models\User\Throttle',  //this is my custom Throttle model using MongoDB
   ...
]
```

My LaunchCMS\Models\User\Throttle cannot be extended from Cartalyst\Sentinel\Throttling\EloquentThrottle as it needs to be implemented with another custom Eloquent model for MongoDB. So, when the Throttle checkpoint is run - it will call to the method secondsToFree in Cartalyst\Sentinel\Throttling\IlluminateThrottleRepository

```php
    /**
     * Returns the seconds to free based on the given throttle and
     * the presented delay in seconds, by comparing it to now.
     *
     * @param  \Cartalyst\Sentinel\Throttling\EloquentThrottle  $throttle
     * @param  int  $interval
     * @return int
     */
    protected function secondsToFree(EloquentThrottle $throttle, $interval)
    {
        return $throttle->created_at->addSeconds($interval)->diffInSeconds();
    }
```

It will throw the exception: Argument 1 passed to `Cartalyst\Sentinel\Throttling\IlluminateThrottleRepository::secondsToFree()` must be an instance of `Cartalyst\Sentinel\Throttling\EloquentThrottle`, instance of `LaunchCMS\Models\User\Throttle` given.

As my model is not on the same inheritance tree of `EloquentThrottle`, so I have this casting exception issue.

I would suggest that you should not declare the `EloquentThrottle $throttle` here - as it doesn't necessary and prevent the developers to extend the Throttle model. 

I am using the sentinel version 2.0.9
Thanks,

**Comment by brunogaspar** [comment]
Changing the method signature is a breaking change if someone is overriding the repository, but i see the isse.

We'll have to think about it.

Thanks for the report.

**Comment by brunogaspar** [comment]
Considering that we can't change the method signature on the current version, as doing so goes against semver and can likely break someones application.

What i can recommend is to extend both the model and repository here.

This has been re worked for v3.
