### ISSUE TITLE
Class 'Activation' not found when using without Laravel

### ISSUE THREAD

**Issue by kevin-j-morse** [cartalyst/sentinel#203]
I'm trying to get Sentinel working without Laravel and can't seem to be able to use any of the Activation or Reminder functions. 

I am importing the following classes

`use Cartalyst\Sentinel\Native\Facades\Sentinel;`
`use Illuminate\Database\Capsule\Manager as Capsule;`

and have also tried to import various classes in the `sentinel\src\Activations` directory with no luck getting anything to work.

In the Laravel installations instructions there is an explanation for adding Activation, Reminder, and Sentinel to the $aliases array but I can't figure out how to do this natively.

**Comment by brunogaspar** [comment]
You most likely need to fetch the activation repository through your Sentinel instance.

```php
$activation = $sentinel->getActivationRepository();
```

**Comment by odahcam** [comment]
I solved my problem with this: 

```php
$eloquent = $this->container->get('db'); // boots eloquent

$user = Sentinel::findById($request->getParam('id'));

$Activation = Sentinel::getActivationRepository();
$activation = $Activation->create($user);

if ($Activation->complete($user, $activation->code))
{
    // Activation was successfull
}
else
{
    // Activation not found or not completed.
}
```
