### ISSUE TITLE
Set custom attributes [table and column names] 

### ISSUE THREAD

**Issue by Artessan** [cartalyst/sentinel#205]
Hey, i'm working on a espanish sistem and all the tables are in spanish the previous developer try to traslate the vendor folder and change all the attributes, the [user create, authenticate, activate ] methods work correctly, all the cycle looks like works, the persistences code create on db and on session, 

The problem is that the [ getUser()  check() ] doesn't work after refresh, but the session code still is there.

**Comment by brunogaspar** [comment]
You'll need to provide way more information than `doesn't work after refresh` as it's not helpful at all.

We need version of Sentinel, Laravel, how to reproduce error, etc..

**Comment by Artessan** [comment]
sure, L5.1.31  S2.0.9  and more that one error is a question,  the previous developer rewrite on spanish all the methods of the package 
and now i can register and user and i can do login if I do dd(Sentinel::check()) on my controller works but after login on the return view i try to chek is the user is logged for change the nav and Sentinel::check or guest or getUser dont work

if I check my session the cartalys code is there and if a try do logout the session doesn't deleted.

[cartalyst.zip](https://github.com/cartalyst/sentinel/files/163378/cartalyst.zip)  package

[migrations.zip](https://github.com/cartalyst/sentinel/files/163382/migrations.zip) custom migrations

**Comment by mmic-bjohnson** [comment]
Is it possible that this is simply a case of extending the wrong controller?

This is a very common mistake. If the controller in question extends the default Laravel controller, the methods that are necessary to determine whether or not the user is logged-in in the context will return falsey results, even when the user is, in fact, logged-in.

Ensure that your controller extends `Platform\Foundation\Controllers\Controller` and see if the problem still occurs.

**Comment by Artessan** [comment]
yeah, the controller is good, the problem is not there because i can check and get the actual user on the controller on the login method , but when i do Sentinel::check() on the view that the login method  return doesn't works.

**Comment by mmic-bjohnson** [comment]
And what happens if you access the `$currentUser` variable in your view? Is it empty or not? It should have several properties, such as `$currentUser->first_name` and `$currentUser->last_name`.

If you are extending the wrong controller, `$currentUser` will not be set, because it's set in the constructor of the above-mentioned controller, and it would explain the behavior you describe (and you would still be able to acquire the current user in the controller).

**Comment by Artessan** [comment]
the $currentUser is not set, but this is on Laravel and the current user is not set on anywhere

**Comment by mmic-bjohnson** [comment]
Oh, okay, I had assumed you to be using Cartalyst Platform; my bad! In that case, surely one of the Cartalyst developers will be able to help you out soon enough.

**Comment by mmic-bjohnson** [comment]
One other thought: this sounds a lot like https://github.com/cartalyst/sentinel/issues/194 . Any chance that your issue is the same?

**Comment by Artessan** [comment]
Not that is for laravel 5.2 on 5.1 i don't need declare web middleware. but thanks for try to help

**Comment by brunogaspar** [comment]
I'm not being able to reproduce this.

I can login and on the next request the session is still set, so something on your application is not working properly.

Try to set a dummy session like `session(['foo' => 'bar']);` and then on the next request try to fetch that value using `session('foo');`.

Going to close as i'm not seeing this being an issue on Sentinel side, but something on your application.
