### ISSUE TITLE
link more than one company id to user_roles entry

### ISSUE THREAD

**Issue by TanjaEl** [cartalyst/sentinel#209]
In my system the combination of company & user_role will determain what they see from a company. They can have a diffenent &/or same role with multiple companies. This is hard to link because role_users table has a double key. 

What is the best way to do this?

**Comment by TanjaEl** [comment]
I guess I should look for a different ACL right?

**Comment by brunogaspar** [comment]
@TanjaEl If i understood you correctly, you're after multi tenancy and since Sentinel doesn't offer this at the moment, you'll need to make this type of implementation on your own.

**Comment by TanjaEl** [comment]
Would be nice if you guys could add this, can't think I'm the only dev who needs it.

**Comment by brunogaspar** [comment]
We'll release this as an addon, but it'll only be available on Sentinel 3 and we don't have any ETA.
