### ISSUE TITLE
Composer install automatically removes cartalyst/sentinel

### ISSUE THREAD

**Issue by teddywest32** [cartalyst/sentinel#210]
I have already installed cartalyst/sentinel v 2.0.* in my project and when i try to reuse the code and have already added 
<code>'Cartalyst\Sentinel\Laravel\SentinelServiceProvider',</code>
in providers array and 
<code>
 'Activation' => 'Cartalyst\Sentinel\Laravel\Facades\Activation',
'Reminder'   => 'Cartalyst\Sentinel\Laravel\Facades\Reminder',
 'Sentinel'   => 'Cartalyst\Sentinel\Laravel\Facades\Sentinel',
</code>
in class aliases. But when i do <code>composer install</code> i get this error:
Class 'Cartalyst\Sentinel\Laravel\SentinelServiceProvider' not found
https://gist.github.com/teddywest32/910080dc79f4c267ac07

and when i try <code>composer update</code> by removing sentinel from providers and class aliases array it installs sentinel.
https://gist.github.com/teddywest32/2baa7eb32d68f41aca6e

also when i do <code>composer install</code> after <code>composer update</code> it again removes sentinel from vendor.

<code>
paladin@my-PC:~//Desktop/my-site$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
  - Removing cartalyst/sentinel (v2.0.9)
  - Removing cartalyst/support (v1.1.2)
  - Removing laravelcollective/html (v5.2.4)
  - Removing guzzlehttp/promises (1.1.0)
</code>

Could i know what is the mistake that i am doing.

**Comment by brunogaspar** [comment]
Seems to be an issue with your environment or composer itself since I can't reproduce this.

I would try to update composer to the latest version and try again, if that doesn't fix the issue, open a ticket on composer itself as there's not much we can do here.
