### ISSUE TITLE
Handle session lifetime in Native?

### ISSUE THREAD

**Issue by dgildelaig** [cartalyst/sentinel#211]
I have seen comments mentioning to modify the config.php file for Laravel, adding lines such as 
   'lifetime' => 120,
   'expire_on_close' => false,
in the array structure.

I am passing a config file to the Bootstrapper and added those paramenters, however, I don't see the Sentinel behaviour in Native to throw users away.

Is there an example on how to set up the lifetime for Native projects?

**Comment by dgildelaig** [comment]
Surely there is an example around for Native projects to show how to handle alive sessions and to redirect users to login if the session is expired.
Any links?
Thanks

**Comment by brunogaspar** [comment]
Don't believe there's any good way to handle this without extending the session handler at the moment.
