### ISSUE TITLE
FatalErrorException in RepositoryTrait.php line 35: on Laravel 5.1

### ISSUE THREAD

**Issue by Artessan** [cartalyst/sentinel#216]
Hey, I'm using the package for laravel and  I extends the models usign custom namespace now i have this issue the time in time

FatalErrorException in RepositoryTrait.php line 35:
Class '\Rapitiendas\Users\Auth\Reminder' not found

when i have this error i refresh and all works normally.

Thanks for the help.

**Comment by brunogaspar** [comment]
This seems to be an issue on your application.

But provide more details, like what model(s) you're extending and how/when the error occurs with a code sample.

**Comment by Artessan** [comment]
this is mi reminder model 

`<?php

namespace Rapitiendas\Users;

use Cartalyst\Sentinel\Reminders\EloquentReminder;

class Reminder extends EloquentReminder
{
    /**
     * {@inheritDoc}
     */
    protected $table = 'recordatorios';

    /**
     * {@inheritDoc}
     */
    protected $fillable = [
        'Codigo',
        'realizado',
        'fecha_realizado',
    ];

    /**
     * Set mutator for the "completed" attribute.
     *
     * @param  mixed  $completed
     * @return void
     */
    public function setCompletedAttribute($completed)
    {
        $this->attributes['realizado'] = (int) (bool) $completed;
    }

    public function setCustomAttribute($value)
    {
        $setCustomAttribute = [
            'user_id'      => 'id_usuario',
            'password'     => 'Password',
            'code'         => 'Codigo',
            'completed'    => 'realizado',
            'completed_at' => 'fecha_realizado',
            'created_at'   => 'created_at',
            'updated_at'   => 'updated_at',
        ];
        return $setCustomAttribute[$value];
    }
}
`

and the error is in all the system thwen i dont have any code especific to show to try to reproduce the error

**Comment by brunogaspar** [comment]
Your Reminder class FQCN is `Rapitiendas\Users\Reminder` but your exception is `Rapitiendas\Users\Auth\Reminder`, so the error is either on your Reminder class namespace or the config file.

Either way, this is an issue on your application.
