### ISSUE TITLE
Working Example

### ISSUE THREAD

**Issue by teddywest32** [cartalyst/sentinel#221]
Can i get a small working example for sentinel on Laravel 5.2 . As i had tried to do it and some other examples asked to add some codes to middleware so that that works like Laravel Auth. But if i get some working example from official support it will be helpful to all other developers who are confused in using sentinel in their projects.

Thanks in advance.

**Comment by brunogaspar** [comment]
Something like this

```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Cartalyst\Sentinel\Laravel\Facades\Sentinel;

class Authenticate
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle(Request $request, Closure $next)
    {
        if (Sentinel::check()) {
            return $next($request);
        }
        
        if ($request->ajax() || $request->wantsJson()) {
            return response('Unauthorized.', 401);
        } 

        return redirect()->guest('login');
    }
}
```

> I haven't tested this middleware, as i kinda modified it from one i have.

The rest of Sentinel usage is on our documentation.
