### ISSUE TITLE
Wiki: Extending Sentinel

### ISSUE THREAD

**Issue by xgathos** [cartalyst/sentinel#223]
Hi,

I guess there is a small bug in the wiki page "Extending Sentinel".
To set the user model on runtime you need "setModel", not "setUserModel":

`Sentinel::getUserRepository()->setModel('App\User'); `

Tested with master branch (2.1.0)

**Comment by suwardany** [comment]
Hello @xgathos 

Thanks for reporting, i've fixed it.
