### ISSUE TITLE
Error in the docs

### ISSUE THREAD

**Issue by zakiaziz** [cartalyst/sentinel#225]
ref: https://cartalyst.com/manual/sentinel/2.0#reminder-createmodel

The example given under `Reminder::createModel()` is 
```
$reminder = Activate::createModel();
```
I  think it should be
```
$reminder = Reminder::createModel();
```

**Comment by suwardany** [comment]
Thanks for reporting @zakiaziz .. it's fixed, should reflect on the website within an hour.
