### ISSUE TITLE
Argument 1 in Reminder::create($user) must be of type array

### ISSUE THREAD

**Issue by zakiaziz** [cartalyst/sentinel#226]
Hi in the [docs](https://cartalyst.com/manual/sentinel/2.0#reminder-create-user) it says to pass off a user object to the `Reminder::create()` function. This is what I'm doing in my code:
```
$user = Sentinel::findByCredentials(['login' => $request->input('username')]);
Reminder::create($user);
```
Which yields me this error:
```
ErrorException in Model.php line 542:
Argument 1 passed to Illuminate\Database\Eloquent\Model::create() must be of the type array, object given, called in .../app/Http/Controllers/Auth/AuthController.php on line 339 and defined
```
If the `Reminder::create()` function needs an array, what should the array keys be?

**Comment by suwardany** [comment]
Hello @zakiaziz 

Make sure you you are using the `Reminder` facade not the model.

`Cartalyst\Sentinel\Laravel\Facades\Reminder`

**Comment by zakiaziz** [comment]
Thanks @suwardany
