### ISSUE TITLE
Insecure Hashers

### ISSUE THREAD

**Issue by paragonie-scott** [cartalyst/sentinel#230]
* https://github.com/cartalyst/sentinel/blob/2.0/src/Hashing/Sha256Hasher.php
* https://github.com/cartalyst/sentinel/blob/2.0/src/Hashing/WhirlpoolHasher.php

There are two things wrong here.

1. [Cryptographic hash functions are not password hash functions](https://paragonie.com/blog/2016/02/how-safely-store-password-in-2016).
2. `H(K || M)` (where in this case K is a "salt" generated by an [insecure RNG](https://github.com/cartalyst/sentinel/issues/228)) is a textbook [length-extension attack](https://blog.skullsecurity.org/2012/everything-you-need-to-know-about-hash-length-extension-attacks) condition.

**Comment by drsii** [comment]
By Default Sentinel uses 

https://github.com/cartalyst/sentinel/blob/2.0/src/Hashing/NativeHasher.php

The hashers mentioned above, and a few others, have been provided for legacy support only and should be avoided.

**Comment by paragonie-scott** [comment]
> The hashers mentioned above, and a few others, have been provided for legacy support only and should be avoided.

Have you considered raising an `E_USER_WARNING` or `E_USER_DEPRECATED` error when these classes are used?

**Comment by AshleyPinner** [comment]
> The hashers mentioned above, and a few others, have been provided for legacy support only and should be avoided.

IMO they should be removed if you do not suggest their usage. The biggest risk of providing insecure code is that someone might elect to use it, with them going under the fair assumption that if it's in the code, it's safe to use.

It'd be much better to provide a method by which the hashes could be upgraded to the latest and greatest method, either by hashing in the new method the old hash (and noting that it's a legacy hash) or by doing it on-login, depend on your threat model and how you feel about having insecure hashes in a database. 

(on a related note, why doesn't NativeHasher expose [password_needs_rehash ()](http://php.net/manual/en/function.password-needs-rehash.php)]? )

**Comment by brunogaspar** [comment]
> IMO they should be removed 

While i understand your point and agree with you, we can't just remove them unless we do a major release, otherwise we might break someones code. A major release is scheduled but there's no ETA.

> It'd be much better to provide a method by which the hashes could be upgraded to the latest and greatest method, either by hashing in the new method the old hash (and noting that it's a legacy hash) or by doing it on-login, depend on your threat model and how you feel about having insecure hashes in a database.

If you have better alternatives, feel free to submit a pull request with those :)
