### ISSUE TITLE
Potential bug with ActivationRepository?

### ISSUE THREAD

**Issue by snsmurf** [cartalyst/sentinel#233]
Hi,

I'm trying to set up Sentinel using Native implementation, currently trying to setup version 2 but having a weird issue when trying to create Activation records for a user.

Eloquent is all setup correctly so currently just in the process of testing Sentinel out and getting my head around all the methods and the problem I've had is that I create a User record and then go to create an activation record and it creates two for the same user. Have no idea why, I've tried to look through the code myself but I have no idea and couldn't see anything that could cause this to happen as it seems to just set the activation code then pass off to the model to save the data.

I setup the USE statement for the native facade then created a user with:

```
$result = Sentinel::register([
        'email' => 'user@example.com',
        'password' => '123456',
        'first_name' => 'mike',
        'last_name' => 'Barlow',
        'permissions' => [
            'permission1' => true,
            'permission2' => true,
            'permission3' => false
        ]
    ]);
    dump($result);
```
Symfony var dumper then gave me the created user object, still all okay by this point.

In a second test, I then used the following code to retrieve the user and to create the Activation record.

```
    $User = Sentinel::findByCredentials([
        'email' => 'user@example.com',
        'password' => '123456'
    ]);
    $result = Sentinel::getActivationRepository()->create($User);

    dump($User);
    dump($result);
```
Running that second block of code, I now have two activation records in the activations table but on the screen is has outputted the user object correctly and the activation record for the FIRST row.
The two activation records timestamps are a second apart, so it's as if it creates one, outputs it's object, then some kind of listener is triggered and then creates another one.

Any ideas what's going on here?

**Comment by brunogaspar** [comment]
Not being able to reproduce this.

@suwardany Any clues?

**Comment by snsmurf** [comment]
Interestingly, I just added `Sentinel::disableDispatcher();` above all the code i mentioned above and it seemingly worked. I've only got the 1 user row and 1 activation row.

Weird though as I would have though the event would have been on user getting created, but when i just register a user and remove the activation create code, it doesn't create any activation rows at all.

**Comment by brunogaspar** [comment]
I think you've most likely ran the same code twice.

That will create 2 activation records, which is expected.

If you're still having the issue, let us know and paste more details about your environment and a consistent way to reproduce the issue.
