### ISSUE TITLE
How to add a error page for not activated?

### ISSUE THREAD

**Issue by skysham** [cartalyst/sentinel#234]
Hi,

I want add a error page when showing 'Your account has not been activated yet.'.

I have tried overall the convertExceptionToResponse function at App\Exceptions\Handler.

    protected function convertExceptionToResponse(Exception $e)
    {
        $debug = config('app.debug', false);

        if ($debug) {
            return (new SymfonyDisplayer($debug))->createResponse($e);
        }

        return response()->view('errors.default', ['exception' => $e], 500);
    }

But seems did not work. Is there any way other to do this?

Thanks.

**Comment by brunogaspar** [comment]
Not really sure what you're asking here, but you can simple check if the user is activated or not in a middleware and if not, redirect to that specific page.
