### ISSUE TITLE
Native integration fails

### ISSUE THREAD

**Issue by cborchmann** [cartalyst/sentinel#236]
Hallo,
i´m trying to get in touch with Sentinel to replace Sentry in my little project. I´m using the native integration shown in the manual.

Here is my basic script:

```php
<?php

// Import the necessary classes
use Cartalyst\Sentinel\Native\Facades\Sentinel;
use Illuminate\Database\Capsule\Manager as Capsule;

// Include the composer autoload file
require 'vendor/autoload.php';

// Setup a new Eloquent Capsule instance
$capsule = new Capsule;



$capsule->addConnection([
    'driver'    => 'mysql',
    'host'      => 'localhost',
    'database'  => 'sentinel',
    'username'  => 'user',
    'password'  => 'secret',
    'charset'   => 'utf8',
    'collation' => 'utf8_unicode_ci',
]);

$capsule->bootEloquent();


// Register a new user
Sentinel::register([
		'email'    => 'test@example.com',
		'password' => 'foobar',
]);
?>
```
Always i get the Error: 

´´´[Fri Apr 29 21:58:40.519010 2016] [:error] [pid 1095] [client 192.168.178.60:53269] PHP Fatal error:  Class 'Illuminate\\Database\\Capsule\\Manager' not found in /var/www/sentinel/index.php on line 11, referer: http://192.168.178.50/
´´´

And my composer.json file:
```
{
    "require": {
        "cartalyst/sentinel": "2.0.*",
        "illuminate/database": "4.0.*"
    }
}
```

Any hints what i have overseen?

Thanks

**Comment by suwardany** [comment]
bump the `illuminate/database` version to something above 5.0, `~5.0` should work.

**Comment by cborchmann** [comment]
Thank you... It worked :-)

**Comment by GhulamJafar** [comment]
I am just installed the Sentinel on laravel 5.2, I am able register user without putting below code in project. Should i use this code in project? If yes, please let me know where i should use this?
// Import the necessary classes
use Cartalyst\Sentinel\Native\Facades\Sentinel;
use Illuminate\Database\Capsule\Manager as Capsule;

// Include the composer autoload file
require 'vendor/autoload.php';

// Setup a new Eloquent Capsule instance
$capsule = new Capsule;



$capsule->addConnection([
    'driver'    => 'mysql',
    'host'      => 'localhost',
    'database'  => 'sentinel',
    'username'  => 'user',
    'password'  => 'secret',
    'charset'   => 'utf8',
    'collation' => 'utf8_unicode_ci',
]);

$capsule->bootEloquent();

**Comment by brunogaspar** [comment]
If you are using Sentinel on Laravel, you don't need any of that, as it's for native integrations only. Please read the documentation a bit more :)
