### ISSUE TITLE
Can't seem to use Auth::user [issue]

### ISSUE THREAD

**Issue by TomKFisher** [cartalyst/sentinel#238]
So essentially i have a login that works and the user is persisted thought my web app. however when it comes to updating the users credentials and i use the code snippet below I get

No [login] credential was passed.

 however i know that the user is logged in  as i see their details loaded into the screen.
How can I use Sentinel to use the Auth::user?

```
$credentials = [
            'title' => $request->title,
            'first_name' => $request->first_name,
            'last_name' => $request->last_name,
            'mobile' => $request->mobile,
            'pref_contact' => $request->pref_contact
        ];

        $user = Sentinel::validForUpdate($user, $credentials);
```

**Comment by brunogaspar** [comment]
> So essentially i have a login that works and the user is persisted thought my web app. however when it comes to updating the users credentials and i use the code snippet below I get

The "error" is intended. If you need to only validate your attributes, use the Laravel validator, the `validForUpdate` requires you to pass the user email and password.

--

> How can I use Sentinel to use the Auth::user?

There's no `Auth::user` you need to use `Auth::getUser()` or `Sentinel::getUser()`.

> **Note:** You need to have the `Auth` facade aliased to the `Sentinel` facade, otherwise it will use the built in Laravel authentication.
