### ISSUE TITLE
Sentinel update not updating all fields?

### ISSUE THREAD

**Issue by TomKFisher** [cartalyst/sentinel#239]
So i'm trying to update a user in the database, all names are correct however the update is only updating the first_name and the last_name.I have no clue why it's ignoring the others.

       $credentials = [
                'first_name' => $request->first_name,
                'last_name' => $request->last_name,
                'title' => $request->title,
                'mobile' => $request->mobile,
                'pref_contact' => $request->pref_contact
    
            ];
    
             Sentinel::update($user, $credentials);
      return redirect('account');

any particular reason for this?

**Comment by brunogaspar** [comment]
You need to [extend](https://github.com/cartalyst/sentinel/wiki/Extending-Sentinel) the user model so that your columns are on the [fillable array](https://github.com/cartalyst/sentinel/blob/2.0/src/Users/EloquentUser.php#L42).
