### ISSUE TITLE
Session fixation

### ISSUE THREAD

**Issue by sajjadrad** [cartalyst/sentinel#241]
Does Sentinel safe about Session Fixation? Depend on this [issue](https://github.com/laravel/framework/issues/2679) it fixed in laravel auth.

**Comment by sajjadrad** [comment]
Please someone answer

**Comment by brunogaspar** [comment]
If Laravel has this covered, which i think it does, then Sentinel is good as well.

**Comment by sajjadrad** [comment]
@brunogaspar It resolved in Laravel Auth system, is Sentinel using Laravel Auth?

**Comment by brunogaspar** [comment]
> is Sentinel using Laravel Auth?

No, Sentinel is it's own thing. If you feel that this issue is still present on Sentinel, feel free to create a PR.

**Comment by sajjadrad** [comment]
@brunogaspar Thank you. I trying to catch it 😂

**Comment by brunogaspar** [comment]
👍
