### ISSUE TITLE
Cookie Domain

### ISSUE THREAD

**Issue by xgathos** [cartalyst/sentinel#243]
I need to set a cookie domain because I use different subdomains (Login on login.domain.tld, redirect to app.domain.tld, where I need to check the loggedin user)

I am not able to figure out how to override the cookie config in sentinel (without patching the code ;)

Is it possible? May I ask you to provide a sample?

I am using Sentinel without Laravel bytheway.

Thank you very much!

**Comment by suwardany** [comment]
Hello @xgathos 

You should be able to achieve that using something as follows

```
use Cartalyst\Sentinel\Native\Facades\Sentinel;
use Cartalyst\Sentinel\Native\SentinelBootstrapper;

$bootstrapper = new SentinelBootstrapper(['cookie' => ['domain' => '.foobar.com']]);

$sentinel = Sentinel::instance($bootstrapper);
```

Then use that newly created instance.

I haven't tested the code but it should at least point to the direction.

Hope that helps.

**Comment by xgathos** [comment]
Thank you very much!
