### ISSUE TITLE
Get all Effective permissions for given User

### ISSUE THREAD

**Issue by rahulbussa** [cartalyst/sentinel#249]
Wondering how do we get all permissions by combining Role permissions and User Permissions.
Do we have any method to get all this info like given in sentinel example.

**Comment by brunogaspar** [comment]
Just use what's mentioned [here](https://github.com/cartalyst/sentinel/issues/128#issuecomment-135578709) there's no method on Sentinel 2.

**Comment by rahulbussa** [comment]
The given method is for combining multiple roles to get effective permission.
I am asking about combining permissions in roles and user permissions .

**Comment by brunogaspar** [comment]
Then use that and get the user permissions and combine, it's not that difficult.
