### ISSUE TITLE
Role authority levels ?

### ISSUE THREAD

**Issue by breaktag** [cartalyst/sentinel#253]
Hello,

Is there anyway to implement role authority levels within Sentinel? I have an app where the Administrator role can create roles, assign permissions to them and assign the roles to other users below them.

My issue at the moment is that we also have a Super User / Developer role (me), which is above the Administrator role. How would I stop the Administrator revoking our super user role, or assigning themselves as a super user?

Many thanks

**Comment by brunogaspar** [comment]
This is more of application logic than Sentinel itself.

I would create a check and disable the form/page if he is a super user.
If you're on Laravel you can achieve this by using a middleware for example.

Hope it helps.

**Comment by breaktag** [comment]
Okay great thanks. That is kind of what I was thinking and I was surprised that no one has already implemented something similar in Laravel.

Cheers
