### ISSUE TITLE
Register hooks

### ISSUE THREAD

**Issue by lorvent** [cartalyst/sentinel#254]
Hello,
Sentinel has any hooks for Register method?

lets say i have a list of blocked email addresses in another table,

before we do registration....i want to call hook and see if entered email address exists in other table or not.

I can call a method before `Sentinel::Register`` but we have social registration aswell so i want to know, if there is any elegant method available.

Thanks.

**Comment by brunogaspar** [comment]
Hello @lorvent 

Sentinel fires some before/after events, you can probably look into that, otherwise you should perform your logic before hitting the register function.
