### ISSUE TITLE
Use with Doctrine

### ISSUE THREAD

**Issue by jasonlfunk** [cartalyst/sentinel#255]
Has there been any work on using Sentinel with Doctrine? I'm happy to do it myself, if there aren't any packages that provide it - but I don't want to reinvent the wheel if it's already been done.

Will it be as simple as writing `Doctrine` versions of the current `Eloquent*` models? Or will I run into any other challenges?

**Comment by brunogaspar** [comment]
Hello @jasonlfunk 

We don't have any official doctrine implementation, but it's something that would be valuable to have.

I remember this was asked [before](https://github.com/cartalyst/sentinel/search?q=doctrine&type=Issues&utf8=%E2%9C%93) probably we can have @guiwoda help to achieve it?

**Comment by guiwoda** [comment]
Absolutely! 
I have some code made for the company I'm working at. Let me check next week if they are alright with opening it!

**Comment by brunogaspar** [comment]
@guiwoda @jasonlfunk What would be the best way to have this?

We can most likely setup a repository for this i guess.

**Comment by guiwoda** [comment]
Allright! This is what we have: https://github.com/digbang/security
We've made it public _just now_.

It's been designed as a wrapper around Sentinel, allowing multiple security contexts and implementing all needed interface through Doctrine repositories and entities.
We can probably work together to break it into smaller pieces, such as a "sentinel-doctrine-adapter" separated from the rest of the code.

Cheers!

**Comment by odahcam** [comment]
So with Doctrine, Sentinel could work aiming database operations to Doctrine Entities and, because of this, we could have custom database naming?

**Comment by guiwoda** [comment]
@odahcam well, database naming could be customized with either ORM. Greatest difference is in how your model knows or doesn't know about persistance, AFAIK.

**Comment by odahcam** [comment]
This lib could use some Mapping standards where with Doctrine we could point our custom named columns to the names that this lib expects. This would a big differential against other Auth solutions, I found 0 solutions that allow custom database schemas.

**Comment by brunogaspar** [comment]
@odahcam Care to elaborate a bit more on how you might implement such changes on the library itself?

We're always open to suggestions and improvements.

**Comment by brunogaspar** [comment]
The idea is interesting, not sure how easy/doable that would be to implement.

> Also, I could write some code if you want.

That would be very nice, it can help understand your vision on this more easily :)

Thanks!

**Comment by guiwoda** [comment]
You can see how we did exactly that in https://github.com/digbang/security

**Comment by odahcam** [comment]
Just a few questions (I'm a newbie in Laravel, I don't like it enough to study it):

1. As long as I know, Eloquent is the main ORM here and it doesn't have data mapping, am I right?
2. I read in the docs: Can I really use *any* ORM with Sentinel as the docs say?
