### ISSUE TITLE
last_login on basic() auth 

### ISSUE THREAD

**Issue by gwenth** [cartalyst/sentinel#256]
Hi,

I don't know if you did it on purpose or not but I'm using an authentication with basic method. it works great but this method doesn't call recordLogin method. Because of that, the last_login remains empty.

Is that a kind a missing feature or is basic method designed for not calling recordLogin ?

Thanks for your help

**Comment by brunogaspar** [comment]
I think this is intended but i'll leave to @suwardany to chime in.

**Comment by gwenth** [comment]
Hi !

I would be very interested to know more about it : do you feel like it is a bad practice to record the login on basic auth ?

**Comment by brunogaspar** [comment]
I wouldn't call bad practice, but I believe it's because you're not really logging in but instead you're authenticating a user.

**Comment by suwardany** [comment]
Hello @gwenth .. this is as @brunogaspar mentioned above, basic authentication or authentication  itself (without login) does not call recordLogin .. just the login methods do.
