### ISSUE TITLE
Can't use facade in blade template

### ISSUE THREAD

**Issue by LoneWolfPR** [cartalyst/sentinel#258]
I've triple checked that i've defined the service provider and facades in app.php properly. However when I put a simple `@if (Sentinel::check())` in my blade template I get this error: `FatalErrorException in ClassLoader.php line 314:
Maximum function nesting level of '100' reached, aborting!`

**Comment by brunogaspar** [comment]
Try to increase the value of `xdebug.max_nesting_level` in your php.ini or just turn `xdebug` off.

Hope it helps.
