### ISSUE TITLE
Sentinel Reminder::exists() error

### ISSUE THREAD

**Issue by shahidbasheer** [cartalyst/sentinel#259]
HI Im getting error with  this Reminder::exists($user) function `Argument 1 passed to Cartalyst\Sentinel\Reminders\IlluminateReminderRepository::exists() must implement interface cartalyst\Sentinel\Users\UserInterface`

here is Code same as on example page. 

```
`$user = Sentinel::findById($credentials);

//dd($user); // this dump user return collection object of user

 $reminder = Reminder::exists( $user );`
```

**Comment by brunogaspar** [comment]
I'm seeing that you're passing `$credentials` to the `findById` method, it should be the user id, not an array.

With that said, make sure that what's being returned on `$user` is really an user object that implements the `UserInterface` as it seems a logic issue on your application.

**Comment by shahidbasheer** [comment]
Thanks it solved. 
$credential array had user id and findBydId returned laravel collection object that had EloquentUser object. By passing id it returned  EloquentUser object.
