### ISSUE TITLE
Permissions checking are using strict php comparison

### ISSUE THREAD

**Issue by CoolGoose** [cartalyst/sentinel#262]
Pull request :) https://github.com/cartalyst/sentinel/compare/2.0...CoolGoose:patch-1

This should typecast nicely 1/0 db values

**Comment by CoolGoose** [comment]
@suwardany my question in this case is how are you storing true/false in the database ? usually mysql has bool that's actually tinyint(1)

**Comment by suwardany** [comment]
@CoolGoose permissions are json encoded in a text field .. they are not stored on separate fields.
