### ISSUE TITLE
Overwriting/extending Throttle model (to rename/prefix the $table)

### ISSUE THREAD

**Issue by caruanas** [cartalyst/sentinel#263]
Hi all,

following the suggestions from other threads/questions (like #168), I am extending my models to be able to rename (or rather, add a prefix to) the db table names.

For example:

```
Sentinel::getUserRepository()->setModel("MyEloquentUser");

class MyEloquentUser extends \Cartalyst\Sentinel\Users\EloquentUser
{
	
	function __construct()
    {
		$this->table = config::getInstance()->getValue("dbTablePrefix") . "users";
    }
	
	public function roles()
    {
        return $this->belongsToMany(static::$rolesModel, config::getInstance()->getValue("dbTablePrefix") . 'role_users', 'user_id', 'role_id')->withTimestamps();
    }
}
```

(where config::getInstance()->getValue("dbTablePrefix") is my way of getting a common prefix).

However there is no Sentinel::getThrottleRepository(), naturally. Since this is my first time working with Sentinel, I cannot figure out from where I can get access to set the Throttle model to point to my extended class.

Note: I am using Sentinel natively, without Laravel.

**Comment by suwardany** [comment]
Hello @caruanas

I've pushed a fix for the missing setter/getter for the throttle repository, you can pull it in by appending `@dev` to the sentinel version on your composer.json file until this is tagged.

Regarding model overrides, you could use something as follows

```
use Cartalyst\Sentinel\Native\Facades\Sentinel;
use Cartalyst\Sentinel\Native\SentinelBootstrapper;

$config = 'your_config.php'; // A copy of sentinel's config file and update the model values to reference your overridden models

$bootstrapper = new SentinelBootstrapper($config);

$sentinel = Sentinel::instance($bootstrapper);
```

That should take care of the models as well.

Let me know if you have any further questions.

**Comment by caruanas** [comment]
Thank you @suwardany, that is awesome!

You've also managed to answer another question I've been pondering: how to override the config. Just perfect!

Today was my first forage with Sentinel, and I must say I'm impressed.

Thanks again!

**Comment by suwardany** [comment]
Glad i could help, you're welcome, @caruanas

**Comment by caruanas** [comment]
I've noticed a small bug related to this.

In SentinelBootstrapper.php, in the createUsers() function, the persistence model is being pulled from the config file (as intended) like so: `$persistences = $this->config['persistences']['model'];`

However perhaps this should also/instead be called within the `createPersistence()` function and passed to the `return new IlluminatePersistenceRepository($session, $cookie);` within that same function?

That seemed to cause the extended persistence model to be recognised.

**Comment by suwardany** [comment]
Pushed a fix for this @caruanas

**Comment by kavin-90** [comment]
@suwardany  thanks but why `Sentinel::getUserRepository()->setModel("MyEloquentUser");` not works?

**Comment by suwardany** [comment]
It does work, there are various instances where the user model is required though. https://github.com/cartalyst/sentinel/blob/2.0/src/Native/SentinelBootstrapper.php#L150-L174

**Comment by kavin-90** [comment]
@suwardany thanks
