### ISSUE TITLE
Problem access User relationships inside web pages

### ISSUE THREAD

**Issue by sloan58** [cartalyst/sentinel#267]
I'm using Sentinel with Laravel 5.2 and have run into an issue accessing relationships defined on my User model when calling from a web page.  If I use artisan tinker I'm able to resolve the relationship.

My App\User relationship is:

`public function tasks()
    {
        return $this->hasMany('App\Task');
    }`

In my Auth controller I perform a 'Sentinel::authenticateAndRemember()' and can access all of the User parameters like id, name, etc by 'Sentinel::getUser()' but when I call the 'Sentinel::getUser()->tasks()' relationship I receive the 'Call to undefined method' error.

I've run through the same process inside of tinker and the calls to tasks() works.  I've probably wired something up incorrectly but can't seem to track it down.

**Comment by brunogaspar** [comment]
If you haven't, you'll need to tell Sentinel to use your User model.

Have a look in [this tutorial](https://github.com/cartalyst/sentinel/wiki/Extending-Sentinel) on how to do this.

Hope it helps!

**Comment by sloan58** [comment]
Wow, thanks for the quick response!  I'll have run through the tutorial.  I glanced over it and I think it might fix another issue I was having trying to access attributes on AdldapUser which I'm using with Sentinel.

**Comment by brunogaspar** [comment]
No problem.

Let us know if you get stuck!

**Comment by sloan58** [comment]
That totally fixed it!  Just had to swap out the model in the Sentinel config.  I'm see the AdlapUser trait on the model now as well.  It's null, but at least it's progress...  Thank you for the help.

**Comment by brunogaspar** [comment]
Awesome, and no problem!

**Comment by kavin-90** [comment]
I can't get it work on native one my code is

`Sentinel::getUserRepository()->setModel('User');`
because i don't need Namespace for models.

for only Sentinel and eloquent i need to use full path.

when i dd($user) i got `Cartalyst\Sentinel\Users\EloquentUser Object` but no relationship
