### ISSUE TITLE
Migrate Users to Sentinel 

### ISSUE THREAD

**Issue by aniljailta** [cartalyst/sentinel#269]
Hi ,

I am using Sentinel and doing users migration .

So i have users table with all user information and want to convert them to Sentinel based . Tables required by Sentinel are already migrated , activation , persistence , throttle , roles and user_roles are already in place .

So how can i assign this users table data to sentinel based and assign them to a particular slug or role ? 

any quick solution ? 

Thanks .

**Comment by brunogaspar** [comment]
You want to import your legacy users table to Sentinel?

**Comment by brunogaspar** [comment]
Closing due to lack of response.
