### ISSUE TITLE
Sentinel::login() in L5.2 middleware failed, but works in controller

### ISSUE THREAD

**Issue by newbro** [cartalyst/sentinel#270]
I'm using Sentinel 2.0.12 with Laravel 5.2. For some reason when I call Sentinel::login($user) within a middleware, it will not persist in session which cause subsequent page request with Sentinel::guest() to return true. However if I runs the same Sentinel::login() code in a controller, it will works as expected.

**Comment by brunogaspar** [comment]
It's not an issue with Sentinel and i doubt it's an issue with Laravel, but feel free to open an issue on Laravel side, otherwise, perform the login within a controller, which is the recommended way.
