### ISSUE TITLE
Laravel 5.3 compatibility

### ISSUE THREAD

**Issue by kasirye** [cartalyst/sentinel#272]
Sentinel not compatible with laravel 5.3

**Comment by brunogaspar** [comment]
We are aware, thanks.

**Comment by lorvent** [comment]
i am getting this error in 5.3

```
FatalErrorException in EloquentUser.php line 209:

Call to a member function getRoleId() on integer
```

same code working properly in 5.2

**Comment by lorvent** [comment]
Hello,
Will you be coming up with solution for this?

Thanks.

**Comment by brunogaspar** [comment]
Yes, but i can't give any ETA.

**Comment by brunogaspar** [comment]
I've pushed a [feature branch](https://github.com/cartalyst/sentinel/tree/feature/laravel-53) with Laravel 5.3 support, we still need to conduct some tests on an application, but it should work.

If someone wants to give it a go, please go ahead and let us know if you find any issues.

**Comment by brunogaspar** [comment]
2.0.13 tagged.

**Comment by webreinvent** [comment]
Now, can I use sentinel with Laravel 5.3 in production env?

**Comment by brunogaspar** [comment]
@webreinvent Yes.
