### ISSUE TITLE
Update User Role

### ISSUE THREAD

**Issue by kirobo** [cartalyst/sentinel#274]
Is it possible to update a user's role? 
Also, how to find a user's role if I have his ID?

**Comment by brunogaspar** [comment]
> Is it possible to update a user's role?

You need to have the user object and the role object you want to attach/detach from the user.

You can use the following [attach a user to a role](https://cartalyst.com/manual/sentinel/2.0#assign-a-user-to-a-role) and [detach a user from a role](https://cartalyst.com/manual/sentinel/2.0#remove-a-user-from-a-role).

Or do the inverse: `$user->roles()->attach($role);`.

> Also, how to find a user's role if I have his ID?

Check [here](https://cartalyst.com/manual/sentinel/2.0#sentinel-findrolebyid).

Hope it helps.

**Comment by kirobo** [comment]
Hey, This is exactly what I did. 

$group =$request->get('role_id');
                //No method in Sentry to update Role.
                //todo: Find a more secure way of updating the users role               
                $role = Sentinel::findRoleById($group);                
                $role->users()->attach($user);

But it gives me error - SQL Integrity constraint violation - basically, the sentinel is trying to insert a new record where primary key is user_id - Is there any way to UPDATE?

**Comment by kirobo** [comment]
@brunogaspar Kindly reply. This is a common question. I appreciate your help.

**Comment by brunogaspar** [comment]
That's expected to happen.

You need to verify if the user has that role or not already.

We use this which works great

```php
if ($roles = array_get($data, 'roles')) {
    // Get the user roles
    $userRoles = $user->roles->lists('id')->toArray();

    // Prepare the roles to be added and removed
    $toAdd = array_diff($roles, $userRoles);
    $toDel = array_diff($userRoles, $roles);

    // Detach the user roles
    if (! empty($toDel)) {
        $user->roles()->detach($toDel);
    }

    // Attach the user roles
    if (! empty($toAdd)) {
        $user->roles()->attach($toAdd);
    }
}
```

**Comment by imagine10255** [comment]
Hi, why not any error (throw) ?

**Comment by houssemeddindhouib** [comment]
when i chage the role of my user i found this problem
**# **ErrorException in VerifyCsrfToken.php line 156:
Trying to get property of non-object****

any help please

**Comment by RonnieCSE** [comment]
array_get($data, 'roles')

this line I do not Understanding Bro

would u help me?
