### ISSUE TITLE
"cartalyst_sentinel" cookie becoming null in subsequent request from browser(GOOGLE LOGIN)

### ISSUE THREAD

**Issue by AshishCode** [cartalyst/sentinel#276]
I am trying to implement google login in my application. I use slimframework and sentinel for native auth implementation.
When I try to make the first login request then two `Set Cookie` headers are sent to the browser(chrome). But then the client side makes another request to the server in which the value for `cartalyst_sentinel` cookie comes out to be `null`.
The app works completely fine in case of normal(through credentials) login. The issue only surfaces in google login. In case of normal login only one `Set Cookie` header is sent from the server's end which is for `cartalyst_sentinel`.
The google login works in a way where the server just validates the auth code provided by the client and then logs the user in through sentinel.
There seems to be no issue while using postman. It's only a browser specific issue.

**Comment by brunogaspar** [comment]
Sorry, but i'm not really following what your issue has to do with Sentinel?

**Comment by AshishCode** [comment]
Maybe these screenshots will help me explain the issue.

These are the cookies which are received at the time of login from google. You can see that two `Set-Cookie` headers are received. 
The first doubt that I have is, why are two `Set-Cookie` headers being sent ? In case of normal(using credentials) only one(cartalyst_sentinel and not PHPSESSID) such header is received from the server.
![pasted image at 2016_09_01 03_28 pm](https://cloud.githubusercontent.com/assets/5352627/18271817/cdaac262-7451-11e6-80c5-791212f1971f.png)

The cookie being sent at the time of second request to the server. The value for `cartalyst_sentinel` comes out to be `null`.
![pasted image at 2016_09_01 02_41 pm](https://cloud.githubusercontent.com/assets/5352627/18271818/cddab4d6-7451-11e6-93e7-f3f0dc235e43.png)

So why are two headers being received? And can that be an issue for the sentinel cookie to be `null` ?

Are there any knows issues in implementing google login with sentinel(native) ?

**Comment by brunogaspar** [comment]
Sorry, but not having a good way to reproduce the issue, it seems to be something outside of our scope.

If you still have this issue, please provide some steps to  reproduce it.

Thanks.
