### ISSUE TITLE
Problem with ThrottlingException

### ISSUE THREAD

**Issue by wassimhattab** [cartalyst/sentinel#277]
Hello, im using asgardcms in my project.
In the backend the login form is usint sentinel so i used it in the frontend also,
but when i try to login to many time with my email the login form is blocked not only my email but all the emails.
Is there any solution for this problem or if i can disable the ThrottlingException?

**Comment by brunogaspar** [comment]
Your ip gets blocked and you need to wait a certain amount of time until it gets unblocked, the more you try to login with invalid credentials, the more you will need to wait for it to unblock you.

You can disable it by commenting out [this line](https://github.com/cartalyst/sentinel/blob/2.0/src/config/config.php#L136).

Hope it helps.
