### ISSUE TITLE
Problem with version laravel 5.3 and v2.0.13

### ISSUE THREAD

**Issue by stojankukrika** [cartalyst/sentinel#280]
Hi,
I have problem with new version 2.0.13 and laravel 5.3. I use it like in laravel 5.2, I am copy all files for the project from old project to new project when I put new version laravel and other depend. composer packages. After that I am copy project files. And when I am start it, it's great login user in login page. But I have logic that if user login, redirect to some route. It's redirect user but Sentinel::getUser() return null. Do you maybe know what is the problem? In version with laravel 5.2 it's works well.

**Comment by brunogaspar** [comment]
Hello,

Where are you applying that logic?

A code snippet would be helpful.

**Comment by stojankukrika** [comment]
Here is post method for login in AuthController:

` 
public function postSignin(LoginRequest $request)
    {
        try {
            if ($user = Sentinel::authenticate($request->only('email', 'password'), $request->has('remember'))) {
                Flash::success(trans('auth.signin_success'));
                return redirect("/");
            }
            Flash::error(trans('auth.login_params_not_valid'));
        } catch (NotActivatedException $e) {
            Flash::error(trans('auth.account_not_activated'));
        } catch (ThrottlingException $e) {
            $delay = $e->getDelay();
            Flash::error(trans('auth.account_suspended') . $delay . trans('auth.second'));
        }
        return back()->withInput();
    }
`

and here is SecureController and his constructor that other Controllers that is for login user use:
`
 public function __construct()
    {
        dd(Sentinel::getUser());// - here return NULL
        if (Sentinel::check()) {
            $this->user = User::find(Sentinel::getUser()->id);
            if(!isset($this->user)){
                Sentinel::logout(null, true);
                Session::flush();
                Flash::error(trans('secure.account_deleted'));

                return redirect()->guest('/');
            }
            $this->shareValues();
        } else {
            Sentinel::logout(null, true);
        }
    }
`

**Comment by brunogaspar** [comment]
> Sorry for bed formating code :(

No problem, i've formatted it.

In regards to your issue, in Laravel 5.3 you can't access session data on your controller's constructor anymore because the middleware as not run at that point.

To fix that, you'll need to define a `Closure` based middleware directly on your controller's contructor.

Here's an example with a bit of your code (adjust to your needs of course)

```php
public function __construct()
{
    $this->middleware(function ($request, $next) {
        if (! Sentinel::check()) {
            return redirect()->guest('/');
        }

        return $next($request);
    });
}
```

**Comment by stojankukrika** [comment]
OK. TNX for info and help! 👍

**Comment by nijesh-wiredelta** [comment]
Thanks, working fine.
