### ISSUE TITLE
Exception when trying to login with not existing user

### ISSUE THREAD

**Issue by mixalistzikas** [cartalyst/sentinel#282]
When I use an email/password to login, if email exists to my db.. then... no problem..

The problem is when someone trying to login with a non existing email. I can't catch this exception.

vendor/cartalyst/sentinel/src/Sentinel.php
```
$user = $this->users->findByCredentials($credentials);
$this->users->validateCredentials($user, $credentials);
```

if found that the first line returns $user = false and the validateCredentials wants the $user to be "UserInterface"

`public function validateCredentials(UserInterface $user, array $credentials);`

What can I do? 

This this is the error I get

`FatalThrowableError in IlluminateUserRepository.php line 152: Type error: Argument 1 passed to Cartalyst\Sentinel\Users\IlluminateUserRepository::validateCredentials() must implement interface Cartalyst\Sentinel\Users\UserInterface, null given, called in /var/www/html/vendor/cartalyst/sentinel/src/Sentinel.php on line 302`

```

try {
            $credentials = $request->only('email', 'password');
            $user = Sentinel::authenticate($credentials, $request->has('remember'));
        }catch(\Cartalyst\Sentinel\Checkpoints\NotActivatedException $e){
            $user = false;
            echo 'NotActivatedException';
            echo '<br/>';
            echo $e->getMessage();
            $error = $e->getMessage();
        } catch (\Cartalyst\Sentinel\Checkpoints\ThrottlingException $e) {
            $user = false;
            echo 'ThrottlingException';
            echo '<br/>';
            echo $e->getMessage();
            $error = $e->getMessage();
        }

        if ($user !== false)
            return redirect('home');
        else
            return redirect('login')->withInput($request->only('email', 'remember'))->withErrors(['email' => $error]);
```

**Comment by brunogaspar** [comment]
What version of Sentinel and Laravel?

Not being able to reproduce this.

**Comment by mixalistzikas** [comment]
"name": "laravel/framework",
"version": "v5.3.10",

"name": "cartalyst/sentinel",
"version": "v2.0.13",

**Comment by mixalistzikas** [comment]
My bad... i was trying to debug something else and i made some changes to the core file..

Nothing wrong...  Sorry

**Comment by brunogaspar** [comment]
No problem, glad it's working now :)
