### ISSUE TITLE
Why aren't thresholds for throttling sorted?

### ISSUE THREAD

**Issue by alexweissman** [cartalyst/sentinel#283]
I'm looking at the implementation of the threshold-based throttling algorithm, and I notice that thresholds don't seem to get sorted anywhere.  All I see is a [call to `array_reverse`](https://github.com/cartalyst/sentinel/blob/2.0/src/Throttling/IlluminateThrottleRepository.php#L360), and then the algorithm stops at the first eligible threshold for which the last event is more recent than the threshold delay.  

```
// Threshold definitions
'thresholds' => [
    10 => 1,
    20 => 2,
    30 => 4,
    40 => 8,
    50 => 16,
    60 => 12
],
...
// Thresholding algorithm
foreach (array_reverse($this->$thresholds, true) as $attempts => $delay) {
    if ($throttles->count() <= $attempts) {
        continue;
    }
    if ($last->created_at->diffInSeconds() < $delay) {
        return $this->secondsToFree($last, $delay);
    }
}
```

So for example if the algorithm sees that more than 50 attempts have been made, and the last event was x < 16 seconds ago, it returns the remaining (16 - x) seconds.

However, any event that exceeds 50 attempts would also exceed 40 attempts, and could also have exceeded the delay for the 40-attempt rule (x < 12).  In that case, the delay would be different, at (12 - x) seconds.

It seems that based on the order in which the default throttling rules are defined, and the use of `array_reverse`, that Sentinel's strategy is to find the rule with the **largest** number of attempts for which the event history violates the corresponding delay.  But it doesn't seem to be enforced, and so for example if the loop encountered and found to be violated the 40-attempt rule before the 50-attempt rule, it would use that to compute delay.

Is this on purpose to allow developers to arbitrarily order rules, or is it just assumed that the defined rules will always be pre-sorted?

**Comment by brunogaspar** [comment]
Feel free to submit a [pull request](https://help.github.com/articles/using-pull-requests/).

**Comment by alexweissman** [comment]
Ah ok so, would this be a bug fix, or an enhancement?

**Comment by brunogaspar** [comment]
More of an improvement.
