### ISSUE TITLE
Removing all permissions from User or Role

### ISSUE THREAD

**Issue by DanVeira** [cartalyst/sentinel#286]
How do I go about removing all permissions from a certain User or Role?

Currently I'm doing this:
```
$role->permissions = array();
$role->save();
```
It _works_, but is it acceptable?

I can't set it to `null` because it will throw an error:
`Cartalyst\Sentinel\Roles\EloquentRole::setPermissionsAttribute() must be of the type array, null given`

I understand I could do a `foreach` and call the `removePermission()` method but that seems wasteful as I know for sure I want to remove them all.

**Comment by brunogaspar** [comment]
Hello @DanVeira 

Your solution is perfectly acceptable.
