### ISSUE TITLE
how to set allow only one user at the same time online

### ISSUE THREAD

**Issue by LiXunGuan** [cartalyst/sentinel#287]

**Comment by brunogaspar** [comment]
One session per account or one entire session on the entire application?

I'm rather confused to be honest since you didn't give much information.

**Comment by LiXunGuan** [comment]
The same account, behind the login, the front will be expire

**Comment by brunogaspar** [comment]
I'm going to assume that you're using Laravel, therefore you just need to publish the configuration file and modify the persistence mode [here]( https://github.com/cartalyst/sentinel/blob/2.0/src/config/config.php#L116) from `false` to `true` and it should create the desired workflow.

**Comment by LiXunGuan** [comment]
3q
