### ISSUE TITLE
Phalcon Integration [Proposal]

### ISSUE THREAD

**Issue by talal424** [cartalyst/sentinel#290]
I made an integration for phalcon

you can check it out as i forked your project and made the changes 

plus i made a change to Native\SentinelBootstrapper.php on line: 125-127
to enable or disable single persistence mode.

# SentinelBootstrapper.php
```php
$single = $config['persistences']['single'];

return new IlluminatePersistenceRepository($session, $cookie, $model, $single);
```
[SentinelPhalcon](https://github.com/talal424/sentinel)

**Comment by brunogaspar** [comment]
Thanks, but this type of integrations needs to stay outside of our package.

But cool that you're using Sentinel on a different framework other than Laravel :)
