### ISSUE TITLE
Is possible Integration in Laravel 5.3

### ISSUE THREAD

**Issue by adw-cr** [cartalyst/sentinel#292]
Is possible Integration in Laravel 5.3?

**Comment by brunogaspar** [comment]
Yes, have you followed the documentation?

**Comment by adw-cr** [comment]
Here https://cartalyst.com/manual/sentinel/2.0#laravel-5?

**Comment by brunogaspar** [comment]
Correct

**Comment by adw-cr** [comment]
Perfect i will integrate this package in my project.
Thanks @brunogaspar
