### ISSUE TITLE
How mass assign user roles

### ISSUE THREAD

**Issue by kneipp** [cartalyst/sentinel#293]
Hi there!

I'm working with CSV and avoiding N+1 queries, for sample:
```
            $users = [];
            foreach ($results->get() as $row) {
                $validator = Validator::make(['email' => $row->email, ...], [
                    ...
                ]);


                if (!$validator->fails()) {
                    array_push($users, [
                        'cpf' => $row->cpf,
                        'card_number' => $row->numero_cartao,
                        'email' => $row->email,
                        'password' => bcrypt($row->senha),
                        'first_name' => $row->nome,
                        'last_name' => $row->sobrenome
                    ]);
                }
            }
            User::insert($users);
 ```
How can mass assign roles or better way to work with many data trying to avoid N+1 queries?

**Comment by brunogaspar** [comment]
Hello @kneipp 

It's probably better for you to ask this on the Laravel forums or on the Laravel Slack.

I would try to create an array of roles with the user id, and then use the insert as you're doing for users. Not sure if it would work properly or not, but just an idea.

**Comment by kneipp** [comment]
@brunogaspar what do you thinking about new Sentinel methods or change register method to mass assign option? Is it a good idea to work on? Thanks

**Comment by brunogaspar** [comment]
@kneipp Not sure, i have the feeling it's out of the scope of Sentinel to be honest.

@suwardany What do you think?

**Comment by kneipp** [comment]
My concern is about N+1 inserts and updates using Sentinel. We can do this with insert() and update() methods in Laravel. Not sure if have any way to do mass-assign using Sentinel auth. 
BTW i'm newbie w/ Sentinel.
Appreciate, [ ] 's
