### ISSUE TITLE
Renaming tables

### ISSUE THREAD

**Issue by JD719** [cartalyst/sentinel#294]
Hi, is it possible to rename the db tables in a persistent way?
Unprefixed tables are always a bad idea, specially when you use such common names like 'users'.
Thanks.

**Comment by cbj4074** [comment]
In my humble opinion, prefixing tables is a worse idea than separating tables into different schemas (or different databases, if the implementation has no concept of schemas, e.g., MySQL).

That said, if you insist on prefixing tables (or your environment won't allow for separate schemas/databases), you can simply extend Sentinel's models and override the `$table` property, and then update your Sentinel configuration to use your custom model.

The process is explained here:

https://github.com/cartalyst/sentinel/wiki/Extending-Sentinel

**Comment by brunogaspar** [comment]
Thanks @cbj4074 !
