### ISSUE TITLE
Error Bag in FormRequest

### ISSUE THREAD

**Issue by CecileV** [cartalyst/sentinel#300]
Hi,

I would like to have 2 forms in one view ( login form and register form).

I just edit the view selection in `config/sentinel.php`

```
    'view' => [
         'session_login' => 'sentinel.loginAndRegister',
         'user_register' => 'sentinel.loginAndRegister'
    ],
```

I've a problem with errors display. Without error bag in FormRequest it's complicated. How I can do ? Do you have a idea about how to solve this problem neatly ?

Best,

PS : Sorry for my english. It's not my native language. Sorry if my question sounds silly.

**Comment by brunogaspar** [comment]
Hi,

It seems that you are on the incorrect repository and you seem to be using https://github.com/rydurham/Sentinel

Let me know if you have any questions.
