### ISSUE TITLE
Method Cartalyst\Sentinel\Sentinel::hasAccess() can only be called if a user is logged in.

### ISSUE THREAD

**Issue by GhulamJafar** [cartalyst/sentinel#301]
When I check permission `Sentinel::hasAccess('application.applications.index')` in controller it returns true. Its fine. But when i try to check same permissions in sidebarmenu creator class, it return the following error. However i am already logged-in. 
**Method Cartalyst\Sentinel\Sentinel::hasAccess() can only be called if a user is logged in.**

My sidebarcreator class.
`<?php namespace Modules\Application\Sidebar;

use Cartalyst\Sentinel\Laravel\Facades\Sentinel;
use Maatwebsite\Sidebar\Group;
use Maatwebsite\Sidebar\Item;
use Maatwebsite\Sidebar\Menu;
use Modules\User\Repositories\Contracts\AuthenticationInterface as Authentication;
use Maatwebsite\Sidebar\SidebarExtender;

class MySidebarExtender implements SidebarExtender
{
    /**
     * @var Authentication
     */
    protected $auth;

    /**
     * @param Authentication $auth
     *
     * @internal param Guard $guard
     */
    public function __construct(Authentication $auth)
    {
        dd(Sentinel::hasAccess('application.applications.index'));
        $this->auth = $auth;
    }

    /**
     * @param Menu $menu
     *
     * @return Menu
     */
    public function extendWith(Menu $menu)
    {
        $menu->group("Features", function (Group $group) {
            $group->item("Borrower Application", function (Item $item) {
                $item->weight(1);
                $item->icon("fa fa-flag-o");
                $item->route('admin.application.applications.index');
                $item->authorize(
                    $this->auth->hasAccess('application.applications.index') 
                );
            });
        });
        return $menu;
    }
}
`

**Comment by brunogaspar** [comment]
What version of Laravel and how is this class instantiated/used?

**Comment by GhulamJafar** [comment]
I am using Laravel 5.2 & Sentinel 2.0

Actually I am using Nwidart Module system and "maatwebsite/laravel-sidebar": "~2.1" to create sidebar. This class is instantiated by core module's class **" AdminSideBar"** to build menu, Please see below
`<?php namespace Modules\Core\Sidebar;

use Illuminate\Contracts\Container\Container;
use Maatwebsite\Sidebar\Menu;
use Maatwebsite\Sidebar\ShouldCache;
use Maatwebsite\Sidebar\Sidebar;
use Maatwebsite\Sidebar\Traits\CacheableTrait;
use Nwidart\Modules\Contracts\RepositoryInterface;

class AdminSidebar implements Sidebar, ShouldCache
{
    use CacheableTrait;
    /**
     * @var Menu
     */
    protected $menu;

    /**
     * @var RepositoryInterface
     */
    protected $modules;

    /**
     * @var Container
     */
    protected $container;

    /**
     * @param Menu                $menu
     * @param RepositoryInterface $modules
     * @param Container           $container
     */
    public function __construct(Menu $menu, RepositoryInterface $modules, Container $container)
    {
        $this->menu = $menu;
        $this->modules = $modules;
        $this->container = $container;
    }

    /**
     * Build your sidebar implementation here
     */
    public function build()
    {
        foreach ($this->modules->enabled() as $module) {
            $name = studly_case($module->get('name'));
            **$class = 'Modules\\' . $name . '\\Sidebar\\MySidebarExtender';**
            if (class_exists($class)) {
                $extender = $this->container->make($class);

                $this->menu->add(
                    $extender->extendWith($this->menu)
                );
            }
        }
    }`

**Comment by GhulamJafar** [comment]
Any Help? I am stucked? Why is this happening?

**Comment by brunogaspar** [comment]
I would contact the author of that sidebar package as i'm not seeing this being an issue with Sentinel, since it works on your application already.

**Comment by GhulamJafar** [comment]
How told you that my issue is resolved? How can you mark that my issue is resolved? I am still having the issue.

**Comment by brunogaspar** [comment]
@GhulamJafar As i mentioned on my last reply, you should contact the author of that sidebar package/module you're using to get support, since your issue doesn't seem to be related to Sentinel, as Sentinel is already working fine on your application as you mentioned.
