### ISSUE TITLE
Add attributes to Persistence

### ISSUE THREAD

**Issue by Thorazine** [cartalyst/sentinel#304]
In a new clean and shiny project I'm building I need to add attributes to the persistence table. It seems like the perfect place to add browser, device and location information. So I have created my own model and extended it with Cartalyst\Sentinel\Persistences\EloquentPersistence. This obviously works like a charm.

But now I need to add additional data to the Persistence model on create only and I can't see a way to this without altering the package in the vendor folder, which is sucky. However, the docs say that it is possible to do so, but no explanation is given anywhere to find. 

What am I missing.

**Comment by pankitgami** [comment]
Hi,

One solution is that you can override the save method in your model.

    use Cartalyst\Sentinel\Persistences\EloquentPersistence as SentinelEloquentPersistence;

    class EloquentPersistence extends SentinelEloquentPersistence
    {
        public function save(){
             // your code
         }
    }

**Comment by brunogaspar** [comment]
You can do probably like how @pankitgami suggested or extend the Persisistences repository and store the extra data you need.
