### ISSUE TITLE
[Proposal] Tightly Coupled to Eloquent

### ISSUE THREAD

**Issue by HeathNaylor** [cartalyst/sentinel#308]
Looking to use this in a pet project, nothing major. Noticed a tight coupling to Eloquent throughout. Looking through the source I believe I can shim in support for something like Doctrine or Propel, but found it interesting that this was not created in near zero-dependency fashion. Is this something that you would entertain decoupling in the future? I might have interest in doing some contributions if it is a focus.

**Comment by HeathNaylor** [comment]
Went through implementing the native Sentinel via the facade, ended up needing `illuminate/events` and `symfony/http-foundation`. I did not see this documented anywhere. Would you be open to a PR for just the README for the time being and then further discussion on decoupling the models and repositories?

**Comment by brunogaspar** [comment]
Sentinel uses Eloquent by default, but you can create your own implemention and extend Sentinel to use your implementation instead.

Here's a topic that has a Doctrine implementation https://github.com/cartalyst/sentinel/issues/255.

> Went through implementing the native Sentinel via the facade, ended up needing illuminate/events and symfony/http-foundation. I did not see this documented anywhere. Would you be open to a PR for just the README for the time being and then further discussion on decoupling the models and repositories?

These are being suggested through Composer, but you are more than welcomed to create a PR to the documentation.
