### ISSUE TITLE
User->inRole error

### ISSUE THREAD

**Issue by farmanalikhan** [cartalyst/sentinel#310]
The inRole function on the user model matches the passed role with the first use role and returns.
It should not return until a match is found or the end of user->roles.

**Comment by brunogaspar** [comment]
It's possible that this is already fixed but not tagged, please try to change your dependency on your `composer.json` file to `"2.0.*@dev"`, run `composer update` and check if the issue still persists.

If the issue still persists, you're more than welcomed to submit a PR with a fix.

**Comment by farmanalikhan** [comment]
Thanks brunogaspar , this issue is fixed in the "2.0.*@dev".

**Comment by brunogaspar** [comment]
Cool. We'll release a new tag very soon.
