### ISSUE TITLE
[Question] Why JSON permissions and not Eloquent relationships?

### ISSUE THREAD

**Issue by Frondor** [cartalyst/sentinel#312]
I've noticed the permissions are stored as a json object in the DB instead of the common `Role/Permissions` practice with `Eloquent` relationships, why is that? 
I don't feel like that's a good practice, although I think its better in terms of performance (unless Eloquent relationships are somehow cache'd, then that's not the case), not sure... I'm confused

**Comment by brunogaspar** [comment]
It was more efficient to store these as json instead of having a has many relation.

If you really want to use relations, you're free to extend Sentinel, i personally never tried nor had any need to use it that way.
