### ISSUE TITLE
Generating permission based on a list of controller methods

### ISSUE THREAD

**Issue by nhg2016** [cartalyst/sentinel#314]
Hi,

Is there a way I can generate a list of permissions for a role based on the methods within a controller?
I am trying to implement an ACL system where controllers are parsed and the methods with specific tags will be extracted and permissions generated.

Any ideas or am I over complicating things?

Thanks

Nhg

**Comment by a3gz** [comment]
There is a way but not within Sentinel of course: you can use PHP's `ReflectionClass' to scan for methods inside each of your controllers.
