### ISSUE TITLE
Documentation issue as a newb

### ISSUE THREAD

**Issue by rikdavis** [cartalyst/sentinel#315]
So, I'm rather new to Laravel and in attempting to follow the documentation on [https://cartalyst.com/manual/sentinel/2.0#native](url) I'm struggling with certain assumptive elements of the instructions,

The code block referenced in this section provides no indication as to where that code lives and I'm embarrassed to admit that since I am so new to Laravel, I don't know what file I would use that code in.

Can you please offer some clarity?

Thanks

**Comment by brunogaspar** [comment]
Hello,

Nothing to be embarrassed of :)

If you're using Sentinel on Laravel, you'll need to follow the instructions to install on Laravel only https://cartalyst.com/manual/sentinel/2.0#laravel-5, the link you mentioned is for usage outside of frameworks.

The rest of the documentation applies pretty much for both, Laravel and native integration.

Let us know if you have any more questions or issues.

Regards.

**Comment by rikdavis** [comment]
Thanks so much for that timely and very informative response. Very appreciated!
