### ISSUE TITLE
Separate migration files

### ISSUE THREAD

**Issue by Whyounes** [cartalyst/sentinel#316]
We do we have all the migrations in one file? It's better to have a separate file to ease modifications?

**Comment by Whyounes** [comment]
Another note. Laravel already have a migration file for the users table, and Sentinel has migration for creating the users table! I think it should `alter` the table and create the necessary DB fields needed

**Comment by brunogaspar** [comment]
> We do we have all the migrations in one file? It's better to have a separate file to ease modifications?

It's fine as is, but you can make separate migration files on your application.

> Another note. Laravel already have a migration file for the users table, and Sentinel has migration for creating the users table! I think it should alter the table and create the necessary DB fields needed

No. You should remove the initial migrations from Laravel. It's stated on the [documentation](https://cartalyst.com/manual/sentinel/2.0#migrations).
