### ISSUE TITLE
Sentinel::authenticate doesn't work.

### ISSUE THREAD

**Issue by favoriabs** [cartalyst/sentinel#317]
I've put in all the configurations i saw on the cartalyst site. I seeded a user and a role and tried to use the `Sentinel::authenticate()` method. Its returning a false. Am not sure what i am doing wrong.
`<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Sentinel;

class AuthenticationController extends Controller
{
      
    public function logIn(Request $request) {
        
        $this->validate($request, [
            'email' => 'required|email',
            'password' => 'required',
            
        ]);
        
        $credentials = [
            'email'    => $request->email,
            'password' => $request->password,
        ];
        
        if($user = Sentinel::authenticate($credentials)) {
            return view ('layouts.main');
        } else {
            echo "NOT A USER";
        }
    }
}`

**Comment by favoriabs** [comment]
Sorted: 
I had encrypted my password in the seeder file. Apparently sentinel doesn't recognized the hashed password. I removed the bcrypt function and everything was fine.

PS:
Still surprised sentinel didn't have this covered.

**Comment by juandelossantos** [comment]
Thanks @favoriabs, after hours l found this Issue post and was the same problem that i had. 👍

**Comment by favoriabs** [comment]
You welcome. Glad it helped.

**Comment by AhmedYacoub** [comment]
after 2 years, I faced the same problem xD

**Comment by FlipsterTaner** [comment]
after another 2 years, I faced the same problem 😅
