### ISSUE TITLE
[Proposal] Save user permissions in separate table

### ISSUE THREAD

**Issue by ahmedbebars** [cartalyst/sentinel#318]
I want o use this package for SAAS application , while architecturing the app , Each User may be in differnet accounts so this would have a conflict with the permissions save on the users table , instead if the permissions are saved in sperate table this will solve the problem becuase will allow the user to have a permission row per each account.

 Steps: 
-Remove permissions from users table 
-Create permissions table as the following (id , user_id . permissions . created_at , updated_at)

This should work in case of using it in single tenant or multi-teant (SAAS)

**Comment by brunogaspar** [comment]
Pretty much the same as https://github.com/cartalyst/sentinel/issues/312 so the recommendation is the same.

**Comment by ahmedbebars** [comment]
@brunogaspar I think you misunderstand me, I see the point for using JSON and I prefer this way as you recommend but the point here is different, as I mentioned earlier the user may have membership with multiple accounts so in the current implementation the permission was saved in the user row so this will effect both account's memberships but if we saved the permissions in different table we can add  another foreign key for the account id let's say
id 
user_id 
permissions => JSON Permissions
created_at
updated_at

Sorry if I can't explain better, but the point not to make each permission as row but to decouple the permissions field from the user's table so can add foreign keys if needed.

**Comment by brunogaspar** [comment]
The suggestion is still the same. For your use case you'll need to extend Sentinel models to use a different table for the permissions, there's no other way around it i believe.
