### ISSUE TITLE
Laravel 5.x EloquentUser should implements Authenticatable

### ISSUE THREAD

**Issue by Cyrille37** [cartalyst/sentinel#320]
Hi,
Thanks a lot for open sourced Sentinel!

In Laravel 5.x, there is the TestCase's trait method `Illuminate\Foundation\Testing\Concerns\ImpersonatesUsers::actingAs( Illuminate\Contracts\Auth\Authenticatable )` that is not compatible with `Cartalyst\Sentinel\Permissions\PermissibleInterface\EloquentUser`.

`Cartalyst\Sentinel\Permissions\PermissibleInterface\EloquentUser`should implements`Illuminate\Contracts\Auth\Authenticatable`.
**Or another solution ?**

Cheers
Cyrille

**Comment by brunogaspar** [comment]
I've the feeling that's incorrect, since Sentinel is not using any Laravel authentication nor they are the same thing.

But will leave for @suwardany to evaluate.

**Comment by Cyrille37** [comment]
Thanks @brunogaspar 

But then, how to use Sentinel logged-in user in TestCase ?
Like:
```
$user = User::where( ['email'=>'admin@internet.com'] )->first();
$this->actingAs( $user )
        ->visitRoute( 'admin.dashboard' )
        ->see('E-mail');
```

**Comment by Cyrille37** [comment]
@brunogaspar I agree that Sentinel does not use any Laravel auth stuff, but it should be compatible with some contracts to permits a smooth Sentinel integration in Laravel ecosystem (others packages & tools). Or perhaps I miss some knowledge...

**Comment by suwardany** [comment]
@Cyrille37 not seeing the point here, as Bruno mentioned, these are two different packages which are not meant to be functioning together in any way.

**Comment by Cyrille37** [comment]
@suwardany I do not talk about Laravel Auth implementation compatibility but about Laravel Auth contract that permits compatibility with other packages...

**Comment by suwardany** [comment]
@Cyrille37 i understand you're talking about the contract, i still don't think this should be part of the sentinel pacakge .. if you really need it, you can override the user model and implement the contract.

**Comment by Cyrille37** [comment]
So, I could not find any idea on how to replace `$this->actingAs( $user )` in Test ?

**Comment by suwardany** [comment]
Check out this wiki page on how to extend sentinel https://github.com/cartalyst/sentinel/wiki/Extending-Sentinel

Just implement the contract on that new user class and you should be able to use it on your tests.

**Comment by Cyrille37** [comment]
Ok. Thanks.

**Comment by andela-tolotin** [comment]
To solve this problem you will have to do 2 things; import the interface and use the trait on the User model
- Illuminate\Auth\Authenticatable;
-  Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;

```
class User extends EloquentUser implements AuthenticatableContract
{
    use Authenticatable;
```

You should be fine afterward.
