### ISSUE TITLE
Bug in checkPermission() method

### ISSUE THREAD

**Issue by alpha-hawk** [cartalyst/sentinel#321]
```php
protected function checkPermission(array $prepared, $permission)
{
    if (array_key_exists($permission, $prepared) && $prepared[$permission] === true) {
        return true;
    }

    foreach ($prepared as $key => $value) {
        if ((str_is($permission, $key) || str_is($key, $permission)) && $value === true) {
            return true;
        }
    }

    return false;
}
```

In case, array of prepared permissions has a 'zero' index this function always returns the value at it. 

Like if there is a 'true' on index zero user will have permission to everything or if there is 'false' on this index user will have no access to anything.

**Comment by brunogaspar** [comment]
I've formatted your post a little bit, so it's more readable.

If you find a way to fix it, feel free to submit a PR.

**Comment by suwardany** [comment]
@alpha-hawk why would a prepared permission have a zero index in the first place?

**Comment by alpha-hawk** [comment]
I understand that, but if due to some unfortunate incident on part of the programmer once a zero has been placed inside the array, all permissions will just collapse. 
As we are dealing with the site permissions here, I think we should handle these kind of issues. It is very easy to place a zero inside the array but it should not affect the whole permissions. 
If you don't find that important please feel free to close the issue.

**Comment by a3gz** [comment]
If a zero index is an undesired condition, then shouldn't the condition be checked before it ever reaches the `checkPermission()` method? 
 
You are assuming that the permission array `[0 => true]` is always undesired, however it would be one possible way to grant super user access to a user. 
In any case, in my opinion, this shouldn't be up to Sentinel to decide whether this condition is acceptable or not. If in any specific application this condition is always unacceptable, then shouldn't it be the application's responsibility to make sure it never occurs?.

**Comment by alpha-hawk** [comment]
I understand that. 
But, don't you think an application should not fall so easily for these kind of errors?

**Comment by a3gz** [comment]
The thing is that it's still to be determined that the specific condition under discussion is in fact an error and even more: an error that can be attributed to Sentinel. 

In my opinion this: `[0 => true]` is as much an error as an array with all possible permissions set to true. 
It's not uncommon to use the value zero to represent infinite or all possible values in a collection. From that point of view, what you call an error might very well be an undocumented feature... discovery of which, you would be the one to thank for!.

**Comment by drsii** [comment]
@alpha-hawk I understand your concern and we'll look to clarify documentation on this for Sentinel 2.

@suwardany make a note to review pros/cons regarding this issue for S3. Our premise has always been for permissions to override and fall back. Circumvention of this behavior from the root node of a permissions array introduces a single point of entry.
