### ISSUE TITLE
Accessing `Snetinel` facade in our web application controller after login through API

### ISSUE THREAD

**Issue by hizbul25** [cartalyst/sentinel#323]
In our web application, we are using API for auth and registration. In the API end we are using Sentinel for authentication and return `user` object as `json` data.
So, in web application end we have user object and we can check user existence upon `$currentUser` session. Problem arise when we try to access `Sentinel::inRole()` in the website end, and system can't find `Snetinel` facade.

So, how can we handle this situation for accessing `Snetinel` facade in our web application controller?

**Comment by brunogaspar** [comment]
> **Note**: Going to assume that you're using Laravel, since you didn't provide this information.

You're most likely not importing the Sentinel facade class properly.

At the beggining of your class file add `use Cartalyst\Sentinel\Laravel\Facades\Sentinel;` and it should work.
