### ISSUE TITLE
migration table reminders miss table->engine like other tables

### ISSUE THREAD

**Issue by Cyrille37** [cartalyst/sentinel#326]
Hi,
Is there a reason or it's just a miss ?
Cheers

**Comment by brunogaspar** [comment]
Seems to be there https://github.com/cartalyst/sentinel/blob/2.0/src/migrations/2014_07_02_230147_migration_cartalyst_sentinel.php#L62

**Comment by Cyrille37** [comment]
Hi.
But not in 2.0.13 https://github.com/cartalyst/sentinel/blob/v2.0.13/src/migrations/2014_07_02_230147_migration_cartalyst_sentinel.php#L54

**Comment by suwardany** [comment]
@Cyrille37 this has been tagged now. `composer update` and you should receive the latest update.
