### ISSUE TITLE
After ran php artisan migrate, getting error.

### ISSUE THREAD

**Issue by mikromika** [cartalyst/sentinel#327]
[Illuminate\Database\QueryException]         
                                                                                     
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key
  length is 767 bytes (SQL: alter table `persistences` add unique `persistences_code_unique`(`code`)) 

- I am follow up video
   https://youtu.be964-xdghBOY?list=PL3ZhWMazGi9KB9PajJHWvV2NJ1ITNoNGp
- I have deleted default migration files for users and password_reset table.
- I have done new clean database with no old tables.
- I have done migrate command few times for clean database and it fails each time for same error.

Any Ideas ?

Thanks Mikromika-

**Comment by brunogaspar** [comment]
Hi,

Please see my comment [here](https://github.com/cartalyst/sentinel/issues/324).

**Comment by mikromika** [comment]
Thanks.
