### ISSUE TITLE
Documentation page is down

### ISSUE THREAD

**Issue by underdpt** [cartalyst/sentinel#329]
Hi,

For a few days now, manual seems to be down. Either it shows a the manual without styling, or throws a 403 forbidden error.

Also, this seems to affect all https://cartalyst.com/. I can open cartalyst.com, then go to the manual, get a 403 error,, and when going back to cartalyst.com, it also throws a 403 error.

**Comment by suwardany** [comment]
This should be fixed, give it another try and let me know if you're still having issues @underdpt

**Comment by underdpt** [comment]
Thanks!
