### ISSUE TITLE
Email-Change and send Reminder: Users can't login while not activated

### ISSUE THREAD

**Issue by sugo23** [cartalyst/sentinel#331]
I found this problem:

When I allow the users to change their email addresses, I have to send a Reminder, so they have to reactivate their account.

The problem is, that after that, they cannot login anymore (till the account is activated again). So when a user has a typo in his new email address, he is locked out..

I guess for now one has to change how Sentinel deals with Reminders. Is that possible without touching the Sentinel core code?

**Comment by brunogaspar** [comment]
@sugo23 You'll most likely need to [Extend Sentinel](https://github.com/cartalyst/sentinel/wiki/Extending-Sentinel) and modify the logic you need, either on the models or on the repositories.

Other solution would be to create a custom Activation checkpoint, that way you can still allow the users to login after they change the email address, but maybe show limited functionality.

**Comment by drsii** [comment]
@sugo23  We assume the question has been answered, feel free to reopen if necessary. otherwise code well, rock on!

@suwardany add note to review our default reminder workflow for Sentinel 3 to decide if we want to make any changes here.
