### ISSUE TITLE
How can i use correctly remember me

### ISSUE THREAD

**Issue by jscavazos** [cartalyst/sentinel#335]
Im trying to use this feature but i just cant know how to implement it since there is no documentation about this.

i know i need to set remember me as true when i authenticate but then what i need to do for the user not need to write his username and/or password again to login.

could someone help me? please

**Comment by brunogaspar** [comment]
Just create a checkbox input called remember-me for example that contains the value of 1 and when logging the user in, you retrieve that checkbox value and use that on the Sentinel authenticate method.

If that's not it, just elaborate a bit more on what you're having problems with by providing the code that you currently have.

**Comment by jscavazos** [comment]
Thank you for answer, well what i mean is that i do all u are saying, i have my checkbox on login page and when the user log in, i use Sentinel::login($user, true) then in my code this redirect to my home page with a welcome message and my username all works perfectly, i actually send true as second parameter in Sentinel::login because all i want to know is if when the user log out and want to log in again how can i get the cookie that have his information to fill the input "username" and "password" so user does not need to write again his account and password cause he is using the "remember me" feature

hope you can understand me if not, i can provide my code but is working well im just dont know how i can get the username value and passwrod value so the user dont need to write again in the next log in if he is using remember me

**Comment by chrisbjr** [comment]
hi @brunogaspar would also like to know how long the "remember" flag will remember the session. Can't seem to find documentation on that anywhere. Thanks!
