### ISSUE TITLE
Native Sentinel: My User Model never used by Sentinel

### ISSUE THREAD

**Issue by kavin-90** [cartalyst/sentinel#336]
I'm using Native Sentinel but My Eloquent user model never used when i use. 

**`Sentinel::getUserRepository()->setModel('User');`**

I don't need namespace because User model does not need namespaces to use.

It use own Model until i didn't change config file of Sentinel.

**Comment by suwardany** [comment]
@kavin-90 check my comment here https://github.com/cartalyst/sentinel/issues/263#issuecomment-233057343

It should address your issue.
