### ISSUE TITLE
How to get all user 

### ISSUE THREAD

**Issue by leezene** [cartalyst/sentinel#337]
how do i get all the registered user on the system 

`$users` = Sentinel::getUser();
    	return view('admin.userlist',compact('users'));

**Comment by brunogaspar** [comment]
Something like this

```php
$users = Sentinel::getUserRepository()->get();
```

**Comment by leezene** [comment]
and how to show the roles of the users.

**Comment by brunogaspar** [comment]
Try with `$users = Sentinel::getUserRepository()->with('roles')->get();`

It's pretty much [Laravel Eloquent](https://laravel.com/docs/5.1/eloquent).

**Comment by leezene** [comment]
when i want to show the role 
`{{$users->roles->name}}`
it show the error.

> Property [name] does not exist on this collection instance. (View: C:\Users\Joker-PC\Desktop\pw\resources\views\admin\userlist.blade.php)

**Comment by brunogaspar** [comment]
Since a user can have as many roles, you'll need to loop through the roles and then display the role name.

**Comment by drsii** [comment]
We assume the question has been answered, @leezene feel free to reopen if necessary. Code well, rock on!

**Comment by Kehbas** [comment]
hello guys, 
I have the sme problem as @leezene  and I dont understand what @brunogaspar  meant with "loop through the roles" can anyone help? 

I'm working on a platform with many roles and I would like to make a admin panel to set roles.
Thank you,

**Comment by brunogaspar** [comment]
@Kehbas 

If it's to show all the users and the roles they are assigned to, you'll need to iterate through the users first and then inside create another loop to iterate through the user roles:

```php
// Get all the users
$users = Sentinel::getUserRepository()->with('roles')->get();

// Loop through the users
foreach ($user as $user) {
    // Loop through this user roles
    foreach ($user->roles as $role) {
        echo $role->name;
    }
}
```

If it's to show only the available roles:

```php
// Get all the roles
$roles = Sentinel::getRoleRepository()->get();

// Loop through the roles
foreach ($roles as $role) {
    echo $role->name;
}
```

Hope it makes sense.

**Comment by Kehbas** [comment]
@brunogaspar thank you so much for your time! It work perfectly Ive never done a loop inside a loop..
Cheers

**Comment by Tekken-Army** [comment]
To get it from a specific id use:

$user = Sentinel::findById(2);
        $user->inRole('admin');
        foreach($user->roles as $role){
            echo $role->name;
        }

**Comment by Tekken-Army** [comment]
Also if you don't know the role slug

$user = Sentinel::findById(2);
        $user->inRole('*');
        foreach($user->roles as $role){
            echo $role->name;
        }
