### ISSUE TITLE
How implements select with roles. Change it updated?

### ISSUE THREAD

**Issue by majweb** [cartalyst/sentinel#339]
I have question How You implemets roles i selectbox update and selected?

**Comment by majweb** [comment]
I use getRolerepository->get() as $roles variable and use foreach in select option tag but I see all roles i want see role selected by User and i want changed and updated role. Laravel 5.4.

**Comment by brunogaspar** [comment]
As far as i know you'll need to pass the current user roles as the 3rd argument on the `Form::select` method.

If that doesn't work you'll need to create an issue on the Laravel Collective repository as this is not an issue on Sentinel.
