### ISSUE TITLE
verify the permissions on blade ?

### ISSUE THREAD

**Issue by ayubDev** [cartalyst/sentinel#340]
Hi Guys 

I have a question about how can I verify the permissions on blade ?

**Comment by brunogaspar** [comment]
Please elaborate on what you're trying to achieve.

**Comment by ayubDev** [comment]
I wanna find out the functions I can to use in blade to verify the permissions , for example in controller we do this : `
```
if ($user->hasAccess(['user.create', 'user.update']))
{
    // Execute this code if the user has permission
}`
```

**Comment by brunogaspar** [comment]
You can use pretty much everything, just update to blade syntax.

**Comment by ayubDev** [comment]
could you please give me an example?

**Comment by brunogaspar** [comment]
Pretty much

```
@if ($user->hasAccess(['user.create', 'user.update']))
Execute this code if the user has permission
@endif
```

> Considering that you're passing the `$user` variable to the Blade view.

[Laravel documentation](https://laravel.com/docs/5.1/blade#control-structures) covers it all.

**Comment by ayubDev** [comment]
ah thank you friend
