### ISSUE TITLE
how senstinel do encrypt user password

### ISSUE THREAD

**Issue by knour89** [cartalyst/sentinel#342]
i want to know the function you are using to encrypt password

**Comment by drsii** [comment]
https://cartalyst.com/manual/sentinel/2.0#hashing

**Comment by knour89** [comment]
i cant understand it, if i need to has 1234 what should i do?

**Comment by vijayrana-me** [comment]
I also want to know how to hash password, so that i can manually hash when needed. Did you find any solution?
