### ISSUE TITLE
Laravel 5.4 Support

### ISSUE THREAD

**Issue by pankitgami** [cartalyst/sentinel#344]
@brunogaspar As Laravel 5.4 is released, are you guys working on upgrade to 5.4?

**Comment by drsii** [comment]
Are you experiencing issues?

**Comment by pankitgami** [comment]
@drsii I am starting a new application. So I was checking whether you are working on upgrade or not. If you want, I can have a look at it and let you know.

**Comment by drsii** [comment]
You should be good to go. Cartalyst Platform 7 was released a couple weeks ago for Laravel 5.4 https://platform.cartalyst.com which uses Sentinel.

**Comment by brunogaspar** [comment]
It already has support for Laravel 5.4.

If you encounter any issues, just open a new ticket per issue.
