### ISSUE TITLE
php artisan platform:install gives pdo exception error

### ISSUE THREAD

**Issue by highnoon112** [cartalyst/sentinel#345]
after playing a bit with sentinel Ive decided to go for a fresh install of Platform. 

Ive gone trough the installation process through git bash and eventually get below shown pdo exception error. Ive also tried the browser install but the page looks like this: 

https://uploadpie.com/GH6a5T

I cant accept the terms and installing Platform through the  browsers gives me the same error as shown below.

Currently it looks like I cant access Platform pages like the admin dashboard. 

Thanks

`  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1055 'platform.node.slug' isn't in GROUP BY (SQL: select `node`.*, (count(`parent`.`id`) - (`sub_tre
  e`.`depth` + 1)) as `depth` from `menus` as `node` inner join `menus` as `parent` on `node`.`lft` >= `parent`.`lft` inner join `menus` as `sub_parent`
  on `node`.`lft` >= `sub_parent`.`lft` inner join (select `node`.`id`, (count(`parent`.`id`) - 1) as `depth` from `menus` as `node` inner join `menus` a
  s `parent` on `node`.`lft` >= `parent`.`lft` where `node`.`lft` <= `parent`.`rgt` and `node`.`id` = 1 and `node`.`menu` = 1 and `parent`.`menu` = 1 gro
  up by `node`.`id` order by `node`.`lft` asc) as `sub_tree` on `sub_parent`.`id` = `sub_tree`.`id` where `node`.`lft` <= `parent`.`rgt` and `node`.`lft`
   <= `sub_parent`.`rgt` and `node`.`id` != 1 and `node`.`menu` = 1 and `parent`.`menu` = 1 and `sub_parent`.`menu` = 1 group by `node`.`id`, `sub_tree`.
  `depth` order by `node`.`lft` asc)

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1055 'platform.node.slug' isn't in GROUP BY

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1055 'platform.node.slug' isn't in GROUP BY`

**Comment by suwardany** [comment]
Hello @highnoon112 .. this is actually related to Platform not Sentinel.

Check https://github.com/cartalyst/platform/issues/314

**Comment by highnoon112** [comment]
Thanks for the incredible fast answer. Bit pity Ive lost half a day figuring out what I did wrong. Ill blame it on my unsufficient laravel knowledge. 

Have a nice day

**Comment by suwardany** [comment]
Always welcome, @highnoon112 !

Have a great day.
