### ISSUE TITLE
how i can retrive the realtion between users table and activations table?

### ISSUE THREAD

**Issue by knour89** [cartalyst/sentinel#347]
how i can retrive value of completed column in activation table for users and for specific user also

**Comment by brunogaspar** [comment]
Hi,

This is covered on the [activations documentation](https://cartalyst.com/manual/sentinel/2.0#activation).

**Comment by knour89** [comment]
i know its in documentation, but i want to retrieve the relation in on recorded for exable
first name | last name | email | activation code| activation complted

**Comment by brunogaspar** [comment]
You'll most likely need to do a manual query as this is not really related to Sentinel.

If you're stuck you can refer to the Laravel documentation.
