### ISSUE TITLE
Laravel 5.4 Vendor Publish Doesnt Work

### ISSUE THREAD

**Issue by cagatayoncul** [cartalyst/sentinel#349]
In Laravel 5.4 doesnt work publish command. Any fix ?

`php artisan vendor:publish --provider="Cartalyst\Sentinel\Laravel\SentinelServiceProvider"`

**Comment by arkid** [comment]
Did you resolve this @cagatayoncul  ?  I seem to have had the exact same issue.

**Comment by brunogaspar** [comment]
@arkid Just make sure that you have the Sentinel Service Provider added on the `providers` array on the `config/app.php` file, otherwise it will not work.

**Comment by cagatayoncul** [comment]
ohh sure i solved this i forgot the close issue

**Comment by DaKeZhang7412** [comment]
can you share how did you solve your problem? I have the same one. and I did add Sentinel service provider on the providers array on the config/app.php. 

but, it still didnt see any file get copied

**Comment by brunogaspar** [comment]
@DaKeZhang7412

What's the output when you run the command?
Are you seeing any error?
Do you have the config cached?

**Comment by DaKeZhang7412** [comment]
It says "publishing complete." but didn't see any file get copied(ex, migration file, and config file)

**Comment by brunogaspar** [comment]
Not sure, i'm not able to reproduce any issue

```
php artisan vendor:publish --provider="Cartalyst\Sentinel\Laravel\SentinelServiceProvider"
Copied Directory [/vendor/cartalyst/sentinel/src/migrations] To [/database/migrations]
Publishing complete.
```

**Comment by DaKeZhang7412** [comment]
Thx @brunogaspar 
I guess I have to manually copy those file I need. 
BTW, when Sentinel publish, dose it create any model file(ex. roles, etc.)

**Comment by brunogaspar** [comment]
@DaKeZhang7412 

It only publishes the config file and the migrations.

If you need to customise how the default models behave and such, you can [extend](https://github.com/cartalyst/sentinel/wiki/Extending-Sentinel) Sentinel.

**Comment by MohamedHana** [comment]
# Follow these steps:
1- Add service provider to providers array on the config/app.php
2- Run  **php artisan config:cache** 
3- Run **composer update**
4- Run  **php artisan config:cache**  
5- Run **php artisan vendor:publish**

**Comment by davido242** [comment]
Take this recent update for 29th September, 2021 by running the following on php container:
1-php artisan config:cache
2-php artisan cache:clear
3-php artisan clear-compiled
4-composer dumpautoload
5-finally you can run your vendor:publish --provider="whatever...........whever and more"
