### ISSUE TITLE
cant use Authentication method / Authentication method error

### ISSUE THREAD

**Issue by knour89** [cartalyst/sentinel#350]
hello i am trying to use Authentication method and it show me error

```
UnexpectedValueException in Response.php line 444:
The Response content must be a string or object implementing __toString(), "boolean" given

```

I even tried to use exmable in web site and get same error

```
$credentials = [
    'email'    => 'john.doe@example.com',
    'password' => 'password',
];

Sentinel::authenticate($credentials)

return Sentinel::check();
```

**Comment by brunogaspar** [comment]
Hello

The exception is pretty much self explanatory, it expects a string but you're returning a boolean.

That's caused by your `return Sentinel::check();`.
