### ISSUE TITLE
ajax call Sentinel::check() and Sentinel::getUser() always return null

### ISSUE THREAD

**Issue by hbsoftco** [cartalyst/sentinel#354]
Hi
I'm using Sentinel package, Everything is fine, But when I want call Sentinel::check() and Sentinel::getUser() using ajax, it return null. help me please :(

my route in api.php
`Route::post('/managersShowMarkers', 'ManagerController@managersShowMarkers');`

managerShowMarkers method in ManagerController
`public function managersShowMarkers()
    {
        $currentUser = Sentinel::getUser();
        $my_id = $currentUser->id;
        $markers = MapLocation::where('code_shahrestan', $my_id)->get();
        return $markers;
    }`

jquery and ajax
`var map;
var marker;

jQuery(document).ready(function () {

    var latval = 37.4714526;
    var lngval = 57.320;

    console.log([latval, lngval]);

    myLatLng = new google.maps.LatLng(latval, lngval);

    createMap(myLatLng);

    // Create Map
    function createMap(myLatLng) {
        map = new google.maps.Map(document.getElementById('mymap'), {
            center: myLatLng,
            zoom: 14
        });

        setMarkers(map);

    }

    function setMarkers(map) {

        $.post(
            'http://localhost:8000/api/managersShowMarkers',
            {vaz: 'ok'},
            function (match) {
                console.log(match);

                $.each(match, function (i, val) {

                    var glatval = val.lat;
                    var glngval = val.lng;

                    var gname = val.address;
                    var status = val.status;
                    var shahrestan = val.shahrestan;
                    var code = val.code_keshvari_shobe;
                    var shahr_rousta = val.shahr_rousta;

                    // console.log(status);
                    var gicn;
                    if (status == 'آنلاين') {
                        gicn = 'storage/uploads/onlineFlag.png';
                    }
                    else if (status == 'آفلاين') {

                        gicn = 'storage/uploads/offlineFlag.png';

                    } else {

                    }

                    marker = new google.maps.Marker({
                        position: {
                            lat: parseFloat(glatval), lng: parseFloat(glngval)
                        },
                        map: map,
                        icon: gicn,
                        title: gname
                    });

                    var infoWindow = new google.maps.InfoWindow(), marker, i;

                    google.maps.event.addListener(marker, 'click', (function (marker, i) {
                        return function () {
                            infoWindow.setContent('<div class="font-iran scrollFix gmap-info">کد شعبه:' + code + '</div><div class="font-iran scrollFix gmap-info">' + shahrestan + '</div><div class="font-iran scrollFix gmap-info">' + shahr_rousta + '</div><div class="font-iran scrollFix gmap-info">' + gname + '</div>');
                            infoWindow.open(map, marker);
                        }
                    })(marker, i));

                });

            });
    }});

**Comment by brunogaspar** [comment]
What Laravel version are you using?

**Comment by hbsoftco** [comment]
laravel 5.3

**Comment by brunogaspar** [comment]
Is that route you posted using the `web` middleware?

**Comment by hbsoftco** [comment]
I did not use a middleware

this is my code in api.php
<?php

use Illuminate\Http\Request;

Route::get('/user', function (Request $request) {
    return $request->user();
})->middleware('auth:api');

Route::post('/showMarkers', 'MapLocationsController@showMarkers');

Route::post('/managersShowMarkers', 'ManagerController@managersShowMarkers');

**Comment by brunogaspar** [comment]
You'll need to use the `web` middleware as well i'm afraid, otherwise you'll not be able to get the logged in user i suppose since the API routes are stateless.

**Comment by hbsoftco** [comment]
thanks for replay, but it's not working with `web` middleware :(

**Comment by brunogaspar** [comment]
Is it working as expected without being an Ajax request?

**Comment by hbsoftco** [comment]
Yes, it's working correctly

**Comment by brunogaspar** [comment]
So something on those routes are not correctly setup.

Therefore i believe it's not a Sentinel issue since it's working as expected in the rest of your application.

**Comment by joginder89** [comment]
@hbsoftco Do you able to solve this problem ? I am facing same problem.

**Comment by hbsoftco** [comment]
@joginder89  I used another way.
First add user's info into a session
`Session::put('city_id', $currentUser->city_id);`
then goto app/Http/Kernel.php and active session on rest api routes
`
'api' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Session\Middleware\StartSession::class,
            'throttle:60,1',
            'bindings',
        ],
`
