### ISSUE TITLE
[Question] How to manually login a user ?

### ISSUE THREAD

**Issue by joginder89** [cartalyst/sentinel#355]
I use `Sentinel::loginAndRemember($user);` inside a Controller to manually login a user. Then in same function I used `Sentinel::getUser()` to check if User is logged in, It print the user details. But when I move to another page (like login to home) their `Sentinel::getUser()` print `null` . Is their any other method to manually login a user ?

**Comment by brunogaspar** [comment]
What Laravel version?

**Comment by joginder89** [comment]
`"laravel/framework": "5.4.*",`
`"cartalyst/sentinel": "^2.0",`

**Comment by brunogaspar** [comment]
Make sure that your routes are using the web middleware as mentioned on the Laravel documentation.

**Comment by joginder89** [comment]
I do not find web middleware, I have written my routes in roures/web.php files.

**Comment by pankitgami** [comment]
You can check whether a user is logged in or not before calling `Sentinel::getUser()` using `Sentinel::check()`. If `Sentinel::check()` returns false means your user is not logged in. There could be a problem with your session.

**Comment by joginder89** [comment]
@pankitgami  `Sentinel::check()` return false at home page but it return true in postLogin Controller. Let me find out the session problem.

**Comment by brunogaspar** [comment]
The `web` middleware is set [here](https://github.com/laravel/laravel/blob/master/app/Http/Kernel.php#L29) and used by default [here](https://github.com/laravel/laravel/blob/master/app/Providers/RouteServiceProvider.php#L54).

You'll need to have this to make sessions work as expected on your application.

**Comment by joginder89** [comment]
I try to add 3rd party login (like facebook or gmail) in app, I just create user and use

`$user = User::where('uid', $uid)->first();
Sentinel::login($user);
Redirect::route("/");`

then at home page I used

`
@if(Sentinel::check())
     You are Login
 @else
     You are not Login
@endif
`
it print You are not Login.

**Comment by brunogaspar** [comment]
If you're still having this issue, let me know and i'll reopen and will try to determine what might be wrong as i don't seem to be able to reproduce this.
