### ISSUE TITLE
Testing login session with Behat

### ISSUE THREAD

**Issue by wout** [cartalyst/sentinel#358]
I am testing an XML and JSON REST API with Behat. For authentication, I use Sentinel. Now, if I log in a user through Behat, and I test the status of the login session, the API returns a negative response (e.g. user not logged in). When I do the exact same thing manually in a browser using AJAX requests, everything works fine. So the end result is fine but the scenario fails. Any suggestions on how to overcome this issue?

Might this have something to do with the login session initiated from a CLI client rather than a browser?

**Comment by wout** [comment]
I included more info on the Stackoverflow issue:
http://stackoverflow.com/questions/43479251/testing-login-session-with-behat

**Comment by drsii** [comment]
@wout Closing question as unsolved. Please fill free to reopen should have more to add or have found a solution.
