### ISSUE TITLE
Cannot instantiate Interface (Native)

### ISSUE THREAD

**Issue by Fergall** [cartalyst/sentinel#359]
Hello!

im trying to run Sentinel Native and im having a problem

```
//here is located the autoload.php
require_once("configuraciones/include.cfg.php");

use Cartalyst\Sentinel\Native\Facades\Sentinel;
use Illuminate\Database\Capsule\Manager as Capsule;

// Setup a new Eloquent Capsule instance
$capsule = new Capsule;

$capsule->addConnection([
    'driver'    => 'mysql',
    'host'      => 'host',
    'database'  => 'db',
    'username'  => 'user',
    'password'  => 'secret'
]);

$capsule->bootEloquent();

$sentinel = (new Sentinel())->getSentinel();
    
// Register a new user
Sentinel::register([
    'email'    => 'test@example.com',
    'password' => 'foobar',
]);
```
But so far i get
`Fatal error: Cannot instantiate interface Illuminate\Contracts\Events\Dispatcher in /var/www/canal_de_denuncias/admin/bibliotecas/sentinel/vendor/cartalyst/sentinel/src/Native/SentinelBootstrapper.php on line 317`

I downloaded through composer with the next json:
```
{
    "require": {
        "cartalyst/sentinel": "2.0.*",
	"illuminate/database": "5.*.*"
    }
}
```

Hope you can help me, thanks!

**Comment by drsii** [comment]
@Fergall were you able to figure out the issue?

**Comment by vkathirvel** [comment]
@Fergall @drsii 
I had to add "illuminate/events" and "illuminate/http" to my composer.json. Looks like these are not being loaded by Sentinel upon install. Any idea why it is under require-dev and not require?
https://github.com/cartalyst/sentinel/blob/2.0/composer.json

**Comment by sabas** [comment]
I am using native and these are my relevant requires
```
"cartalyst/sentinel": "2.0.*",
"illuminate/database": "~5.0",
"illuminate/events": "^5.2",
"symfony/http-foundation": "^3.0",
"illuminate/config": "^5.2",
```

And the php
```
use Cartalyst\Sentinel\Native\Facades\Sentinel;
use Illuminate\Database\Capsule\Manager as Capsule;

$config = new Cartalyst\Sentinel\Native\ConfigRepository('src/customSentinelConfig.php');
$bootstrapper = new Cartalyst\Sentinel\Native\SentinelBootstrapper($config);
Sentinel::instance($bootstrapper);
```

**Comment by sarim** [comment]
Calling this framework agnostic is kinda wrong. I also tried this seeing the tagline but after finding out about these dependencies, no thanks.
