### ISSUE TITLE
user_id is always null in sessions table

### ISSUE THREAD

**Issue by aleemb** [cartalyst/sentinel#360]
The `user_id` column is always null, the other columns are correct. Is there something I am missing or is this Sentinel behaviour?

**Comment by drsii** [comment]
@aleemb If you're still having issues please us know a bit more information and we'll reopen. Which table are you talking about here?

**Comment by aleemb** [comment]
The Laravel's default `sessions` table has a `user_id` column which was always being populated with `null`. The other info was being populated correctly.

This is somewhat related to #136 and #328 where the [workaround](https://github.com/cartalyst/sentinel/issues/328#issuecomment-281779639) seems to be to call `app->rebinding` and then `setUserResolver`. There are some other references as well

 *  http://stackoverflow.com/questions/39488871/laravel-sessions-table-user-id-always-null/39497803#39497803
* https://gist.github.com/brunogaspar/494903b3dd16321a12d1

I think it should be done in the Laravel driver within Sentinel to make it easy for users. The suggestions above are all different. The one that actually worked for me was to set `Auth::setUser` in the middleware after `Sentinel::check` passes

**Comment by aleemb** [comment]
@drsii not sure if I was meant to ping you since this  is a closed issue.
