### ISSUE TITLE
Cannot authenticate with Laravel 5.4 and Sentinel 2.0.15

### ISSUE THREAD

**Issue by Vortelf** [cartalyst/sentinel#361]
Hello,
I'm having this issue where I can't seem to be able to login anymore.
This is my authenticate function
```
public function Authenticate(LoginRequest $request)
{
	try {
		if ($response = Sentinel::authenticate($request->only('username', 'password'), false)) {
			return Redirect::action('Administration@MakeRequest');
		} else {
			return Redirect::action('User@Login')->withErrors("Wrong info.");
		}
	} catch (\Cartalyst\Sentinel\Checkpoints\ThrottlingException $ex) {
		return Redirect::action('User@Login')->withErrors("Too many attempts");
	}
}
```
Worked fine with Laravel 5.3 and Sentinel 2.0.12

**Comment by brunogaspar** [comment]
> I'm having this issue where I can't seem to be able to login anymore.

What is the issue?

**Comment by brunogaspar** [comment]
My only guess, is that you're passing `username` and the User model is still using the default `email` column for the authentication + the `password`.

**Comment by Vortelf** [comment]
As I said, it was working before I decided to update it. That is not the problem.

**Comment by brunogaspar** [comment]
I just tried on a completely fresh Laravel 5.4 installation and with your code it doesn't work until i modify the login column to be username [here](https://github.com/cartalyst/sentinel/blob/2.0/src/Users/EloquentUser.php#L72).

To properly extend Sentinel you can check this [quick tutorial](https://github.com/cartalyst/sentinel/wiki/Extending-Sentinel) and you can then change the login column to be `username` instead of `email`.

**Comment by Vortelf** [comment]
> I just tried on a completely fresh Laravel 5.4 installation and with your code it doesn't work until i modify the login column to be username here.

I did that when I started my project a year ago. It is defined in my model.

**Comment by brunogaspar** [comment]
Not really sure what might be wrong on your end..

Do a little debugging.. add a `dd(config('cartalyst.sentinel.users.model'));` on your login method and see what it returns.

Also add a `dd($loginNames);` on line 93 or 94 on the [IlluminateUserRepository](https://github.com/cartalyst/sentinel/blob/2.0/src/Users/IlluminateUserRepository.php#L93) and also see what it returns.

If everything returns the expected values, which is your own model and then the `username` column from the repository, then something else, which seems unrelated to Sentinel, is not working as expected.

If one of the above doesn't return the expected value, we need to figure out why that's happening.

But as i mentioned, with a very fresh Laravel 5.4 installation it's working as expected.
We also have other applications on 5.4 that were updated from 5.1 to 5.4 and they are working as well.

**Comment by Vortelf** [comment]
```
use Cartalyst\Sentinel\Users\EloquentUser as SentinelUser;


class User extends SentinelUser
{
	protected $loginNames = ['username'];
        ...
}
```
Apparently this doesn't seem to work.
Whenever I replace it in `Cartalyst\Sentinel\Users\EloquentUser.php` it works as intended, but it won't work from the model anymore.

**Comment by brunogaspar** [comment]
What does `config('cartalyst.sentinel.users.model');` return?

**Comment by Vortelf** [comment]
It returns `"\App\User"`.

**Comment by alhassansumon** [comment]
How the problem cartalyst sentinel install laravel 5.4
please help me......!
