### ISSUE TITLE
Problem with finding role with findRoleById( )

### ISSUE THREAD

**Issue by maranovot** [cartalyst/sentinel#362]
Hello, I am using Sentinel in my laravel application and everything is working fine except if I want to find and delete role like this:
```
$role = Sentinel::findRoleById($id) -> delete();
```
I get this error which puzzles me, but I hope it won't puzzle you:
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'role_id' in 'where clause' (SQL: select * from `users` where `role_id` = 5 and `users`.`deleted_at` is null limit 1)
```
So if anyone would be kind enough to clarify what is going on, I would much appreciate it.

**Comment by drsii** [comment]
@maranovot can you set the role object first. Want to separate the possible errors out here.

```
$role = Sentinel::findRoleById($id);
$role->delete();
```

The sql error there i'm guessing is the result of another issue. Unless you actually do not have that column on the users table.

**Comment by brunogaspar** [comment]
Not being able to reproduce this.

Will need more information, like:
- Laravel version if applies;
- Sentinel version;
- Database Engine & version;
- What does the `$role` return if you remove the `->delete()` part?

**Comment by drsii** [comment]
Thats one way to humblebrag about our support.

**Comment by maranovot** [comment]
@drsii 
I separated it as you suggested it returns the role just fine, so the problem must be with the delete part. And I do not have that column on my users table, that's why I asked for clarification because I don't know why is it looking for that column in first place. Do I need an extra role_id column on users table in order to delete roles?

@brunogaspar 

1. Laravel version 5.4.21
2. Cartalyst version 2.0.15
3. InnoDB engine, MySQL is 5.6.35
4. $role returns the role as it should

Hope this helps, thanks.

**Comment by maranovot** [comment]
Sorry my blunder, already fixed it. It had nothing to do with Sentinel.
