### ISSUE TITLE
getUser() function with relations data

### ISSUE THREAD

**Issue by vijay-kumar-rana** [cartalyst/sentinel#364]
I know that `Sentinel::getUser()` get the logged in user detail. But, I have a different condition. I have `name, email, and password` in user table and other information about user in `user_detail` table where `user_table ` have field `user_id` which points to id of user table(foreign key). 

I want to load both user table with eager loading user_detail table. Simply, eloquent ways is as:

`App\Models\User::find($id)->with('user_detail')`

How can I achieve it using sentinel way. 
`Sentinel::getUser()->with('user_detail') `
doesn't seem to work

**Comment by brunogaspar** [comment]
You'll need to call `load()` instead of `with()` in this situation.

Hope it helps.

**Comment by vijay-kumar-rana** [comment]
Yes it works great. Thank you
