### ISSUE TITLE
Is there any demo app using sentinel ?

### ISSUE THREAD

**Issue by babind** [cartalyst/sentinel#365]
I was wondering whether the social authenticated provided by the Sentinel is free service? Or Do we have to pay for it?

**Comment by babind** [comment]
https://cartalyst.com/manual/sentinel/2.0 states that its paid service

**Comment by drsii** [comment]
We offer two paid products.

A simple kickstart app. https://demo.cartalyst.com/sentinel-kickstart/

And our more advanced Cartalyst Platform. https://platform.cartalyst.com/

Both are included in a $75/quarter subscription with no obligation to stay subscribed unless you want updates and support.

**Comment by babind** [comment]
could we still use the sentinel for free for social login?

**Comment by drsii** [comment]
@babind Sentinel Social is paid library. If you do not need to advanced features of sentinel I believe Laravel 5 has it's own auth library for 3rd party services.

**Comment by wakawakapogsSr** [comment]
https://www.youtube.com/watch?v=GqRqlvgByNk&list=PL3ZhWMazGi9KB9PajJHWvV2NJ1ITNoNGp
