### ISSUE TITLE
Can't get sentinel to work with setModel at runtime (Extending Sentinel)

### ISSUE THREAD

**Issue by mdixon18** [cartalyst/sentinel#367]
I am attempting to use the setModel function in runtime in the latest version of Laravel like this:

`Sentinel::getUserRepository()->setModel('App\Client');`

Then call methods such as `Sentinel::getUser();`, However, i am finding that when i do this, its accessing the original 'users' table and not the clients table which is represented when i do `Sentinel::getUserRepository()`.

Its like i can login when i use the setModel function, the authenticate works fine and accesses the clients table, but when i use `getUser()` or `check()` even though it says the user repository is `App\Client` it doesn't work.

I've posted a stackoverflow to show more on this:

[https://stackoverflow.com/questions/44348872/laravel-sentinel-setmodel-accessing-the-wrong-table](https://stackoverflow.com/questions/44348872/laravel-sentinel-setmodel-accessing-the-wrong-table)

**Comment by brunogaspar** [comment]
Hi

Please let us know some more information so we can try to debug the issue a bit better:

- What Laravel version?
- What Sentinel version?
- When exactly, on your routes file, are you setting the user model?

**Comment by mdixon18** [comment]
Hello,

cartalyst/sentinel: 2.0.*
laravel/framework: 5.4.*

I run the call at the top of my routes file, i have also tried it in the AppServiceProvider with the same issue. The authenticate method works beautifully, if i `dd()` out the response it is perfect and it logs me in with the correct user. Upon redirection it is going back to the other model (User) and picking the user out of the incorrect table.

So far its `getUser()` and `check()` i'm struggling with.

Thanks

**Comment by brunogaspar** [comment]
Thanks.

I'll have a look as soon as possible.

**Comment by mdixon18** [comment]
Thank you, keep me posted 👍

**Comment by mdixon18** [comment]
Any news on this yet?

**Comment by brunogaspar** [comment]
Hello

You'll need to also define the model on the persistence repository:

```php
Sentinel::getPersistenceRepository()->setUsersModel('App\Client');
```

I've updated the wiki to mention this as well.
