### ISSUE TITLE
Getting list of users with two different roles (admin & support) in the same array.

### ISSUE THREAD

**Issue by awardx** [cartalyst/sentinel#371]
If I use the following code

$role = Sentinel::findRoleById(1);
$users = $role->users()->with('roles')->get();

I can get only one set of users (i.e. admin or support) per request, but I'd like to have all users with either role in the same bucket.

How can I achieve that?

**Comment by brunogaspar** [comment]
You can try something like the following which is nothing more than Laravel Eloquent queries:

```php
$users = Sentinel::getUserRepository()
    ->with('roles') # Can be removed if you don't want eager loading
    ->whereHas('roles', function ($query) {
        $query->whereIn('id', [1, 2]);
    })
    ->get()
;
```

> **Note:** The `1` and `2` are role ids. You can use whatever you prefer like the roles slug and you can also add more role id's into the array.
