### ISSUE TITLE
Sentinel::check() returns false inside constructor.

### ISSUE THREAD

**Issue by nijesh-wiredelta** [cartalyst/sentinel#372]
`public function __construct(){
        if (Sentinel::check()){
            $current_user = Sentinel::getUser();
            $user = Sentinel::findById($current_user->id);
            $credentials = [
                'lastActiveTime' => date('Y-m-d H:i:s'),
                'ip_address'=>$this->getIpAddress()
            ];
            $user = Sentinel::update($user, $credentials);
            return View::share(array('settings'=>$settings,'current_user'=>$current_user));
        }else{
            echo "logged off<br>";
        }`
Sentinel::check() inside constructor always returns false, working properly within function
Laravel Version 5.4

**Comment by suwardany** [comment]
Check https://github.com/cartalyst/sentinel/issues/280#issuecomment-249587197
