### ISSUE TITLE
how to get logged in user in sentinel ?

### ISSUE THREAD

**Issue by babind** [cartalyst/sentinel#373]
I want to access Sentinel::getUser()->id inside a laravel controller . Therefore i could do like $input["user_id"] $model= Model::create($input);

**Comment by brunogaspar** [comment]
If the user is logged in you can call `Sentinel::getUser()->id` to retrieve the user id.

**Comment by SharmaTushar** [comment]
Deprecation Warning: Sentinel::getUser() should not be called statically.
