### ISSUE TITLE
Laravel Guard

### ISSUE THREAD

**Issue by nWidart** [cartalyst/sentinel#374]
Hello,

Is there a custom laravel guard ( https://laravel.com/docs/5.4/authentication#adding-custom-guards ) available for sentinel ?

This would allow using some laravel methods with sentinel.

Thanks,

**Comment by nWidart** [comment]
I've just come across this one https://github.com/joshwhatk/sentinel-guard/tree/master/src

Might be nice to have this included with sentinel

**Comment by denisdulici** [comment]
@nWidart were you able to use it with Asgard?

**Comment by nWidart** [comment]
It works yes. I had to add the `attempt` method so added the class myself [here](https://github.com/AsgardCms/Platform/blob/2.0/Modules/User/Guards/Sentinel.php).

![image](https://user-images.githubusercontent.com/882397/28516454-9ae5d3b4-7061-11e7-807c-6586685beea2.png)

**Comment by brunogaspar** [comment]
Hello @nWidart 

I'm personally alright with this, however i'm a bit overwhelmed how Laravel handles versioning, which might cause issues in the future if they rename a method or whatever.

So my suggestion would be to keep as a separated package maybe?

Let's see what @suwardany have to say :)

**Comment by DMeganoski** [comment]
I had just spent the majority of the day yesterday trying to figure out how to integrate sentinel into laravel's default auth. I had created a new provider and userprovider for sentinel, which required a good deal of overriding methods to get to work. The gate solution is much cleaner, and implements all features of sentinel. 

I would also love to see this supported officially, and think a separate repository/package would probably be a good idea.

@nWidart 's class is close, but there are still a good deal of functions missing such as `loginUsingID()` and `logout()`

I'd be willing to share my progress once I've got a solid version.

**Comment by nWidart** [comment]
Sorry for late reply here, indeed @DMeganoski but those can easily be added, will do that.

**Comment by nWidart** [comment]
I just added those 2 methods: https://github.com/AsgardCms/Platform/commit/7b870594f66045cbb5503dc674f636bb376bcba3

Though I don't know if there's a better way with Sentinel to login using an ID. I had to first find the user, and then pass that to the Sentinel::login() method.

**Comment by DMeganoski** [comment]
That works too, I used 
```php
/**
	 * Log the given user ID into the application.
	 *
	 * @param  mixed $id
	 * @param  bool $remember
	 *
	 * @return \Illuminate\Contracts\Auth\Authenticatable|false
	 */
	public function loginUsingId($id, $remember = FALSE) {
		
		$user = SentinelFacade::findById($id);
		
		$this->setUser($user, $remember);
	}
```

Here is a gist of my guard class. https://gist.github.com/DMeganoski/9f3b0e42d4b8f37302433d1482afb77d

It should also be noted for complete integration, that a custom password broker for custom resets needs to be created. I could not find a way to bind my extended version to the container (I think because it is bound with `singleton`), and had to replace the original service provider `Illuminate\Auth\Passwords\PasswordResetServiceProvider` with my own extended version which overrode the functions binding the password broker.

**Comment by Gertiozuni** [comment]
I came accross an issue like: 
when adding middleware like this: `->middleware('can:see-survey,survey')` i had to add another method to the guard: 
`public function authenticate() {

    }`
