### ISSUE TITLE
Activation code not case sensitive

### ISSUE THREAD

**Issue by max-pro** [cartalyst/sentinel#376]
Activation code should be case sensitive, here if we convert W to w in activation link still user get activated.

**Comment by brunogaspar** [comment]
Do you have any suggestion to improve this?

**Comment by max-pro** [comment]
public function activate($email,$activation_code)
    {
    	$user = User::whereEmail($email)->first();
        $code1 = Activation::findByuser_id($user->getUserId());

        if($code1->code == $activation_code){

        	if(Activation::complete($user,$activation_code))
        	{
                
        		return 'activation completed';
        	}
        	else
        	{
        		return 'failed activation ';
        	}
        }
        else
        {
            return 'invalid activation code';
        }
    }

**Comment by max-pro** [comment]
if($code1 == $activation_code) are case sensitive

**Comment by brunogaspar** [comment]
Feel free to submit a pull request.
