### ISSUE TITLE
Get current user's roles

### ISSUE THREAD

**Issue by LeftPinkie** [cartalyst/sentinel#378]
Is there any way to get the current user's roles besides iterating `Sentinel::getRoles()` and checking each with `Sentinel::inRole()`?  Ideally I would like to have the current user's roles (slug and name) returned by `Sentinel::getUser()`

**Comment by brunogaspar** [comment]
You can access the user roles by accessing the roles relationship on the user itself.

```
$userRoles = Sentinel::getUser()->roles;
```

Hope it helps.
