### ISSUE TITLE
How can I make a 6-digit activation code?

### ISSUE THREAD

**Issue by ismailcaakir** [cartalyst/sentinel#380]
Is it possible to change activation codes without customising the package?
(i wanna do it on my application) I want to generate 6-digit verification numerical codes to confirm phone numbers.

**Comment by dels07** [comment]
+1 I have same same issue also, want to know some solution

**Comment by brunogaspar** [comment]
Hi

You'll need to extend Sentinel to have this behaviour i'm afraid.

[This](https://github.com/cartalyst/sentinel/wiki/Extending-Sentinel) gives a sense on how to do it.

If you still have questions about doing so, just let us know.
