### ISSUE TITLE
OAuth with Passport not working

### ISSUE THREAD

**Issue by hamza-d52** [cartalyst/sentinel#382]
i am using sentinel 2.0 with laravel version 5.4 and i have install laravel passport every thing works fine my issue is that i want to use OAuth for laravel , what i mean is with valid access token for a user i want to by pass the login system and directly let user enter to application from another application.

`$this->app->rebinding('request', function ($app, $request) { $request->setUserResolver(function () use ($app) { return $app['sentinel']->getUser(); }); });`
this code is not working for me aswell it is always returning null when we call $request->user or $app['sentinel']->getUser(); I am using laravel version 5.4

I had tired overriding the sentinel Authenicate() method but unsuccessful. Is there any update for sentinel going to come which is compatible with laravel passport?

**Comment by brunogaspar** [comment]
We don't have any plans on having custom code for Laravel Passport at this moment.

However, if the rebinding is not working, you can try to extend the Sentinel Service Provider with your own Service Provider and apply a patch there.

**Comment by PDXfoster** [comment]
@brunogaspar --> do you have any further advice on how to go about patching this through a service provider? I've been looking all over for an answer for this for nearly a year now. (just ran across my old comment: https://laracasts.com/discuss/channels/general-discussion/sentinel-passport-api-security) 

I seem to have the authentication working after finding this: https://stackoverflow.com/questions/49043879/laravel-passport-with-cartalyst-sentinel

I read thoroughly through the other related issue: https://github.com/cartalyst/sentinel/issues/328
but I just can't seem to get passport and sentinel to play nicely together to return the user when passing a bearer token to passport. 

Any direction would be greatly appreciated.
