### ISSUE TITLE
FatalThrowableError Class 'App\Http\Controllers\Sentinal' not found

### ISSUE THREAD

**Issue by aamirkhan37557** [cartalyst/sentinel#383]
when i want to login it give me this error

FatalThrowableError
Class 'App\Http\Controllers\Sentinal' not found

i have included use sentinel 

this is my controller

![login](https://user-images.githubusercontent.com/24594319/29486172-ed1c7dc6-8494-11e7-9f13-152d77e337bf.png)

**Comment by brunogaspar** [comment]
You've imported `Sentinel` but you're calling `Sentinal`, therefore you've a typo there :)
