### ISSUE TITLE
'sentinel.registering' event

### ISSUE THREAD

**Issue by pierlon** [cartalyst/sentinel#390]
When the event 'sentinel.registering' fires, the listener doesn't receive the credentials as an array, but as parameters instead. ([found here](https://github.com/cartalyst/sentinel/blob/2.0/src/Sentinel.php#L169))

Is this the intended way?

**Comment by brunogaspar** [comment]
It's not the intended way. Feels more like a change on Laravel Event system.

Any idea @suwardany ?
