### ISSUE TITLE
User Role assignment fails on registration (Laravel 5.5)

### ISSUE THREAD

**Issue by Ohssie** [cartalyst/sentinel#391]
Following the documentation found on the official website, assigning a user to a role goes like this, 

`$user = Sentinel::findById(1);

$role = Sentinel::findRoleByName('Subscribers');

$role->users()->attach($user);`

applying the same structure into my codes in laravel 5.5 flags an error 

> Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to a member function users() on null

Which is coming from this line `$role->users()->attach($user);`

Here's is my code block where I face same issue,

`public function create($request) {

        $userDetails = [
            'last_name' => strtolower($request->last_name),
            'first_name' => strtolower($request->first_name),
            'username' => $request->username,
            'state' => $request->state,
            'shipping_address' => $request->shipping_address,
            'phone_number' => $request->phone_number,
            'email' => $request->email,
            'password' => $request->password,
            'role' => $request->role,
        ];
        $user = Sentinel::register($userDetails, false);
        if ($request->role == ' ') {
            $role = Sentinel::findRoleBySlug('customer');
        } else {
            $role = Sentinel::findRoleBySlug($request->role);
        }
        $role->users()->attach($user);
        $activation = \Activation::create($user);
        return $user;
    }`

**Comment by brunogaspar** [comment]
From the error, you're calling `->users()` on `null`, which means `$role` doesn't contain anything, so it errors out as expected.

**Comment by Ohssie** [comment]
Thank you
Just fixed it

Now I would need a little help on implementation. Stated above, I intend to use this code block to register new customers and also let the admin add users to the platform. The workflow is this, if the user registers, the `$request->role` would be empty. Now I was checking to see if it was empty at any point so that if it's empty, the role should automatically be 'customer'

How so you think would be the best implementation procedure
