### ISSUE TITLE
Sentinel::authenticate always results to false

### ISSUE THREAD

**Issue by adru0071324** [cartalyst/sentinel#392]
What i am trying to do is to authenticate first before allowing to login
newbie.

```php
try {
    if (Sentinel::authenticate([
        'email'    => Request::input('email'),
        'password' => Request::input('password'),
    ])) {
        return dd('ok');
    }else{
        return dd('false');
    }
} catch (Cartalyst\Sentinel\Checkpoints\ThrottlingException $ex) {
    echo "Too many attempts!";
    return;
} catch (Cartalyst\Sentinel\Checkpoints\NotActivatedException $ex){
    echo "Please activate your account before trying to login";

    return;
}
```

**Comment by brunogaspar** [comment]
I've formatted your original post but i'm confused on what the problem is or what you're trying to achieve.

**Comment by adru0071324** [comment]
I would like to do an authentication before login somehow Sentinel::authenticate is is giving a False even if the credentials are correct.

**Comment by adru0071324** [comment]
I would like to do an authentication before login somehow Sentinel::authenticate is giving a False even if the credentials are correct.

**Comment by adru0071324** [comment]
i tried 
`dd(Sentinel::authenticate(
         ['email'    => Request::input('email'),
          'password' =>Request::input('password')]
))`

but it returns False

**Comment by brunogaspar** [comment]
I'm not able to reproduce any issue when performing authentication on users.

Make sure that you're not doing something funky with the password when creating the user and also ensure that when you're authenticating you really have data on both `email` and `password` inputs.

Other than this, it seems a bug on your application.

**Comment by dbrax** [comment]
I got this error as well 

   $credentials = [
            'email'    => $request->email,
            'password' => $request->password,
        ];
        
      
        $response=Sentinel::authenticate($credentials);

        echo json_encode($response);

keep getting false ..
