### ISSUE TITLE
Sentinel::activate(int) doesn't work

### ISSUE THREAD

**Issue by Ser5** [cartalyst/sentinel#394]
`Sentinel::activate(1)` doesn't work.

While `Sentinel::activate('1')` works - which I find very counterintuitive - almost a bug.

Reason is that `activate()` requires either a string or an array:
```
        if (is_string($user) || is_array($user)) {
            $users = $this->getUserRepository();

            $method = 'findBy'.(is_string($user) ? 'Id' : 'Credentials');
```

I suggest to add `int` support to the `activate()` method.

**Comment by brunogaspar** [comment]
Feel free to submit a pull request with a test case.
