### ISSUE TITLE
Sentinel per object permission

### ISSUE THREAD

**Issue by dels07** [cartalyst/sentinel#395]
I want to ask, is it possible to set permission per object, for example I have in school database:

- Principal will assign teacher to class
- Many Teachers can be assigned to many classes
- Teacher permission is based on class

So teacher John can edit schedule in Math class, but can only view schedule in English class. Let's say we store the permissions in each user permission column in nested json format with class_id as key, for teacher John:

`1: {class.index: true, class.edit: true, class.update: true, class.delete: true},`
`2: {class.index: true, class.edit: false, class.update: false, class.delete: false}`

**Comment by brunogaspar** [comment]
Hi

That's not possible, at least not by default (you can maybe implement your own permission strategy with Sentinel), Sentinel only cares for permissions as a whole, not per object.

Hope it clarifies it for you.
