### ISSUE TITLE
Double reminder request

### ISSUE THREAD

**Issue by KarelWintersky** [cartalyst/sentinel#396]
1. Request password recovery (via router or any other way)

```
$sentinel_user = Sentinel::findByCredentials( $request->all() );
$reminder = Reminder::create( $sentinel_user );
```
Our token will be in `$reminder->code` and this code will be present in DB.
```
2	2	sAV0FXMbE9NsOiuw340GgExnulRD1cl9	0		2017-10-18 16:24:23	2017-10-18 16:24:23
```

Well, call 'password recovery` again. 

We recieve second token and second record in DB.

User will recieve SECOND (3rd, 4th, etc) token as ACTUAL, but 
```
$reminder = Reminder::exists($sentinel_user);
```
will return FIRST record.

# How to fix?

do
```
            DB::table('reminders')->where('user_id', $sentinel_user->id)->delete();
```
before

```
            $reminder = Reminder::create($sentinel_user);
```

**Comment by brunogaspar** [comment]
Going to close as this doesn't seem very related to the package itself, but rather application specific.

**Comment by KarelWintersky** [comment]
Popular user case. And 'app specific'/
Idiot

**Comment by KarelWintersky** [comment]
Popular user case. And 'app specific'/
Idiot
Your library is useless absolutly

**Comment by cbj4074** [comment]
A useless library with 1,026 stars! 🤣

**Comment by KarelWintersky** [comment]
star is NOT an effective instrument for measure code effectiveness.
`star` is like an like in any social network. no. more.

**Comment by KarelWintersky** [comment]
I tried use this 'library'. 
Sentinel overrides native laravel's middlewares. It makes it incompatible with other packages that use auth subsystem.
And this version of sentinel contains A LOT of dirty code

**Comment by cbj4074** [comment]
@KarelWintersky

> star is NOT an effective instrument for measure code effectiveness.

Okay... is the number of downloads on packagist.org? Or what metric would you consider to be reflective of a given package's overall viability?

> Sentinel overrides native laravel's middlewares. It makes it incompatible with other packages that use auth subsystem.

Were you under the impression that Sentinel is a "drop-in" replacement for Laravel's native Auth? If so, why?

Straight from the documentation:

> [Sentinel is a] modern and **framework agnostic** authorization and authentication package featuring roles, permissions, custom hashing algorithms and additional security features.

How would a framework-agnostic package ever work as a drop-in replacement for Laravel's stock implementation?

> And this version of sentinel contains A LOT of dirty code

Such as? That statement is without merit unless you provide specific examples and explain why the code is "bad".

To answer your original question, look at https://github.com/cartalyst/sentinel/blob/2.0/src/Reminders/IlluminateReminderRepository.php#L98 .

The `$code` is optional, and if you don't specify it, the lookup is performed against the `$id` only. Accordingly, if more than one still-valid Reminder request has been issued for the user, multiple records will be returned.

Notice that there is no call to `orderBy()`, which means that the return order is undefined; the fact that you are getting the "FIRST record", as you say, is purely coincidental. By definition, a query that lacks an `ORDER BY` clause returns results in any order.

As evidenced by its name, this method's purpose is simply to answer the question, "Does one or more reminder requests **exist** for the user with the given `$id`?" Its purpose is not to return the most recently created Reminder.

Presumably, this is why @brunogaspar closed the Issue, with

> ... doesn't seem very related to the package itself".

And he's correct.

It would have been trivial for you to extend `IlluminateReminderRepository` and add a method to return only the most recently created Reminder.

Given that nobody else seems to have requested this "feature", Bruno is again correct in that the implementation you describe is application-specific.

It doesn't sound like you have any interest in using Sentinel at this point, but this information may be helpful for anyone else who comes in guns-blazing with the same request.

**Comment by webdevmedia** [comment]
"And this version of sentinel contains A LOT of dirty code"

Man i love this library/package....i love the style of coding with was created and is pretty fast,strong and suitable for the new codeigniter 4 ... Ion Auth vs Sentinel (winner by far).sorry for my bad english....:)))
