### ISSUE TITLE
[Proposal]Optional Cookies

### ISSUE THREAD

**Issue by BackEndTea** [cartalyst/sentinel#399]
Recently i ran into an issue where i didn't have a need for cookies, but the ```IlluminatePersistenceRepository``` requires a ```CookieInterface``` on creation. This means i have cartalyst_sentinel cookies, with a value of null, not doing anything.

My proposal is to either make the ```CookieInterface```optional,  or introduce the ```Null Cookie```. Which is just a fake Cookie, not doing anything.

The Null cookie would look something like this:
```php
class NullCookie implements CookieInterface
{

    /**
     * Put a value in the Sentinel cookie (to be stored until it's cleared).
     *
     * @param  mixed $value
     * @return void
     */
    public function put($value)
    {
    }

    /**
     * Returns the Sentinel cookie value.
     *
     * @return mixed
     */
    public function get()
    {
        return null;
    }

    /**
     * Remove the Sentinel cookie.
     *
     * @return void
     */
    public function forget()
    {
    }
}
```

If don't mind creating this and opening up a PR for it.

**Comment by brunogaspar** [comment]
I'm fine with having it on the core.

If you want to submit a PR, please go for it :)

**Comment by brunogaspar** [comment]
Thanks for the PR's!
