### ISSUE TITLE
The ReminderRepositoryInterface is not correct

### ISSUE THREAD

**Issue by BackEndTea** [cartalyst/sentinel#402]
The ```create``` function of the ```ReminderRepositoryInterface``` says it returns a string.

But it in fact, returns a ReminderModel in the ```IlluminateReminderRepository```

```php
    public function create(UserInterface $user)
    {
        $reminder = $this->createModel();

        $code = $this->generateReminderCode();

        $reminder->fill([
            'code'      => $code,
            'completed' => false,
        ]);

        $reminder->user_id = $user->getUserId();

        $reminder->save();

        return $reminder;
    }
```

My suggestion would be to change the interface signature, or have the create function return a string

**Comment by brunogaspar** [comment]
Just need to update the docblock, since code wise.

**Comment by BackEndTea** [comment]
Yeah thats what i meant, update the docblock.
