### ISSUE TITLE
Problems using Sentinel on PHP 5.5

### ISSUE THREAD

**Issue by Fergall** [cartalyst/sentinel#405]
Hi,

 I succeeded on install a native version of Sentinel on PHP 5.6, according to the site, Sentinel should work in PHP 5.4+, but when i'm installing on the client server, which has PHP 5.5 i get this error:

Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /var/www/html/denuncias/admin/bibliotecas/sentinel/vendor/illuminate/support/helpers.php on line 509

i know this is caused by the splat operator which is just introduced on php 5.6, but how can i make Sentinel work in php 5.5?

Thanks!

**Comment by BackEndTea** [comment]
Could it be that composer require or update was ran a php 5.6+ environment ? Because composer will try to install the latest version possible in your environment.

If your server is running 5.5 i would suggest adding 
```json
"platform": {
  "php": "5.5.38"
}
```
to your composer.json. This will make sure that running ```composer update``` or ```composer require``` won't add packages that don't support that version of php.

And if at all possible, i would suggest upgrading to php 5.6 or 7+.

**Comment by Fergall** [comment]
Thanks for the observation!

Gonna check that and test it to see if it works normally, and yeah, ideally it should update the server at least to 5.6, but we have no say in that, its the client decision :/

**Comment by brunogaspar** [comment]
Hello @Fergall

As @BackEndTea mentioned, if you can update PHP versions, please go for it. 

Another solution, not sure if it helps or not, as i don't know which version of `illuminate/support` it's being installed on your end, but you can also try to enforce on your `composer.json` an earlier version of the `illuminate/support` dependency we require until 5.0, other than that, there's not much we can do on the package i'm afraid.

But let us know how it goes.

**Comment by Fergall** [comment]
Thanks for the help, my composer.json it looks like this now:

`{
    "name": "cartalyst/sentinel",
    "description": "PHP 5.4+ Fully-featured Authentication & Authorization System",
    "keywords": [
        "php",
        "cartalyst",
        "laravel",
        "auth",
        "security",
        "codeigniter",
        "fuelphp"
    ],
    "license": "BSD-3-Clause",
    "authors": [
        {
            "name": "Cartalyst LLC",
            "email": "help@cartalyst.com",
            "homepage": "https://cartalyst.com"
        }
    ],
    "platform": {
		"php": "5.5.38"
	},
    "require": {
        "php": ">=5.4.0",
        "cartalyst/support": "~1.0|~2.0",
        "illuminate/support": "~5.0"
    },
    "require-dev": {
        "illuminate/cookie": "~5.0",
        "illuminate/database": "~5.0",
        "illuminate/events": "~5.0",
        "illuminate/http": "~5.0",
        "illuminate/session": "~5.0",
        "ircmaxell/password-compat": "~1.0",
        "mockery/mockery": "~0.9",
        "paragonie/random_compat": "^1.4|^2",
        "phpunit/phpunit": "~4.0"
    },
    "suggest": {
        "illuminate/database": "By default, Sentinel utilizes the powerful Illuminate database layer.",
        "illuminate/events": "To hook into various events across Sentinel, we recommend using Illuminate's event dispatcher.",
        "ircmaxell/password-compat": "Default hashing uses PHP 5.5 password_* functions, with forward-compatible support.",
        "symfony/http-foundation": "Required for native implementations."
    },
    "autoload": {
        "psr-4": {
            "Cartalyst\\Sentinel\\": "src/"
        }
    },
    "extra": {
        "component": "package",
        "branch-alias": {
            "dev-master": "2.0.x-dev"
        }
    },
    "minimum-stability": "stable"
}`

After doing `composer update` it should work, at least in theory, right?

**Comment by BackEndTea** [comment]
The 
```"platform": {
	"php": "5.5.38"
},
```
part should be in your own composer.json

**Comment by Fergall** [comment]
@BackEndTea 

Thanks, i still don't get the handle with Composer, but with that i made it work with a lesser version.

@brunogaspar now it's working, thanks both for the help :+1:
