### ISSUE TITLE
select users by age 

### ISSUE THREAD

**Issue by TeyNey** [cartalyst/sentinel#406]
is there any way how to do this 

$users = DB::table('users')->whereBetween('date_of_birth', [$carbon_max, $carbon_min])->get();

with sentinel ?

**Comment by brunogaspar** [comment]
Hello @TeyNey 

You can use the Sentinel User Model:

```php
$users = \Cartalyst\Sentinel\Users\EloquentUser::whereBetween('date_of_birth', [$carbon_max, $carbon_min])->get();
```

Or you can use the Sentinel Users Repository:

```php
$users = \Sentinel::getUserRepository()->whereBetween('date_of_birth', [$carbon_max, $carbon_min])->get();
```

Hope it helps!
