### ISSUE TITLE
user->update() doesn't hash password

### ISSUE THREAD

**Issue by camtarn** [cartalyst/sentinel#408]
It looks like user->update() is the intended mechanism for updating passwords, as mentioned in another issue.

In my current very vanilla setup, it seems to be storing plaintext passwords. Of course, this means that after a password update, the user is unable to log in.

        Sentinel::registerAndActivate([
          'email'    => 'test@example.com',
          'password' => 'asdf'
        ]);

        mysql> select password from users where email='test@example.com';
        $2y$10$urHKraELe8oClCb7BG.rsOO701yqVrkPsUTmjeDEx/IR/QPvH/tdW

        $a_user = Sentinel::findByCredentials([
          'email' => 'test@example.com'
        ]);
        $a_user->update([
          'password' => 'asdf'
        ]);

        mysql> select password from users where email='test@example.com';
        asdf

`composer show` output:

     cartalyst/sentinel        v2.0.17 PHP 5.4+ Fully-featured Authentication & Authorization System
     cartalyst/support         v2.0.1  Support helpers.
     doctrine/inflector        v1.2.0  Common String Manipulations with regard to casing and singular/plural      rules.
     illuminate/container      v5.5.28 The Illuminate Container package.
     illuminate/contracts      v5.5.28 The Illuminate Contracts package.
     illuminate/database       v5.5.28 The Illuminate Database package.
     illuminate/events         v5.5.28 The Illuminate Events package.
     illuminate/support        v5.5.28 The Illuminate Support package.
     nesbot/carbon             1.22.1  A simple API extension for DateTime.
     paragonie/random_compat   v2.0.11 PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
     psr/container             1.0.0   Common Container Interface (PHP FIG PSR-11)
     psr/simple-cache          1.0.0   Common interfaces for simple caching
     symfony/http-foundation   v3.4.2  Symfony HttpFoundation Component
     symfony/polyfill-mbstring v1.6.0  Symfony polyfill for the Mbstring extension
     symfony/polyfill-php70    v1.6.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
     symfony/translation       v3.4.2  Symfony Translation Component

**Comment by suwardany** [comment]
Check https://cartalyst.com/manual/sentinel/2.0#sentinel-update

**Comment by camtarn** [comment]
Oh. Didn't spot the difference between $user->update() and Sentinel::update( $user ). Never mind.

(this is kinda dangerous though - perhaps the docs should call this out?)

**Comment by suwardany** [comment]
we could add a note there, ya
