### ISSUE TITLE
fire Logout Event

### ISSUE THREAD

**Issue by delia-curiel** [cartalyst/sentinel#410]
Hi, I need to listen for the user logout, but I don't know if Sentinel fires this event.

**Comment by delia-curiel** [comment]
thanks @brunogaspar, I think it would be great to add this feature, just as the Auth package in Lavarel does (it fires two events on login and logout: 'Illuminate\Auth\Events\Login' and Illuminate\Auth\Events\Logout)

**Comment by lehainam125** [comment]
+1

**Comment by Surya1995** [comment]
@delia-curiel 
maybe you should try to make an own feature using the user-override extension and fire event whenever you want I have fired an event on forgot password .
[useroveride.zip](https://github.com/cartalyst/sentinel/files/2680075/useroveride.zip)

@brunogaspar

**Comment by brunogaspar** [comment]
This has been implemented.
