### ISSUE TITLE
getAuthIdentifierName

### ISSUE THREAD

**Issue by gifary** [cartalyst/sentinel#417]
Hello I am getting this error BadMethodCallException
Call to undefined method Illuminate\Database\Query\Builder::getAuthIdentifierName() when using laravel passport. I am stuck how to solve this.

Best regargs,
gifary

**Comment by kfeng0806** [comment]
You should implement this interface in your Account model as per the docs: https://laravel.com/docs/5.5/authentication#the-authenticatable-contract

If you are using the default user model from sentinel, then you need make a copy of `Cartalyst\Sentinel\Users\EloquentUser` to `App\User` or `App\Models\User` then implement the above contract(Don't forget change the namespace or class name of EloquentUser class).

Or you can just simple copy it from here https://gist.github.com/kfeng0806/ab81ba58437b10df2eb02c5b669debe3
