### ISSUE TITLE
NullPointerExeception on server start

### ISSUE THREAD

**Issue by IdkMan2** [cartalyst/sentinel#418]
Issue occurs only once on server start.
Error:
https://pastebin.com/FUTWwbgm
Sentinel config:
https://pastebin.com/A7GPq9z0
Citizens config:
https://pastebin.com/RpxbjqGY

I am using latest PaperSpigot, Sentinel build 119 and latest Citizens.

**Comment by brunogaspar** [comment]
Hello @IdkMan2 it seems that you've opened the issue on the incorrect repository.
