### ISSUE TITLE
Laravel 5.6 support

### ISSUE THREAD

**Issue by deanlaw** [cartalyst/sentinel#419]
Are there any issues running with the now released Laravel 5.6?

**Comment by brunogaspar** [comment]
@deanlaw As far as we know, we are not aware of issues with Laravel 5.6.

If you however encounter any problem, please feel free to create a new issue.

Thanks!

**Comment by roquie** [comment]
Maybe this feature will help someone: https://gist.github.com/roquie/29e7f304a99fb9ab6b29485039d79710
