### ISSUE TITLE
onSessionStart Event

### ISSUE THREAD

**Issue by deanlaw** [cartalyst/sentinel#420]
I have an issue with the remember_me feature and last_login dates. I need to track returning users, not just new logins. If someone logs into the site and chooses the remember me option, their last_login field never changes when they return to the site and are simply automatically re-logged into the site. I have to be able to generate a report of all users who have used the site each day and with this current behavior, there is no way for me to do this.

I was thinking that if there was some type of onSessionStart event, that I could update the last_update field myself. But I looked through the code and it appears that there is nothing fired when someone is re-authenticated. Ideally, it would be great to have an option in the Sentinel config file that, if turned on, would tell Sentinel to automatically update the last_login field when a returning user is re-authenticated. But I would settle for at least some type of event that I could monitor for.

**Comment by brunogaspar** [comment]
Hello @deanlaw 

That's an interesting request.

I agree that it would be good to have such event or even a flag to turn on/off that update on the `last_login` column, or perhaps both :)

Feel free to submit a pull request with an implementation if you feel like it, we totally welcome it!

Thanks!
