### ISSUE TITLE
Bug with findByCredentials()

### ISSUE THREAD

**Issue by aurmil** [cartalyst/sentinel#421]
Hello,

in https://github.com/cartalyst/sentinel/blob/8ee7778f96ab6193f4be118a52d265c6861de0a5/src/Users/IlluminateUserRepository.php#L85
password is read from 
https://github.com/cartalyst/sentinel/blob/8ee7778f96ab6193f4be118a52d265c6861de0a5/src/Users/IlluminateUserRepository.php#L95
but is not used after that, there is no check that user password matches $password...

**Comment by suwardany** [comment]
This is not meant to authorize, it's only meant to find a user based on their email or login names incase they are not default.
