### ISSUE TITLE
Login without password while using social login

### ISSUE THREAD

**Issue by vijaymgr** [cartalyst/sentinel#422]
I am using socialite in laravel 5.4. After redirect back to my application, I need to logged the user in. I know that user can be logged in by `Sentinel::login($user)` but, it needs email and password. Since I am using social login, I don't have password. So, I get message `You have not passed a [password]`. How to handle this error in such scenario?

**Comment by v1nk0** [comment]
The function **login** does need the credentials. 
Do you maybe mean the **register** function?

**Comment by brunogaspar** [comment]
During OAuth, you should be able to have access to a User identifier, like the email address.

In that case, you can technically use something like:

```php
$user = App\User::where('email', $email)->first();

Sentinel::login($user);
```

The `login()` only accepts a `User` instance, therefore, you don't a password.

Hope it helps.
