### ISSUE TITLE
extending sentinel

### ISSUE THREAD

**Issue by TeyNey** [cartalyst/sentinel#424]
i read https://github.com/cartalyst/sentinel/wiki/Extending-Sentinel but i'm not sure if i got it right. I can use eloquent syntax and it will use sentinel with all his security yes ?

**Comment by brunogaspar** [comment]
Hello @TeyNey 

Sentinel, by default, uses Eloquent, so you don't really need to anything in that regard.

The main purpose of extending is to add additional or modify current methods from the repositories or even models.

It also allows to swap Eloquent and use a different implementation.

Hope it helps.
