### ISSUE TITLE
how to add parameter after the url ,like GET index/_search?preference=network

### ISSUE THREAD

**Issue by taoyantu** [cartalyst/sentinel#425]
Now I have a very difficult problem, and I need to add parameters after the Url to ensure the stability of the result.
   how to add the config?
   i want to search like GET index/_search?preference=network
   please help me ,thank you very much !!

**Comment by brunogaspar** [comment]
Hello @taoyantu , i believe you have opened an issue on the wrong repository :)

**Comment by taoyantu** [comment]
@brunogaspar oh~~ sorry,i `m wrong..
