### ISSUE TITLE
Hello, I dunno why I keep getting: Type error: Argument 1 passed to Cartalyst\Sentinel\Sentinel::register() must be of the type array, object given when trying to use  Sentinel::register()

### ISSUE THREAD

**Issue by jaywizzy** [cartalyst/sentinel#427]

**Comment by brunogaspar** [comment]
Hello @jaywizzy 

The error seems to be straight forward.

You're passing an object instead of an array when calling the `Sentinel::register()` method.
[This method only accepts an array as the first argument](https://github.com/cartalyst/sentinel/blob/2.0/src/Sentinel.php#L163).

Hope it helps.
