### ISSUE TITLE
I dunno why I'm getting No [login] credential was passed.

### ISSUE THREAD

**Issue by jaywizzy** [cartalyst/sentinel#428]

**Comment by drsii** [comment]
Neither do we. We'll need way more info and code examples to help.

**Comment by jaywizzy** [comment]
Honestly, the documentation is not helping and I have a deadline to meet up with, wish I hadn't used it from the start.

**Comment by jaywizzy** [comment]
The thing is I'm trying to create a new user but it keeps telling me: No [login] credential was passed.

**Comment by jaywizzy** [comment]
In my controller I have:

public function save(Request $request){
        $validatedRecords = $request->validate([
            'username' => 'required|unique:users',
            'first_name' => 'required',
            'email' => 'required|unique:users',
            'organisation'  =>  'required',
            'password'  =>  'required',
            'g-recaptcha-response' => 'required|recaptcha',

        ]);
        if($validatedRecords) {
            $user = $this->userModel->create($request);
            Sentinel::register(array($user), $callback = null);
            if ($user) {
                return redirect()->route('login');
                return view('auth.login');
            } else {
                return view('auth.register')->with('errors', 'failed to register user');
            }
        }    	

    }

**Comment by jaywizzy** [comment]
and in the migration file: 
Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('username')->nullable()->unique();
            $table->string('email');
            $table->text('permissions')->nullable();
            $table->timestamp('last_login')->nullable();
            $table->string('first_name');
            $table->string('last_name');
            $table->string('title')->nullable();
            $table->string('organisation');
            $table->string('department')->nullable();
            $table->string('position')->nullable();
            $table->string('postal_address')->nullable();
            $table->string('phone')->nullable();
            $table->text('comment')->nullable();
            $table->string('password')->nullable();
            $table->timestamps();

            $table->engine = 'InnoDB';
            $table->unique('email');
        });
    }

**Comment by jaywizzy** [comment]
I don't know what I'm doing wrong. Please, help me out

**Comment by jaywizzy** [comment]
let me try that.

**Comment by jaywizzy** [comment]
it's populating the DB and I got this:

 +wasRecentlyCreated: true
  #attributes: array:14 [▼
    "first_name" => "segun"
    "last_name" => "oluwasegun"
    "title" => null
    "organisation" => "nHub"
    "department" => null
    "position" => null
    "postal_address" => null
    "phone" => null
    "email" => "jaywizzy@gmail.com"
    "comment" => null
    "password" => "vanshergzie"
    "updated_at" => "2018-04-06 04:48:11"
    "created_at" => "2018-04-06 04:48:11"
    "id" => 2
  ]
  #original: array:14 [▼
    "first_name" => "segun"
    "last_name" => "oluwasegun"
    "title" => null
    "organisation" => "nHub"
    "department" => null
    "position" => null
    "postal_address" => null
    "phone" => null
    "email" => "jaywizzy@gmail.com"
    "comment" => null
    "password" => "vanshergzie"
    "updated_at" => "2018-04-06 04:48:11"
    "created_at" => "2018-04-06 04:48:11"
    "id" => 2
  ]

**Comment by jaywizzy** [comment]
but when I remove it, it returns the error message again

**Comment by jaywizzy** [comment]
User {#235 ▼
  #fillable: array:4 [▼
    0 => "email"
    1 => "password"
    2 => "first_name"
    3 => "last_name"
  ]
  #hidden: array:2 [▼
    0 => "password"
    1 => "remember_token"
  ]
  #table: "users"
  #persistableKey: "user_id"
  #persistableRelationship: "persistences"
  #loginNames: array:1 [▼
    0 => "email"
  ]
  #connection: "mysql"
  #primaryKey: "id"
  #keyType: "int"
  +incrementing: true
  #with: []
  #withCount: []
  #perPage: 15
  +exists: true
  +wasRecentlyCreated: true
  #attributes: array:14 [▼
    "first_name" => "loreta"
    "last_name" => "jugu"
    "title" => null
    "organisation" => "nHub"
    "department" => null
    "position" => null
    "postal_address" => null
    "phone" => null
    "email" => "loreta@jugu.com"
    "comment" => null
    "password" => "loreta"
    "updated_at" => "2018-04-06 06:07:15"
    "created_at" => "2018-04-06 06:07:15"
    "id" => 3
  ]
  #original: array:14 [▼
    "first_name" => "loreta"
    "last_name" => "jugu"
    "title" => null
    "organisation" => "nHub"
    "department" => null
    "position" => null
    "postal_address" => null
    "phone" => null
    "email" => "loreta@jugu.com"
    "comment" => null
    "password" => "loreta"
    "updated_at" => "2018-04-06 06:07:15"
    "created_at" => "2018-04-06 06:07:15"
    "id" => 3
  ]
  #changes: []
  #casts: []
  #dates: []
  #dateFormat: null
  #appends: []
  #dispatchesEvents: []
  #observables: []
  #relations: []
  #touches: []
  +timestamps: true
  #visible: []
  #guarded: array:1 [▶]
  #permissionsInstance: null
}

**Comment by drsii** [comment]
I'm not near my computer but please scrub user passwords from your dumps.

**Comment by jaywizzy** [comment]
Ok. I will

**Comment by brunogaspar** [comment]
Hello @jaywizzy 

The problem is that you're passing an array with something inside that array to the `register` method.

Your code:

```php
$user = $this->userModel->create($request);
Sentinel::register(array($user), $callback = null);
```

With this in mind the `$user` seems to hold an Eloquent relation, therefore, with your code, you're passing an incorrect payload to the `register` method, as in the end it will be:

```php
array(
    array(
        "first_name" => "segun"
        "last_name" => "oluwasegun"
        "title" => null
        "organisation" => "nHub"
        "department" => null
        "position" => null
        "postal_address" => null
        "phone" => null
        "email" => "jaywizzy@gmail.com"
        "comment" => null
        "password" => "testpassword"
    )
)
```

Which is wrong :)

It should be just something like:

```php
array(
    "first_name" => "segun"
    "last_name" => "oluwasegun"
    "title" => null
    "organisation" => "nHub"
    "department" => null
    "position" => null
    "postal_address" => null
    "phone" => null
    "email" => "jaywizzy@gmail.com"
    "comment" => null
    "password" => "testpassword"
)
```

The documentation clearly states how you should pass the data to the `register` method.
Please have a look [here](https://cartalyst.com/manual/sentinel/2.0#sentinel-register).

Another thing related to your code, you seem to be creating the user and then wanting to register the user (you're doing pretty much the same thing, twice), this will in turn cause another problem for you, because, even if you pass the correct payload to the `register` method, it will most likely error out, due to the fact that there's already a user on the database with such email address.

You can try this code but do keep in mind that i haven't tested nor i'm 100% sure how you're received the form data:

```php
if ($validatedRecords) {
    $user = Sentinel::register($request->all(), $callback = null);
    if ($user) {
        return redirect()->route('login');
    } else {
        return view('auth.register')->with('errors', 'failed to register user');
    }
} 
```

Hope it helps!

**Comment by jaywizzy** [comment]
Thanks @brunogaspar it works, you're the best

**Comment by brunogaspar** [comment]
No problem @jaywizzy 👍
