### ISSUE TITLE
Hi, I can't use the password that I use to register to login. but when I go into the DB to copy the hashed password, it authenticates. why?

### ISSUE THREAD

**Issue by jaywizzy** [cartalyst/sentinel#429]

**Comment by jaywizzy** [comment]
i even tried something like: 
![screenshot from 2018-04-08 07-48-44](https://user-images.githubusercontent.com/20246953/38464248-320972bc-3b02-11e8-8d7d-678aed2ba3f2.png)
but it didn't work and I got something like this:
![screenshot from 2018-04-08 07-49-05](https://user-images.githubusercontent.com/20246953/38464253-49df2602-3b02-11e8-8cc7-f71966950d92.png)
then I went to the database and found out that the password in the DB and the input password are not the same:
![screenshot from 2018-04-08 07-53-07](https://user-images.githubusercontent.com/20246953/38464260-6c107da2-3b02-11e8-9034-f1faeb5b6a0e.png)

**Comment by brunogaspar** [comment]
Hello @jaywizzy 

What is the exact code that you're using to perform the authentication? I can only see a glimpse of it on the first image and it seems that you're doing it a bit wrong.

**Comment by talal424** [comment]
its a typo

column "passwor" should be "password"

check the model for typos

**Comment by brunogaspar** [comment]
Good catch @talal424 

Closing as seems to not be related to Sentinel.
