### ISSUE TITLE
Is there permissions  saving limit?

### ISSUE THREAD

**Issue by GhulamJafar** [cartalyst/sentinel#430]
Does sentinel have any limit of saving permission in role permission column.

I am saving permissions. It was saving fine. But now today when i add some more permissions. Its not saving these permissions. Saving all old permissions. But not new one. Even i made permission column LONG TEXT. Its saving other words, But not saving permissions.

Its looking there is limit on saving permissions in code.

Please help.

**Comment by brunogaspar** [comment]
Hello @GhulamJafar 

It seems you have a big list of permissions..

Are you able to paste your permissions as `JSON` format so we can determine what column type would be more suitable for your use case?

**Comment by GhulamJafar** [comment]
{  
   "application.desk_officer_dashboard.dashboard":false,
   "application.desk_officer_dashboard.re_evaluation_application":false,
   "application.desk_officer_dashboard.add_application":false,
   "application.desk_officer_dashboard.save_application":false,
   "application.desk_officer_dashboard.edit_application":false,
   "application.desk_officer_dashboard.update_application":false,
   "application.desk_officer_dashboard.view_form_level_1":true,
   "application.desk_officer_dashboard.ajax_cnic":false,
   "application.desk_officer_dashboard.visitor_listing":false,
   "application.desk_officer_dashboard.visitor_application":true,
   "application.desk_officer_dashboard.skip_visitor_application":false,
   "application.desk_officer_dashboard.dashboard_records":false,
   "application.desk_officer_dashboard.re_evaluation_records":false,
   "application.desk_officer_dashboard.correction_app":false,
   "application.desk_officer_dashboard.correction_app_records":false,
   "application.desk_officer_dashboard.online_app":false,
   "application.desk_officer_dashboard.online_app_records":false,
   "application.desk_officer_dashboard.online_app_add":false,
   "application.desk_officer_dashboard.desk_app":false,
   "application.desk_officer_dashboard.desk_app_records":false,
   "application.desk_officer_dashboard.desk_add":false,
   "application.desk_officer_dashboard.desk_save":false,
   "application.desk_officer_dashboard.desk_view":false,
   "application.desk_officer_dashboard_2.dashboard_phase2":false,
   "application.desk_officer_dashboard_2.add_application_phase2":false,
   "application.desk_officer_dashboard_2.save_application_phase2":false,
   "application.desk_officer_dashboard_2.view_application_phase2":true,
   "application.desk_officer_dashboard_2.edit_application_phase2":false,
   "application.desk_officer_dashboard_2.update_application_phase2":false,
   "application.desk_officer_dashboard_2.forward_application_phase2":false,
   "application.desk_officer_dashboard_2.re_evaluation_application_phase2":false,
   "application.desk_officer_dashboard_2.phase2_dashboard_records":false,
   "application.desk_officer_dashboard_2.phase2_forwarded_records":false,
   "application.credit_officer_dashboard.dashboard":false,
   "application.credit_officer_dashboard.add_application":false,
   "application.credit_officer_dashboard.save_application":false,
   "application.credit_officer_dashboard.upload_reference_picture":false,
   "application.credit_officer_dashboard.uploads_multiple_images":false,
   "application.credit_officer_dashboard.uploads_signature_snap":false,
   "application.credit_officer_dashboard.edit_application":false,
   "application.credit_officer_dashboard.update_application":false,
   "application.credit_officer_dashboard.view_application":true,
   "application.credit_officer_dashboard.forward_application":false,
   "application.credit_officer_dashboard.re_evaluation_application":false,
   "application.credit_officer_dashboard.print_application":false,
   "application.credit_officer_dashboard.record_voice":false,
   "application.credit_officer_dashboard.dashboard_records":false,
   "application.credit_officer_dashboard.re_evaluation_records":false,
   "application.credit_officer_dashboard.forward_app_records":false,
   "application.credit_officer_dashboard.borrower_closing":false,
   "application.credit_officer_dashboard.borrower_closing_save":false,
   "application.credit_officer_dashboard.borrower_closing_view":false,
   "application.credit_officer_dashboard.correction_app":false,
   "application.credit_officer_dashboard.correction_app_records":false,
   "application.social_mobilizer_dashboard.dashboard":false,
   "application.social_mobilizer_dashboard.add_application":false,
   "application.social_mobilizer_dashboard.save_application":false,
   "application.social_mobilizer_dashboard.edit_application":false,
   "application.social_mobilizer_dashboard.update_application":false,
   "application.social_mobilizer_dashboard.view_application":true,
   "application.social_mobilizer_dashboard.get_forward_application":false,
   "application.social_mobilizer_dashboard.get_re_evaluation_application":false,
   "application.social_mobilizer_dashboard.dashboard_records":false,
   "application.social_mobilizer_dashboard.re_evaluation_records":false,
   "application.social_mobilizer_dashboard.forward_app_records":false,
   "application.social_mobilizer_dashboard.correction_app":false,
   "application.social_mobilizer_dashboard.correction_app_records":false,
   "application.credit_manager_dashboard.dashboard":false,
   "application.credit_manager_dashboard.add_application":false,
   "application.credit_manager_dashboard.save_application":false,
   "application.credit_manager_dashboard.edit_application":false,
   "application.credit_manager_dashboard.update_application":false,
   "application.credit_manager_dashboard.view_application":true,
   "application.credit_manager_dashboard.forward_application":false,
   "application.credit_manager_dashboard.re_evaluation_application":false,
   "application.credit_manager_dashboard.dashboard_records":false,
   "application.credit_manager_dashboard.re_evaluation_records":false,
   "application.credit_manager_dashboard.forward_app_records":false,
   "application.credit_manager_dashboard.borrower_closing":false,
   "application.credit_manager_dashboard.borrower_closing_records":false,
   "application.credit_manager_dashboard.borrower_closing_add":false,
   "application.credit_manager_dashboard.borrower_closing_save":false,
   "application.credit_manager_dashboard.borrower_closing_view":false,
   "application.account_manager_dashboard.dashboard_phase_I":false,
   "application.account_manager_dashboard.edit_application_phase_I":false,
   "application.account_manager_dashboard.update_application_phase_I":false,
   "application.account_manager_dashboard.view_application_phase_I":true,
   "application.account_manager_dashboard.forward_application_phase_I":false,
   "application.account_manager_dashboard.re_evaluation_application_phase_I":false,
   "application.account_manager_dashboard.phase1_dashboard_records":false,
   "application.account_manager_dashboard.phase1_re_evaluation_records":false,
   "application.account_manager_dashboard.phase1_forward_app_records":false,
   "application.account_manager_dashboard.borrower_closing":false,
   "application.account_manager_dashboard.borrower_closing_records":false,
   "application.account_manager_dashboard.borrower_closing_add":false,
   "application.account_manager_dashboard.borrower_closing_save":false,
   "application.account_manager_dashboard.borrower_closing_view":false,
   "application.account_manager_dashboard.invoice_request":false,
   "application.account_manager_dashboard.invoice_request_records":false,
   "application.account_manager_dashboard.invoice_request_add":false,
   "application.account_manager_dashboard.invoice_request_store":false,
   "application.account_manager_dashboard.invoice_request_view":false,
   "application.account_manager_dashboard_2.dashboard_phase_II":false,
   "application.account_manager_dashboard_2.edit_application_phase_II":false,
   "application.account_manager_dashboard_2.update_application_phase_II":false,
   "application.account_manager_dashboard_2.view_application_phase_II":true,
   "application.account_manager_dashboard_2.forward_application_phase_II":false,
   "application.account_manager_dashboard_2.re_evaluation_application_phase_II":false,
   "application.account_manager_dashboard_2.phase2_dashboard_records":false,
   "application.account_manager_dashboard_2.phase2_forward_app_records":false,
   "application.account_manager_recovery.pending_voucher":false,
   "application.account_manager_recovery.pending_voucher_record":false,
   "application.account_manager_recovery.approved_voucher":false,
   "application.account_manager_recovery.approved_voucher_record":false,
   "application.account_manager_recovery.rejected_voucher":false,
   "application.account_manager_recovery.rejected_voucher_record":false,
   "application.account_manager_recovery.edit_voucher":false,
   "application.account_manager_recovery.update_voucher":false,
   "application.account_manager_recovery.view_voucher":false,
   "application.visitors.index":true,
   "application.visitors.create":false,
   "application.visitors.save":false,
   "application.visitors.edit":false,
   "application.visitors.update":false,
   "application.visitors.destroy":false,
   "application.visitors.view":true,
   "application.visitors.get_records":true,
   "application.mark_locations.index":true,
   "application.mark_locations.create":false,
   "application.mark_locations.edit":false,
   "application.mark_locations.update":false,
   "application.mark_locations.googlemaproute":false,
   "application.mark_locations.view":true,
   "application.mark_locations.get_borrowerinfo":true,
   "application.mark_locations.borrower_route":true,
   "application.content_writer_dashboard.dashboard":false,
   "application.content_writer_dashboard.re_evaluated_applications":false,
   "application.content_writer_dashboard.forwarded_applications":false,
   "application.content_writer_dashboard.dashboard_records":false,
   "application.content_writer_dashboard.re_evaluation_records":false,
   "application.content_writer_dashboard.forward_app_records":false,
   "application.content_writer_dashboard.create":false,
   "application.content_writer_dashboard.save_eng_content":false,
   "application.content_writer_dashboard.save_urdu_content":false,
   "application.content_writer_dashboard.update_eng_content":false,
   "application.content_writer_dashboard.update_urdu_content":false,
   "application.content_writer_dashboard.edit":false,
   "application.content_writer_dashboard.update":false,
   "application.content_writer_dashboard.destroy":false,
   "application.content_writer_dashboard.view":true,
   "application.content_writer_dashboard.payment_request":false,
   "application.content_writer_dashboard.payment_request_records":false,
   "application.content_writer_dashboard.payment_request_add":false,
   "application.content_writer_dashboard.payment_request_view":false,
   "application.country_head_dashboard.dashboard":false,
   "application.country_head_dashboard.re_evaluated_applications":false,
   "application.country_head_dashboard.forwarded_applications":false,
   "application.country_head_dashboard.dashboard_records":false,
   "application.country_head_dashboard.re_evaluation_records":false,
   "application.country_head_dashboard.forward_app_records":false,
   "application.country_head_dashboard.create":false,
   "application.country_head_dashboard.save":false,
   "application.country_head_dashboard.edit":false,
   "application.country_head_dashboard.edit_application":false,
   "application.country_head_dashboard.update":false,
   "application.country_head_dashboard.country_head_application":true,
   "application.country_head_dashboard.borrower_closing":false,
   "application.country_head_dashboard.borrower_closing_records":false,
   "application.country_head_dashboard.borrower_closing_add":false,
   "application.country_head_dashboard.borrower_closing_save":false,
   "application.country_head_dashboard.borrower_closing_view":false,
   "application.media_dashboard.dashboard":false,
   "application.media_dashboard.phase1_re_evaluated_applications":false,
   "application.media_dashboard.phase1_forwarded_applications":false,
   "application.media_dashboard.phase1_dashboard_records":false,
   "application.media_dashboard.phase1_re_evaluation_records":false,
   "application.media_dashboard.phase1_forward_app_records":false,
   "application.media_dashboard.create":false,
   "application.media_dashboard.view":true,
   "application.media_dashboard.store":false,
   "application.media_dashboard.edit":false,
   "application.media_dashboard.destroy":false,
   "application.media_dashboard.update":false,
   "application.media_dashboard_phase2.dashboard_phase2":false,
   "application.media_dashboard_phase2.phase2_forwarded_applications":false,
   "application.media_dashboard_phase2.phase2_dashboard_records":false,
   "application.media_dashboard_phase2.phase2_forward_app_records":false,
   "application.media_dashboard_phase2.view_application_phase2":true,
   "application.media_dashboard_phase2.edit_application_phase2":false,
   "application.media_dashboard_phase2.update_application_phase2":false,
   "application.president_dashboard.dashboard":true,
   "application.president_dashboard.forwarded_applications":true,
   "application.president_dashboard.re_evaluated_applications":true,
   "application.president_dashboard.rejected_applications":true,
   "application.president_dashboard.dashboard_records":true,
   "application.president_dashboard.re_evaluation_records":true,
   "application.president_dashboard.forward_app_records":true,
   "application.president_dashboard.rejected_app_records":true,
   "application.president_dashboard.create":true,
   "application.president_dashboard.save":true,
   "application.president_dashboard.edit":true,
   "application.president_dashboard.update":true,
   "application.president_dashboard.view_application":true,
   "application.president_dashboard.delete_application":true,
   "application.president_dashboard.update_project_cost":true,
   "application.president_dashboard.borrower_closing":true,
   "application.president_dashboard.borrower_closing_records":true,
   "application.president_dashboard.borrower_closing_add":true,
   "application.president_dashboard.borrower_closing_save":true,
   "application.president_dashboard.borrower_closing_view":true,
   "application.president_dashboard.cheque_lists":true,
   "application.president_dashboard.cheque_lists_record":true,
   "application.president_dashboard.cheque_list_signed":true,
   "application.president_dashboard.cheque_list_detail":true,
   "application.procurement_officer_dashboard.dashboard":false,
   "application.procurement_officer_dashboard.forward_application":false,
   "application.procurement_officer_dashboard.dashboard_records":false,
   "application.procurement_officer_dashboard.forward_app_records":false,
   "application.procurement_officer_dashboard.create":false,
   "application.procurement_officer_dashboard.store":false,
   "application.procurement_officer_dashboard.edit":false,
   "application.procurement_officer_dashboard.update":false,
   "application.procurement_officer_dashboard.view_application":true,
   "application.procurement_officer_dashboard.destroy":false,
   "application.procurement_officer_dashboard.print_application_phase1":false,
   "application.procurement_officer_dashboard_phase2.dashboard_phase2":false,
   "application.procurement_officer_dashboard_phase2.forward_application_phase2":false,
   "application.procurement_officer_dashboard_phase2.phase2_dashboard_records":false,
   "application.procurement_officer_dashboard_phase2.phase2_forward_app_records":false,
   "application.procurement_officer_dashboard_phase2.selected_vendor_quotation":false,
   "application.procurement_officer_dashboard_phase2.create_application_phase2":false,
   "application.procurement_officer_dashboard_phase2.store_application_phase2":false,
   "application.procurement_officer_dashboard_phase2.edit_application_phase2":false,
   "application.procurement_officer_dashboard_phase2.update_application_phase2":false,
   "application.procurement_officer_dashboard_phase2.view_application_phase2":true,
   "application.procurement_officer_dashboard_phase2.destroy_application_phase2":false,
   "application.procurement_officer_dashboard_phase2.print_application_phase2":false,
   "application.procurement_officer_dashboard_phase2.get_stock_detail":false,
   "application.disbursement_dashboard.dashboard":false,
   "application.disbursement_dashboard.dashboard_records":false,
   "application.disbursement_dashboard.forward_app_records":false,
   "application.disbursement_dashboard.forward_application":false,
   "application.disbursement_dashboard.add_application":false,
   "application.disbursement_dashboard.save_application":false,
   "application.disbursement_dashboard.edit_application":false,
   "application.disbursement_dashboard.update_application":false,
   "application.disbursement_dashboard.view_application":true,
   "application.disbursement_dashboard.borrower_files":false,
   "application.disbursement_dashboard.borrower_files_records":false,
   "application.disbursement_dashboard.borrower_file_add":false,
   "application.disbursement_dashboard.borrower_file_store":false,
   "application.disbursement_dashboard.borrower_file_view":false,
   "application.disbursement_dashboard.add_grf":false,
   "application.disbursement_dashboard.save_grf":false,
   "application.webmaster_dashboard.pending_projects":false,
   "application.webmaster_dashboard.live_projects":true,
   "application.webmaster_dashboard.success_projects":true,
   "application.webmaster_dashboard.completed_projects":true,
   "application.webmaster_dashboard.expired_projects":true,
   "application.webmaster_dashboard.pending_records":true,
   "application.webmaster_dashboard.live_records":true,
   "application.webmaster_dashboard.success_records":true,
   "application.webmaster_dashboard.completed_records":true,
   "application.webmaster_dashboard.expired_records":true,
   "application.webmaster_dashboard.add_project":false,
   "application.webmaster_dashboard.save_project":false,
   "application.webmaster_dashboard.edit_project":false,
   "application.webmaster_dashboard.update_project":false,
   "application.webmaster_dashboard.view_project":true,
   "application.view_permissions.view_comments":true,
   "application.view_permissions.view_application_log":true,
   "application.view_permissions.view_application_summary":true,
   "application.view_permissions.view_documents":true,
   "application.view_permissions.web_content":true,
   "application.view_permissions.change_borrower_branch":true,
   "application.reporting.applications_progess":true,
   "application.reporting.applications_progess_record":true,
   "application.reporting.view_application":true,
   "application.categories.activate":true,
   "application.categories.dashboard":true,
   "application.meetings.create":true,
   "application.meetings.view_application":true,
   "application.meetings.credit_manager_view_application":false,
   "application.meetings.desk_officer_view_application":false,
   "application.meetings.store":true,
   "application.meetings.index":true,
   "application.meetings.edit":true,
   "application.meetings.view_meeting":true,
   "application.meetings.update_meeting_status":true,
   "application.meetings.update":true,
   "application.meetings.save_call_history":true,
   "application.meetings.get_call_history":true,
   "application.update_cell.get_cell_num":false,
   "application.update_cell.add_call_num":false,
   "application.update_cell.active_cell_num":false,
   "application.update_address.get_address":false,
   "application.update_address.add_address":false,
   "application.head_officer_record.borrower_files":false,
   "application.head_officer_record.borrower_files_records":false,
   "application.head_officer_record.borrower_files_add":false,
   "application.head_officer_record.borrower_files_store":false,
   "application.head_officer_record.borrower_files_view":true,
   "application.rejected_app.dashboard":true,
   "application.rejected_app.dashboard_records":true,
   "application.rejected_app.add":true,
   "application.rejected_app.store":true,
   "application.rejected_app.view":true,
   "application.denied_app.index":true,
   "application.denied_app.records":true,
   "application.denied_app.view":true,
   "application.call_logs.get_borrower_call_logs":false,
   "application.call_logs.save_borrower_call_logs":false,
   "application.borrower_closing.accounts_app":false,
   "application.borrower_closing.accounts_app_records":false,
   "application.borrower_closing.account_add":false,
   "application.borrower_closing.account_save":false,
   "application.borrower_closing.account_view":false,
   "application.borrower_closing.desk_app":false,
   "application.borrower_closing.desk_app_records":false,
   "application.borrower_closing.desk_add":false,
   "application.borrower_closing.desk_save":false,
   "application.borrower_closing.desk_view":false,
   "cms.pages.index":true,
   "cms.pages.create":true,
   "cms.pages.store":true,
   "cms.pages.edit":true,
   "cms.pages.update":true,
   "cms.pages.destroy":true,
   "cms.pages.updateorder":true,
   "cms.contact_us.dashboard":true,
   "cms.contact_us.view":true,
   "cms.contact_us.reply":true,
   "cms.banner.dashboard":true,
   "cms.banner.dashboard_record":true,
   "cms.banner.add":true,
   "cms.banner.store":true,
   "cms.banner.edit":true,
   "cms.banner.update":true,
   "cms.banner.destroy":true,
   "cms.banner.view":true,
   "cms.career.index":false,
   "cms.career.records":false,
   "cms.career.add":false,
   "cms.career.store":false,
   "cms.career.edit":false,
   "cms.career.update":false,
   "cms.career.destroy":false,
   "cms.career.view":false,
   "cms.newsletter.dashboard":true,
   "cms.newsletter.newsletter_list":true,
   "cms.newsletter.newsletter_list_record":true,
   "cms.newsletter.add":true,
   "cms.newsletter.store":true,
   "cms.newsletter.edit":true,
   "cms.newsletter.update":true,
   "cms.newsletter.view":true,
   "cms.newsletter.destroy":true,
   "cms.newsletter.user_list":true,
   "cms.newsletter.user_list_record":true,
   "cms.newsletter.add_user":true,
   "cms.newsletter.store_user":true,
   "cms.newsletter.edit_user":true,
   "cms.newsletter.update_user":true,
   "cms.newsletter.destory_user":true,
   "cms.newsletter.import_user":true,
   "cms.newsletter.save_import_user":true,
   "cms.newsletter.export_user":true,
   "cms.articles.dashboard":true,
   "cms.articles.dashboard_record":true,
   "cms.articles.add":true,
   "cms.articles.store":true,
   "cms.articles.edit":true,
   "cms.articles.update":true,
   "cms.articles.destroy":true,
   "cms.articles.view":true,
   "cms.teams.dashboard":false,
   "cms.teams.dashboard_record":false,
   "cms.teams.create":false,
   "cms.teams.store":false,
   "cms.teams.edit":false,
   "cms.teams.update":false,
   "cms.teams.destroy":false,
   "cms.teams.view":false,
   "cms.ourteams.index":false,
   "cms.ourteams.record":false,
   "cms.ourteams.add":false,
   "cms.ourteams.store":false,
   "cms.ourteams.edit":false,
   "cms.ourteams.update":false,
   "cms.ourteams.destroy":false,
   "dashboard.index":true,
   "dashboard.activity_log.activity_log":true,
   "dashboard.recovery_chart":true,
   "dashboard.application_process_flow_chart":true,
   "dashboard.show_borrowers_location":true,
   "dashboard.branchrecovery_chart":true,
   "dashboard.branch_projects":true,
   "dashboard.application_counts":true,
   "dashboard.user_dashboard":true,
   "dashboard.sms_stats":true,
   "dashboard.google_analytics.google_analytics":true,
   "dashboard.rate_of_recovery":true,
   "dashboard.project_costs.project_costs":true,
   "dashboard.conversation":true,
   "dashboard.director_meeting.dashboard":true,
   "dashboard.director_meeting.dashboard_records":true,
   "dashboard.director_meeting.create":true,
   "dashboard.director_meeting.save":true,
   "dashboard.director_meeting.view":true,
   "dashboard.director_meeting.delete":true,
   "dashboard.project_stats.projects":false,
   "dashboard.project_stats.recovery":false,
   "dashboard.project_stats.exemption":false,
   "dashboard.project_stats.filter":false,
   "service.vendors.dashboard":true,
   "service.vendors.dashboard_record":true,
   "service.vendors.create":true,
   "service.vendors.store":true,
   "service.vendors.edit":true,
   "service.vendors.update":true,
   "service.vendors.destroy":true,
   "service.vendors.view":true,
   "service.products.dashboard":false,
   "service.products.create":false,
   "service.products.store":false,
   "service.products.edit":false,
   "service.products.update":false,
   "service.products.destroy":false,
   "service.products.view":false,
   "service.suggestions.dashboard":true,
   "service.suggestions.dashboard_record":true,
   "service.suggestions.create":true,
   "service.suggestions.store":true,
   "service.suggestions.edit":true,
   "service.suggestions.update":true,
   "service.suggestions.destroy":true,
   "service.suggestions.view":true,
   "service.email_template.dashboard":true,
   "service.email_template.create":true,
   "service.email_template.store":true,
   "service.email_template.edit":true,
   "service.email_template.update":true,
   "service.email_template.destroy":true,
   "service.messages.create_settings":true,
   "service.messages.store_settings":true,
   "service.messages.update_settings":true,
   "service.categories.dashboard":true,
   "service.categories.create":true,
   "service.categories.store":true,
   "service.categories.edit":true,
   "service.categories.update":true,
   "service.categories.destroy":true,
   "service.categories.activate":true,
   "service.recovery.due_slips":false,
   "service.recovery.due_slips_record":false,
   "service.recovery.payment_received":false,
   "service.recovery.payment_received_record":false,
   "service.recovery.recovered_slips":false,
   "service.recovery.recovered_slips_record":false,
   "service.recovery.edit_slip":false,
   "service.recovery.update_slip":false,
   "service.recovery.advance_payment_add":false,
   "service.recovery.view_slip":false,
   "service.recovery.view_received_slip":false,
   "service.recovery.reporting":false,
   "service.recovery.reporting_users":false,
   "service.recovery.add_call":false,
   "service.recovery.add_call_store":false,
   "service.recovery.view_call":false,
   "service.exemption.list_of_exemption":false,
   "service.exemption.list_of_exemption_record":false,
   "service.exemption.list_of_borrower":false,
   "service.exemption.borrower_list_records":false,
   "service.exemption.add":false,
   "service.exemption.save":false,
   "service.exemption.save_files":false,
   "service.exemption.remove_file":false,
   "service.exemption.view_exemption":false,
   "service.exemption.edit":false,
   "service.exemption.update":false,
   "service.countries.dashboard":true,
   "service.countries.view":true,
   "service.countries.edit":true,
   "service.countries.update":true,
   "service.countries.destroy":true,
   "service.complain.listing":true,
   "service.complain.listing_record":true,
   "service.complain.view":true,
   "service.complain.reply":true,
   "service.complain.user_listing":false,
   "service.complain.user_listing_record":false,
   "service.complain.user_add":false,
   "service.complain.user_save":false,
   "service.complain.user_view":true,
   "service.voucher.dashboard":false,
   "service.voucher.dashboard_records":false,
   "service.voucher.add":false,
   "service.voucher.store":false,
   "service.voucher.view":false,
   "service.voucher.edit":false,
   "service.voucher.update":false,
   "service.reschedule.dashboard":false,
   "service.reschedule.dashboard_record":false,
   "service.reschedule.add":false,
   "service.reschedule.store":false,
   "service.configuration.dashboard":true,
   "service.configuration.add":true,
   "service.configuration.store":true,
   "service.event.dashboard":true,
   "service.event.dashboard_records":true,
   "service.event.add":true,
   "service.event.store":true,
   "service.event.edit":true,
   "service.event.update":true,
   "service.event.view":true,
   "service.event.ajax":true,
   "service.event.upload_images":true,
   "service.event.destory":true,
   "service.fieldpartner.dashboard":true,
   "service.fieldpartner.dashboard_records":true,
   "service.fieldpartner.add":true,
   "service.fieldpartner.store":true,
   "service.fieldpartner.edit":true,
   "service.fieldpartner.update":true,
   "service.fieldpartner.view":true,
   "service.fieldpartner.destroy":true,
   "service.fieldpartner.update_approvel":true,
   "service.donor_projects.dashboard":true,
   "service.donor_projects.dashboard_records":true,
   "service.donor_projects.add":true,
   "service.donor_projects.store":true,
   "service.donor_projects.edit":true,
   "service.donor_projects.update":true,
   "service.donor_projects.view":true,
   "service.donor_projects.destroy":true,
   "service.bank_accounts.index":true,
   "service.bank_accounts.create":true,
   "service.bank_accounts.store":true,
   "service.bank_accounts.edit":true,
   "service.bank_accounts.update":true,
   "service.bank_accounts.destroy":true,
   "service.bank_accounts.view":true,
   "service.receipts_verification.borrower_receipts":false,
   "service.receipts_verification.borrower_receipts_records":false,
   "service.receipts_verification.borrower_receipts_add":false,
   "service.receipts_verification.borrower_receipts_save":false,
   "service.receipts_verification.borrower_receipts_view":false,
   "service.reporting.recovery":true,
   "service.reporting.recovered_outstanding":true,
   "service.reporting.recovery_report":false,
   "service.payment_gateway.index":false,
   "service.payment_gateway.records":false,
   "service.payment_gateway.add":false,
   "service.payment_gateway.save":false,
   "service.payment_gateway.edit":false,
   "service.payment_gateway.update":false,
   "service.payment_gateway.destroy":false,
   "user.users.index":true,
   "user.users.create":true,
   "user.users.store":true,
   "user.users.edit":true,
   "user.users.update":true,
   "user.users.destroy":true,
   "user.users.activate":true,
   "user.users.profile":true,
   "user.users.view":true,
   "user.users.upload_profile_picture":true,
   "user.users.update_profile":true,
   "user.users.login_history":true,
   "user.users.change_password":true,
   "user.users.user_change_password":true,
   "user.users.user_change_branch":true,
   "user.roles.index":true,
   "user.roles.create":true,
   "user.roles.store":true,
   "user.roles.edit":true,
   "user.roles.update":true,
   "user.roles.destroy":true,
   "user.branches.index":true,
   "user.branches.dashboard_record":true,
   "user.branches.create":true,
   "user.branches.store":true,
   "user.branches.edit":true,
   "user.branches.update":true,
   "user.branches.destroy":true,
   "user.branches.approve":true,
   "user.branches.change_status":true,
   "user.branches.remove_admin":true,
   "user.branches.branch_profile":true,
   "user.branches.branch_profile_update":true,
   "user.branches.tree_structure":true,
   "user.branches.request_delete":true,
   "user.branches.request_cancel":true,
   "user.branches.request_confirm":true,
   "user.branches.request_confirm_store":true,
   "user.branches.exemption_quota_edit":true,
   "user.branches.exemption_quota_update":true,
   "user.branch_dashboard.index":false,
   "user.branch_dashboard.branch_listing_json":false,
   "user.branch_dashboard.branch_profile":false,
   "user.branch_dashboard.update_branch_info":false,
   "user.branch_dashboard.show_branch_role":true,
   "user.branch_dashboard.assign_branch_role":true,
   "user.branch_dashboard.branch_user_list":false,
   "user.branch_dashboard.all_branches_users":false,
   "user.branch_dashboard.add_branch_user":true,
   "user.branch_dashboard.save_branch_user":true,
   "user.branch_dashboard.edit_branch_user":false,
   "user.branch_dashboard.update_branch_user":false,
   "user.branch_dashboard.remove_branch_user":false,
   "user.branch_dashboard.activate":false,
   "user.site_user.index":true,
   "user.site_user.view":true,
   "user.donor.index":true,
   "user.donor.list_records":true,
   "user.donor.add":true,
   "user.donor.save":true,
   "user.donor.edit":true,
   "user.donor.update":true,
   "user.donor.view":true,
   "user.donor.destroy":true,
   "user.donor.change_password":true,
   "user.donor.update_password":true,
   "user.donor.add_balance":true,
   "user.donor.save_balance":true,
   "user.donor.remove_balance":true,
   "user.donor.ledger_view":true,
   "user.donor.donate":true,
   "user.donor.donate_ajax":true,
   "user.donor.donate_save":true,
   "user.guest.index":true,
   "user.guest.records":true,
   "user.guest.add":true,
   "user.guest.save":true,
   "user.guest.edit":true,
   "user.guest.update":true,
   "user.guest.view":true,
   "user.guest.destroy":true,
   "user.guest.add_balance":true,
   "user.guest.save_balance":true,
   "user.guest.remove_balance":true,
   "user.guest.ledger_view":true,
   "user.guest.donate":true,
   "user.guest.donate_ajax":true,
   "user.guest.donate_save":true
}

**Comment by brunogaspar** [comment]
@GhulamJafar 

I just tested with Laravel 5.5.40 and Sentinel v2.0.17, clean install, and created a user through Sentinel, then updated the user permissions using the list above (just converted to be a PHP array, instead of a JSON string) and it saved the permissions fine.

Did the same for a role, worked the same way.

I even added a few more permissions, seems to be working as expected.

So it's either something on your database that might be blocking this or something on your code.

**Comment by GhulamJafar** [comment]
@brunogaspar 
Thanks you so much for your kind response.

Okay, I will see my code as well. Do database column fine with text-long type?

**Comment by brunogaspar** [comment]
@GhulamJafar 

LongText should also work as expected.

I'm curious, what MySQL version are you using?

**Comment by GhulamJafar** [comment]
We are using MySql version 5.6.38.

**Comment by brunogaspar** [comment]
Going to close as i don't really think it's a problem within Sentinel as i personally could never reproduce the issue 😞

**Comment by GhulamJafar** [comment]
This is resolved now. There is php issue, No of variables were 500, I just
made it 2000. Issue fixed.

Thanks,
Jafar
