### ISSUE TITLE
IP exclusion 

### ISSUE THREAD

**Issue by gwiwoloku** [cartalyst/sentinel#431]
Hi,

Is there a way to bypass the Sentinel checkpoint so a set of ips won't it the throttle?

Thanks

**Comment by basherdesigns** [comment]
I would also like to know how you could "whitelist" an IP so it is excluded from throttling. Thanks!

**Comment by brunogaspar** [comment]
Hello

This doesn't seem to be possible at the moment but would be a very good feature to have implemented i think.

We totally welcome it if someone want's to try to implement it.

As a workaround and one of the ways to achieve this is by using a middleware, where you check the IP address and disable throttling if that IP is within a range of IP's for example.
