### ISSUE TITLE
make username as unique as email

### ISSUE THREAD

**Issue by mimbar** [cartalyst/sentinel#433]
Hi, I managed to use username than email to authenticate. I'm done with login, register and edit user. But i just found out the username don't do unique auth as email did. so if there username "admin" and edit some user with similar username that exist in table, it saved. but not working with email because it's unique.

is there any way to make Username unique too ?
thanks !

**Comment by brunogaspar** [comment]
Hello @mimbar 

You'll need to add uniqueness to the username column as well using the `$this->unique('username');`on a migration, similar to how do [here](https://github.com/cartalyst/sentinel/blob/2.0/src/migrations/2014_07_02_230147_migration_cartalyst_sentinel.php#L107) for the email column.

Other solution would be to also validate the username for uniqueness using the Laravel validator when creating the users.

Hope it helps.
