### ISSUE TITLE
Sentinel Throttle implementation. getThrottleRepository returning null.

### ISSUE THREAD

**Issue by alankarglobant** [cartalyst/sentinel#444]
The documentation is also not supportive for throttle implementation. 
`Sentinel::getThrottleRepository()` return null.  

`Call to a member function setUserThresholds() on null` error returns when : `$throttle = Sentinel::getThrottleRepository()->setUserThresholds(5);`

**Comment by alankarglobant** [comment]
Sorry for the Sentry check issue it was the middleware integration not related with the Sentinel. Apologies for the same.

**Comment by brunogaspar** [comment]
It seems the Throttling repository is not being set on the Sentinel instance, only on the Checkpoint.

Adding `$sentinel->setThrottleRepository($app['sentinel.throttling']);` around line 321 of the `SentinelServiceProvider` seems to solve the problem.

@suwardany Was there any reason or was pretty much forgotten?
