### ISSUE TITLE
How to change login fields?

### ISSUE THREAD

**Issue by JospyK** [cartalyst/sentinel#445]
Hi everyone. Hope you're doing good.
I'm using laravel 5.4 on a project right now and I want to **change** actual login field (**email and password**) **by** something like **Phone and password**. I don't know how to manage that. And of course I'm using Sentinel package for my Auth System.
Could someone help me solve this issue? Thanks to everyone.

**Comment by Surya1995** [comment]
simple just add in login columns
project/config/platform-users.php
`
'login_columns' => [
        'email',
        'password',
    ],

'login_columns' => [
        'email',
        'phone',
        'password',
    ],
`

**Comment by JospyK** [comment]
thank you @Surya1995
