### ISSUE TITLE
Sentinel and Laravel Horizon

### ISSUE THREAD

**Issue by RalphMRivera** [cartalyst/sentinel#456]
Hi,

I’ve been trying to get Horizon to work with Sentinel and I’m not having any luck.

Horizon provides the following gate:

```
    protected function gate()
    {
        Gate::define('viewHorizon', function ($user) {
            return in_array($user->email, [
            ]);
        });
    }
```

But calling something like `Sentinel::check()` here always results in false. I know that Horizon is designed to work seamlessly with the built in Laravel Auth, but I’m not sure how to get it working with Sentinel. I’d like to be able to call the check and then test against the logged in user’s email address.

Any ideas?

**Comment by brunogaspar** [comment]
Hello @RalphMRivera 

Can you try to add the following on the  `boot()` method of the published `HorizonServiceProvider`

```php
Horizon::auth(function ($request) {
    $user = $request->user();

    return $user && $user->isAdmin();
});
```

If that works, you don't need the `Gate` call below as it's overriding the default way Horizon uses to authenticate.

Adjust the code as needed though.

**Comment by RalphMRivera** [comment]
Thanks @brunogaspar
