### ISSUE TITLE
Call to undefined method Illuminate\Foundation\Application::share()

### ISSUE THREAD

**Issue by sumagowda** [cartalyst/sentinel#458]
I have been trying to install this for Laravel 5.4
Although I try php composer.phar require cartalyst/sentinel "2.0.*"
It seems to be installing old version & i get this error below:

Call to undefined method Illuminate\Foundation\Application::share()
--
in SentryServiceProvider.php line 76

**Comment by Luke-SF** [comment]
What was the solution? Seeing this with Laravel 8.75 as well.
