### ISSUE TITLE
How to get users by permission?

### ISSUE THREAD

**Issue by sontungx305** [cartalyst/sentinel#460]
Hello,
I was wondering, is there a best way to get all users who have specify permission ?
I am looping through every users and checking with hasAccess?? But if there are a lot of users, it is very slow.
```php
public static function getUsersByPermission ($permission) {
    $result = [];
    $users = Sentinel::getUserRepository()->get();
    foreach ($users as $user) {
        if($user->hasAccess($permission)) {
            $result[] = $user;
        }
    }
    return $result;
}
```

**Comment by brunogaspar** [comment]
This is indeed not easy to perform.

What @cbj4074 suggested is one of the ways to do it.

Either way, going to close the issue as there's, unfortunately, not much we ca do here i'm afraid.

But do let me know if you think otherwise :)
