### ISSUE TITLE
Throttling: proxy ip address is being recorded instead of real remote address

### ISSUE THREAD

**Issue by underdpt** [cartalyst/sentinel#463]
Hi,

We have some sites behind a proxy, and today found that all users were kick off of one site due to a Throttling Exception. Investigating the issue we found that all ips recorded on the `throttle` table are the same: the ip address of the proxy server.

I think this is related to #62, (by the way that issue is closed but a quick look reveals that no change was made to the code).

We should have a way to enforce the keys used to guess the ip, and the order in which those keys are to be checked.

**Comment by brunogaspar** [comment]
Hello @underdpt 

If you have a good way to achieve that, please submit a pull request :)

**Comment by kfeng0806** [comment]
I think your issue is relate to TrustedProxy, you should read the Laravel Doc 
https://github.com/fideloper/TrustedProxy

**Comment by kfeng0806** [comment]
Try to set 
```
protected $proxies = '0.0.0.0/0';
```
in `app/Http/Middleware/TrustProxies.php`

**Comment by brunogaspar** [comment]
@underdpt Please give a try on what @kfeng0806 suggested.

If that still does not work, we can try to work some other solution inside Sentinel perhaps.
