### ISSUE TITLE
[proposal] restructure tests

### ISSUE THREAD

**Issue by 8633brown** [cartalyst/sentinel#484]
```tests/Throttling/ThrottleCheckpointTest.php``` should become ```test/Checkpoints/ThrottleCkeckpointTest.php``` as it does not test throttling it tests checkpoints.

```tests/Checkpoints/CheckpointsTest.php``` should be merged into ```tests/SentinelTest.php``` as it doesnt test checkpoints it tests sentinel calls the relevant checkpoints which is mostly covered in ```SentinelTest.php```

~~also could the ```PermissibleTrait``` class be modified to use a class instead of a string for the permissableClass instance. it would make testing easier for users and roles. and to me it makes sense to typehint ```PermissibleTrait::setPermissionsClass``` for PermissionsInterface instead of a string.~~
forget this not the right thing to do.

**Comment by brunogaspar** [comment]
Seems you've submitted a pull request :)
