### ISSUE TITLE
laravel 6 support

### ISSUE THREAD

**Issue by lorvent** [cartalyst/sentinel#486]
Hope you are aware, laravel 6 is about to release on sep 3rd.

please make package compatible with laravel 6, currently i am unable to install it.

thanks.

**Comment by brunogaspar** [comment]
It's on the `master` branch at the moment.

Will be released after a few days of Laravel 6 release.

**Comment by brunogaspar** [comment]
Sorry, did not meant to close it :)

**Comment by lorvent** [comment]
Sorry didn't check master branch

Happy to know you are already prepared it. :)

**Comment by lorvent** [comment]
Can you please tag the release?

laravel 6 is released..

**Comment by brunogaspar** [comment]
Later in the week or during the weekend.

**Comment by MatanYadaev** [comment]
Can you please release the changed? Thanks ☺️

**Comment by brunogaspar** [comment]
Hopefully tomorrow, but it's not forgotten, do not worry :)

**Comment by juanpscotto** [comment]
Any news? Thanks.

**Comment by lorvent** [comment]
Looking at all the commits and improvements they are making, probably it worths waiting.

**Comment by juanpscotto** [comment]
Thanks!!
