### ISSUE TITLE
Question: Exceptions

### ISSUE THREAD

**Issue by gregorskii** [cartalyst/sentinel#50]
Hi there,

It appears this package has less granular exceptions on authenticate, login, and create user than Sentry does.

Is there a reason for this?

Also,

I found that if a user had not activated their account calling Sentinel::check() inside of a view throws a "NotActivatedException" exception that cannot be caught in the view. What is the process for doing so?

**Comment by lorvent** [comment]
@AbdullahDiaa can you tell how did you create custom exceptions for `LoginRequiredException` ?

i mean how you are handling it?
