### ISSUE TITLE
Return value of Cartalyst\Sentinel\Users\EloquentUser::getPermissions() must be of the type array, string returned

### ISSUE THREAD

**Issue by no0by5** [cartalyst/sentinel#513]
### Your Environment

- OS and Version: Windows 10
- PHP Version: 7.2.19
- Sentinel Version: 3.0.3

### Expected behaviour
A call to Cartalyst\Sentinel\Users\EloquentUser::getPermissions() should not throw an exception.

### Actual behaviour
It throws 

> Symfony\Component\Debug\Exception\FatalThrowableError
> "Return value of Cartalyst\Sentinel\Users\EloquentUser::getPermissions() must be of the type array, string returned"

### Steps to reproduce
In my Middleware i call ``` abort_unless(($user ? $user->hasAccess($permission) : false), 403); ```
I tried adding permissions with
```
$user->addPermission('roles.create');
```
```
$user->setPermissions(['roles.create' => true]);
```
``` 
$user->permissions = [
    'roles.create'  => true,
];
 ```
In every case the Exception is thrown.<br>
With Sentinel v2 it has been working like this.

**Comment by 8633brown** [comment]
The only way I can seem to replicate this is by running ```$user->permissions = 'roles.create'```
and writing this to the DB. This writes the string directly to the DB. Then when trying to read back with ```EloquentUser::hasAccess``` I get the mentioned error. 

I cant replicate the error with the other steps you gave.

https://github.com/8633brown/sentinel/blob/b42950536814186504e5f832b2c46cc20a801bf7/tests/Sentinel513Test.php#L84-L147

**Comment by no0by5** [comment]
I found the problem. I have my own user model where I overwrite the casts variable. Since the new Sentinel version this is also used by Sentinel's user model to cast the permissions into json. I didn't have this cast in my casts variable, which led to the problem. It would have been helpful if this had been in the update news.
https://github.com/cartalyst/sentinel/blob/3.0/src/Users/EloquentUser.php#L64-L71
