### ISSUE TITLE
How to search user by it's first name?

### ISSUE THREAD

**Issue by Nereg** [cartalyst/sentinel#518]
Hello ! I want to search for user by user's first name or any column . First I tryed code like this :
``` php
        $credentials = [
            'last_name' => $name
        ];
        $LocalUser = Sentinel::findByCredentials($credentials);
``` 
but every time I got just null even when in DB is user with that value of `last_name`! Please help !

**Comment by Nereg** [comment]
Any guesses ?

**Comment by brunogaspar** [comment]
That's to find a User by credentials, it's not designed to perform regular searches on such fields, unless you define those fields to be used as credentials..

You need to either use the User model or the User repository:

Something like

```php
$user = Sentinel::getUserRepository()->createModel()->where('first_name', $firstName)->firstOrFail();
```

After the `createModel()` call is all Laravel Eloquent, so you can perform any kind of query with it.
