### ISSUE TITLE
Laravel 6.0 and sentinel 3.0 integration issue

### ISSUE THREAD

**Issue by meekahCodes** [cartalyst/sentinel#528]
### Your Environment

- OS and Version: Windows 10
- PHP Version: 7.4.0
- Sentinel Version: 3.0

Expected behaviour
---------------------
Am trying integrate sentinel 3 with my laravel 6.0 project through composer. 

Actual behaviour
------------------
But its not getting integrate as expected, giving an error as below image
![Capture](https://user-images.githubusercontent.com/43058453/77996709-c0a4f900-734b-11ea-8b7e-41fe3b4ed0b4.JPG)

Steps to reproduce
-------------------------
I tried to re-install sentinel by running following commands still not works .

1.composer dump-autoload
2.php artisan clear-compiled
3. php artisan config:cache
4. composer require cartalyst/sentinel "3.0.*"

**Comment by brunogaspar** [comment]
No need to open several issues for the exact same thing.

#520
