### ISSUE TITLE
i cant use middleware auth or guest inside of my routes

### ISSUE THREAD

**Issue by christmex** [cartalyst/sentinel#551]
### Your Environment

- OS and Version: 5.9.0-kali1-amd64
- PHP Version: 7.4.11
- Sentinel Version: 4.0

hi FOA i want to say sorry for my English, so i just want to ask , is that normal when i use sentinel i cant use auth middleware inside my routes ?  thank you so much

**Comment by brunogaspar** [comment]
Hello @christmex 

Do you have any simple example that shows this behaviour?

**Comment by christmex** [comment]
> Hello @christmex
> 
> Do you have any simple example that shows this behaviour?


hi thx for repling my issue, my code look like this
(Controller for login with sentinel)
`$credentials = [
            'email'    => $request->email,
            'password' => $request->password,
            'remember' => $remember
        ];

        $auth = Sentinel::authenticate($credentials);`

routes
`Route::group(['middleware' => 'auth'], function(){
    // Pengaturan system
    Route::livewire('/roles', 'roles.index')->name('roles');
    Route::get('/logout','SystemController@logout');	
});
`


so when I use sentinel when I want to access route inside of auth middleware, I still cant access them, why? cuz when I check the session, there is no session, I hope u get it, thank you

**Comment by brunogaspar** [comment]
The only things i can think at the moment: 
- Your routes might not be using or inside the web middleware
- Permissions so that Laravel would start and store session

Without good reproducible steps, can't really help much, sorry.
