### ISSUE TITLE
How do I get Sentinel to authenticate checking additional fields?

### ISSUE THREAD

**Issue by arkid** [cartalyst/sentinel#554]
I have added an additional criteria to the authenticate() call in Sentinel as I have a column in my users table called 'enabled'.  That needs to be set to 1 for a user to login.    My authentication request to Sentinel is as follows:

`if (Sentinel::authenticate(['username'=> $request->log, 'password' => $request->pwd, 'enabled' => 1],$rememberMe)){`

however even for users where the record is set to 0, the authentication still passes.   It seems that this enabled field is just ignored completely.

What am I doing wrong ?

**Comment by brunogaspar** [comment]
Hi

You can achieve this by [Extending Sentinel](https://github.com/cartalyst/sentinel/wiki/Extending-Sentinel), more specifically, the [User model](https://github.com/cartalyst/sentinel/blob/5.x/src/Users/EloquentUser.php).

Then on the extended User model, you need to add a `protected $loginNames = ['email', 'enabled'];` property, which be [default](https://github.com/cartalyst/sentinel/blob/5.x/src/Users/EloquentUser.php#L95) only contains the `email` field.

Hope it helps.

**Comment by arkid** [comment]
Thanks so much @brunogaspar , that did the trick!
