### ISSUE TITLE
PostgreSQL ERROR: operator does not exist: boolean = integer

### ISSUE THREAD

**Issue by Aslam97** [cartalyst/sentinel#557]
- OS and Version: Ubuntu 20.4
- PHP Version: 7.4
- Sentinel Version: 2

I am using postgres.

`Sentinel::authenticate([], remember)` gives error `boleean = integer`, seem like laravel transfrom `true` to `1` which produce error `boolean = integer`

![Screenshot](https://user-images.githubusercontent.com/25027592/116941619-3e97aa00-ac9a-11eb-8aaf-ea58e136fa98.png)

I was able to fix this issue by changing this line inside `Cartalyst\Sentinel\Activations\ActivationRepositoryInterface` from

```
->where('completed', true)
```
to

```
->where('completed', 'true')
```

**Comment by brunogaspar** [comment]
Hello

This seems to be a bug on Eloquent itself, i think.

**Comment by Aslam97** [comment]
I couldn't find any solutions for this without changing the vendor file. but for temporary solution I will just use VCS repository.

**Comment by brunogaspar** [comment]
Not sure if this is extremely relevant for your case https://github.com/laravel/framework/issues/37247
