### ISSUE TITLE
Cartalyst\Sentinel\Users\EloquentUser::getUserId(): Return value must be of type int, null returned

### ISSUE THREAD

**Issue by tidcp** [cartalyst/sentinel#560]
### Your Environment

- OS and Version: MacOS, Laravel 6
- PHP Version: 8
- Sentinel Version: 3.0.4

### Expected behaviour

Activation::completed($user) to return boolean

### Actual behaviour

Activation::completed($user) results in error Cartalyst\Sentinel\Users\EloquentUser::getUserId(): Return value must be of type int, null returned

public function getUserId(): int
{
      return $this->getKey();
}

### Steps to reproduce

Calling Activation::completed() anywhere leads to this error

**Comment by brunogaspar** [comment]
This should be addressed on v8.
