### ISSUE TITLE
illuminate/ packages older version

### ISSUE THREAD

**Issue by vitorn1234** [cartalyst/sentinel#562]
### Your Environment

- OS and Version: #.#.#
- PHP Version: 8.0
- Sentinel Version: 5*

### Expected behaviour

update to laravel 9

### Actual behaviour

can't update to laravel 9

### Steps to reproduce

    - illuminate/support[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.0.15) does not satisfy that requirement.
    - Root composer.json requires cartalyst/sentinel ^5.1 -> satisfiable by cartalyst/sentinel[v5.1.0, 5.x-dev].

**Comment by suwardany** [comment]
Sentinel 6 for Laravel 9 is on the master branch, make sure your minimum stability is set to `dev`, you can then install it using `"cartalyst/sentinel": "^6.0"`

A tag will be released in the coming days.
