### ISSUE TITLE
Support for Laravel 9.6 and PHP 8.*

### ISSUE THREAD

**Issue by creanso-niziol** [cartalyst/sentinel#564]
I have my own CMS based on Laravel 8. *. I wanted to update it to the highest version 9.6. Unfortunately, the compatibility limitations of the cartalyst / sentinel library make it impossible to perform such a procedure. Are you planning to release an update? Should I however look for a different solution?
Thank you in advance for your answer. Best wishes.

  Problem 1
    - Conclusion: don't install cartalyst/sentinel v5.1.0 (conflict analysis result)
    - Root composer.json requires cartalyst/sentinel ^5.1 -> satisfiable by cartalyst/sentinel[v5.1.0, 5.x-dev].
    - Conclusion: don't install laravel/framework v9.6.0 (conflict analysis result)
    - cartalyst/sentinel 5.x-dev requires illuminate/support ^8.0 -> satisfiable by illuminate/support[v8.0.0, ..., 8.x-dev].
    - Only one of these can be installed: illuminate/support[v4.0.0-BETA2, ..., 4.2.x-dev, v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev], laravel/framework[v9.6.0, 9.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^9.6.0 -> satisfiable by laravel/framework[v9.6.0, 9.x-dev].

**Comment by brunogaspar** [comment]
You can use the `master` branch for now.

**Comment by suwardany** [comment]
`v6.0.0` for Laravel 9 has been released.
