### ISSUE TITLE
Laravel 10 Support

### ISSUE THREAD

**Issue by rbridge** [cartalyst/sentinel#567]
With the February 14, 2023 release of Laravel 10, is there any chance we will see an update to support the latest version?

**Comment by MirazMac** [comment]
Any updates?

**Comment by ultrono** [comment]
Are there any updates as Laravel 10 was released over week ago :)

**Comment by brunogaspar** [comment]
v7.0.0 released

**Comment by ultrono** [comment]
Is this an active project? I can't see any commits for 8 months :/

> v7.0.0 released

Perfection, was just coming to terms with replacing this package with Breeze, something I don;t particularly want to do doing :)
