### ISSUE TITLE
support laravel 11

### ISSUE THREAD

**Issue by hooman-mirghasemi** [cartalyst/sentinel#574]
https://github.com/cartalyst/sentinel/pull/573

**Comment by joshcadman01** [comment]
@hooman-mirghasemi - I have just forked this package with support for Laravel 11, that you can install with `composer require joshcadman01/cartalyst-sentinel`.

**Comment by LiXunGuan** [comment]
Is this package no longer maintained? I'm thinking of migrating to laravel-permission

**Comment by hooman-mirghasemi** [comment]
@LiXunGuan 
I agree with you it looks like the maintainer abandoned this package

**Comment by brunogaspar** [comment]
v8.0.0 released
