### ISSUE TITLE
No one responding to support emails after purchased subscription

### ISSUE THREAD

**Issue by interactiveRob** [cartalyst/sentinel#576]
I bought a Cartalyst Arsenal subscription to use sentinel-kickstart to lay the groundwork for user-management in my application. Sentinel-kickstart isn't in active development and doesn't run on PHP 8 so I immediately requested a refund via help@cartalyst.com and followed up twice to no response.

**Comment by drsii** [comment]
Hey Rob,  Apologies. We'll of course get you that refund.

I'd look at platform instead of sentinel kickstart. kickstart was meant more as a demo for sentinel.

Platform however is a full application base with user management already baked in.
