### ISSUE TITLE
Decent ACL examples with Sentinekl

### ISSUE THREAD

**Issue by darkweb2015** [cartalyst/sentinel#83]
Hi all, 

I have been hunting for a good user authentication package and my search lead me to Cartalyst sentinel which I believe has now been made open-source (Great!!).

Just wondering, are there any decent examples for ACL?  From what I have seen, the roles system looks really nice.  Just trying to think of a good way of dynamically building a permissions like that can be used.

Can a list of permissions be generated from special tags set in Controllers? Is that the best way of doing it?  Or should I add the list of permissions to a file and load that file in an admin interface and assign those permissions to roles?

Any tips, ideas or links with this will be really helpful.

Thank you...

Samuel

**Comment by brunogaspar** [comment]
Hey,

How you store the permissions, either on a file(s) or on the database so you can manage them in your UI/UX, is really up to you, we don't have any specific needs nor there is a recommended or best way.

Assigning permissions, you can either assign permissions to a role(s) or to an user(s), you can obviously do both if you need a bit more of control. 
If you just assign the permissions to a role(s) , just assign the role(s) to your user(s).

Regarding the permission checking, it really depends on how you want to have it working/behaving and on your skill level.

If you are using Laravel, you can use filters (Laravel 4.2) or middlewares (Laravel 5.0+), in there you could check if the user is authenticated, check if the user has access to the route he's in by either using the Controller@method name or even the named route, but as i said, it really depends and is pretty much up to you to figure it out. 
If you don't feel that fancy, you can do these checks on your controllers methods.

Again, there's no best way or recommended way, is really up to the developer to decide how to better structure the application to fulfil his needs.

Hope it helps.
