### ISSUE TITLE
Use custom configuration file without Laravel integration

### ISSUE THREAD

**Issue by joppuyo** [cartalyst/sentinel#84]
Hey, awesome that you open sourced Sentinel!

I just have a one quick question: the documentation does not specify how to use a custom configuration if you are not using the Laravel integration.

**Comment by brunogaspar** [comment]
You need to use the setter methods, that's what it does through the Laravel service provider, for example [here](https://github.com/cartalyst/sentinel/blob/2.0/src/Laravel/SentinelServiceProvider.php#L333)

**Comment by joppuyo** [comment]
I'm not sure if it's the right way, but I registered a custom configuration using the following code:
```
use Cartalyst\Sentinel\Native\Facades\Sentinel;
$config = new Cartalyst\Sentinel\Native\ConfigRepository('customSentinelConfig.php');
$bootstrapper = new Cartalyst\Sentinel\Native\SentinelBootstrapper($config);
Sentinel::instance($bootstrapper);
```
Maybe creating a custom configuration file could be better documented in the documentation because not everyone using the Sentinel library relies on Laravel.
