### ISSUE TITLE
Register method does not throw exception of user already exists in the system.

### ISSUE THREAD

**Issue by joppuyo** [cartalyst/sentinel#85]
When using register method and trying to add an user with an email address that already exists in the system, sentinel does not throw an exception but and SQL exception "SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'user@example.com' for key 'users_email_unique'" is thrown instead.

**Comment by brunogaspar** [comment]
It's on our list for v3, to have better exceptions.

**Comment by shashvattrip** [comment]
So how do we handle such exceptions for now?

**Comment by brunogaspar** [comment]
Check if a user is already in your system before calling the register method.
