### ISSUE TITLE
Sentinel Jenssegers/MongoDB Laravel 4.2

### ISSUE THREAD

**Issue by KudlaiViktor** [cartalyst/sentinel#86]
I'm trying to integrate Sentinel with Henssegers mongoDB package, but it's not work for me. 
Earlier I used Sentry and everything was ok.

Now I'm getting error 

Argument 2 passed to Illuminate\Database\Query\Builder::__construct() must be an instance of Illuminate\Database\Query\Grammars\Grammar, null given, called in /home/vagrant/shared/muzza/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 1853 and defined

I guess problem because need to extend Jenssegers\Mongodb\Model, but don't know how.
Please, help to figure out! Thanks.

**Comment by GrahamCampbell** [comment]
Laravel 4.2 doesn't seem to be a supported version.

**Comment by KudlaiViktor** [comment]
Version of Sentinel? I'm using 1.1 version of this lib.

**Comment by GrahamCampbell** [comment]
There is no version 1.1?

**Comment by KudlaiViktor** [comment]
https://cartalyst.com/manual/sentinel/1.0#introduction - Sentinel version which i'm using.
https://github.com/jenssegers/laravel-mongodb - Jenssegers MongoDB (using v~2.0).

It's difficult to believe that Sentinel haven't mongoDB support.

**Comment by drsii** [comment]
You would have to write the implementations for the different models used throughout Sentinel.

Then switch out the models for the different entities on the config file with your own implementations, Sentinel should take care of everything else.

**Comment by KudlaiViktor** [comment]
Is it the correct implementation? 

```
<?php 
namespace App\Models;
class Throttling extends Common
{}
```
```
<?php namespace App\Models;
use Jenssegers\Mongodb\Model;
class Common extends Model
{}
```
And in the Sentriel config file 
```
'throttling' => [
		'model' => 'App\Models\Throttling',
...
```

**Comment by Maxime-BHA** [comment]
As @jenssegers already did for Sentry package, you have to create your own Models extending the originals models from Sentinel and bind the attributes defined in those models for relationships/persistances to the new models etc.. like `static $usersModel = 'Cartalyst\Sentinel\Users\EloquentUser';` and also change the config file.

See exemple for Sentry there :
https://github.com/jenssegers/laravel-mongodb-sentry

I think it's the exact same procedure :smile_cat:
