### ISSUE TITLE
Multiple User Models

### ISSUE THREAD

**Issue by rahul-rkt** [cartalyst/sentinel#88]
I have multiple users model -
i) normal users with their set of columns and permissions
ii) administrators who have their own set of columns and permissions

I don't want to put in everything in one table as the columns are quite different. I have set the users model in cartalyst.sentinel config as my own UserModel which extends EloquentUser.

How can I implement the same for my AdministratorModel which also extends EloquentUser, and easily attach roles, permissions, authentication, etc? I also can have more such models where I want to use sentinel features.

**Comment by brunogaspar** [comment]
This is not supported out of the box, but you can still achieve it.

You can read [this](https://gist.github.com/leabdalla/5999421) tutorial, for Sentry, and see how it was applied there and apply the same technics on Sentinel.
