### ISSUE TITLE
Contributing guide

### ISSUE THREAD

**Issue by necrogami** [cartalyst/sentinel#89]
The contributing guide should list PSR-1, PSR-2 and PSR-4 but PSR-2 is missing.

**Comment by necrogami** [comment]
Actually the whole of the code styling should be gone back over as it's changed with the move to PSR-2

**Comment by drsii** [comment]
Hi @necrogami Sentinel 2 only follows psr-1 and psr-4. Version 3 however will follow PSR-2 as well.

Our newer packages follow a specific pattern.

https://medium.com/cartalyst-development/understanding-package-implementations-a8eaa20d9b00

Sentinel 3 is being developed outside this repository for the time being to avoid confusion.

**Comment by necrogami** [comment]
@drsii If Sentinel 2 only follows PSR-1 and 4 then why in the changelog on 2-24 does it say

v2.0.0 - 2015-02-24

Updated for Laravel 5.
REVISED

Switched to PSR-2.

**Comment by drsii** [comment]
Actually I stand corrected. Long night... I'll update
