### ISSUE TITLE
Logout Issues

### ISSUE THREAD

**Issue by AzzAToTV** [cartalyst/sentinel#90]
We have a private community site, using Laravel 5.1 and Sentinel providing the Auth system. We're having an issue where users are randomly getting logged out. I've looked through the code and can't figure out what's causing the issue.

It's not after inactivity either, you could be browsing the site and randomly get logged out.

Can anyone provide some insight into why this may be happening?

**Comment by brunogaspar** [comment]
This seems to be a Laravel issue than anything.

Related to this https://github.com/laravel/framework/issues/8172 maybe.

**Comment by GrahamCampbell** [comment]
You need to run `php artisan cache:config`.

**Comment by GrahamCampbell** [comment]
or config:cache, i can't remember which order those two are, lol

**Comment by Mochaka** [comment]
Thanks for replying @GrahamCampbell but that didn't help.

**Comment by AzzAToTV** [comment]
@GrahamCampbell not sure exactly what that command does, but it didn't help :/

**Comment by drsii** [comment]
@AzzAToTV my hunch here is that it is more then likely an environment issue. Could you provide us some details about the environments the issue has been tested on? Is this happening on development/staging servers. Or is it only on the production server?

**Comment by AzzAToTV** [comment]
@drsii thanks for replying. I'll have to get back to you on that. I haven't really tested it locally or on our development server.

We're running Laravel 5.1 on Ubuntu 14.10 with PHP 5.6.10 and MariaDB10. We're using the redis backend for sessions.

Before switching to Sentinel we were using just the built in Auth system and it worked fine. Ever since we ported over to Sentinel we have had this issue.

**Comment by cryode** [comment]
@AzzAToTV Redis can be configured to not persist data at all, thus losing any existing sessions of your server or the Redis service is ever stopped / restarted. Could be a cause for dropped sessions.

**Comment by AzzAToTV** [comment]
@cryode That's not the issue, we are using redis as our cache and other storage and it's persisting fine. Anyway, i changed it to use file based sessions, and we still get the same issue.

**Comment by brunogaspar** [comment]
Does it logout every single user?

**Comment by AzzAToTV** [comment]
Yeah as far as i know. We have about 1,000 members, quite a few are reporting the issue.

**Comment by brunogaspar** [comment]
If they all get logged out it seems an issue on your application rather than in Sentinel.

I can't reproduce this in any way. If you come up with a way to reproduce this in an application please let us know.

**Comment by AzzAToTV** [comment]
If anyone is interested, i figured it out. We had a checkbox on our login page called remember_me, which i was passing straight to Sentinel. Once i changed it to return a boolean, it started working as expected. I don't know if it's a doc issue or my dumbassness but it's working now :)

**Comment by brunogaspar** [comment]
Glad that you've figured it out.

As mentioned on the [documentation](https://cartalyst.com/manual/sentinel/2.0#sentinel-authenticate), you need to pass a boolean. I believe you can pass an integer of `1` or `0` though, but boolean is the recommended.

**Comment by AzzAToTV** [comment]
Ah yeah i see that now. We did try setting it as a 1 which did not work, so using booleans works.

Thanks
