### ISSUE TITLE
SuperUser.

### ISSUE THREAD

**Issue by berpcor** [cartalyst/sentinel#92]
Is there any way to create super user (can do everything) without adding to him some roles or permissions?

**Comment by brunogaspar** [comment]
Sentinel doesn't have the concept of `superuser`, `root`,  `god` etc.., this is something you need to build/add on your own as it's more flexible this way and you can call it however you want.

You can either add that to the user itself or to a role, using each entity permissions, your call.

Then where you do the permission checks on your application, either it be on a filter/middleware or on each controller/route you just check if the user has access to that area.

Something along these lines to perform the check:

```php
# This is something for you to figure out as it can be called how you want and be retrieve from where you want
$permission = 'admin.users.list';

if (Sentinel::hasAnyAccess(['superuser', $permission])) {
    return $next($request);
}

return abort(403);
