### ISSUE TITLE
Sentinel Oauth-Server

### ISSUE THREAD

**Issue by garagesocial** [cartalyst/sentinel#93]
https://cartalyst.com/manual/sentinel/2.0#sentinel-oauth-server

```
Sentinel Oauth-Server is a Sentinel addon that provides an OAuth server implementation.

Sentinel Oauth-Server is under construction and will be announced at a later date.
```

Any news on that?

**Comment by brunogaspar** [comment]
Hello,

These addons will be released after the Sentinel 3 release, we don't have any ETAs though.
