### ISSUE TITLE
Move /src/migrations to /database/migrations

### ISSUE THREAD

**Issue by DraperStudio** [cartalyst/sentinel#96]
Currently when using Sentinel with Laravel there is an issue that outputs the following everytime I do an composer update or dump-autoload because the migrations are within the src directory which makes no sense to me.

`
Warning: Ambiguous class resolution, "MigrationCartalystSentinel" was found in both "$baseDir . '/database/migrations/2014_07_02_230147_migration_cartalyst_sentinel.php" and "/home/vagrant/Sites/site_name/vendor/cartalyst/sentinel/src/migrations/2014_07_02_230147_migration_cartalyst_sentinel.php", the first will be used.
`

Is there any specific reason that the migrations are within the src folder? They are nothing that should be in there because they don't have any functional purpose so I don't see a reason for the location.

I think they should either be in /database/migrations or /schema together with the mysql schema.

**Comment by GrahamCampbell** [comment]
:+1:
