### ISSUE TITLE
Blade support

### ISSUE THREAD

**Issue by seschi98** [cartalyst/sentinel#99]
Is there a proper way of integrating Sentinel into my L5 application with blade? Or is it just appending the $user variable to my view and doing an blade if-statement? For example:

```php
return view('my.view')->with('user', $user);
```

and
```blade
@if(isset($user))
    Logged in as {{ $user->username }}.
@else
    Guest
@endif
```

A better method could be:
```blade
@permission(my.permission.sub)
...
@endpermission
```
or something similar so that a section is only displayed if you have permission xyz...

**Comment by bypit** [comment]
Yeah, that would be cool and helpful

**Comment by brunogaspar** [comment]
Just use the [View Share](http://laravel.com/docs/5.1/views#sharing-data-with-all-views).
